LunarG/VulkanTools

tests/_vktracereplay.ps1
Trace/PPM can be passed into _vktracereplay.ps1 for regression testing.
Change-Id: Ifce0c5708c257d20198e05ad7c836b760860658c
=> tests: Add old trace testing for windows

vktrace/vktrace_layer/vktrace_lib_trim.cpp
Add barrier to make sure target buffer is ready for copy. When playback trimmed trace file of Sascha Willems sample instancing on some graphic card, some stones lack part of surface (skeletalanimation.exe has similar problem), this change fix the problem.
XCAP-577
Change-Id: I6138e085d5cd303aa732f88ea8bb47152049f7a4
=> Vktrace: fix copy buffer problem

scripts/vktrace_generate.py, vktrace/vktrace_common/CMakeLists.txt, vktrace/vktrace_common/vktrace_trace_packet_identifiers.h, vktrace/vktrace_common/vktrace_trace_packet_utils.c, vktrace/vktrace_common/vktrace_trace_packet_utils.h, vktrace/vktrace_layer/vktrace_lib_trace.cpp, vktrace/vktrace_replay/vkreplay.cpp, vktrace/vktrace_replay/vkreplay.h, vktrace/vktrace_replay/vkreplay_factory.h, vktrace/vktrace_replay/vkreplay_main.cpp, vktrace/vktrace_replay/vkreplay_main.h, vktrace/vktrace_replay/vkreplay_settings.h, vktrace/vktrace_replay/vkreplay_vkreplay.cpp, vktrace/vktrace_replay/vkreplay_vkreplay.h, vktrace/vktrace_trace/CMakeLists.txt, vktrace/vktrace_trace/vktrace.cpp, vktrace/vktrace_trace/vktrace_process.cpp, vktrace/vktrace_viewer/vktraceviewer_QReplayWorker.cpp, vktrace/vktrace_viewer/vktraceviewer_QTraceFileModel.h, vktrace/vktrace_viewer/vktraceviewer_qtracefileloader.cpp, vktrace/vktrace_viewer/vktraceviewer_trace_file_utils.cpp, vktrace/vktrace_viewer/vktraceviewer_trace_file_utils.h
Change-Id: I512ceb6aaded8ae54a48ae6baea046bfb8c4a617
=> vktrace: handle mem types for better trace file portability

vktrace/vktrace_layer/vktrace_lib_pageguardmappedmemory.cpp
…mory watch.
Clear read flag to avoid dead lock when the page is marked as dirty page
by memory watch.
XCAP-585
Change-Id: I3557cbe0f4c6f50556de0a5b7686ee3d2a41d851
=> vktrace: Reset read flag for page if it is marked as dirty page by memory watch

build-android/android-generate.bat, build-android/android-generate.sh, scripts/lvl_genvk.py, scripts/vktrace_file_generator.py, scripts/vktrace_generate.py, scripts/vulkan.py, vktrace/vktrace_replay/CMakeLists.txt, vktrace/vktrace_viewer/CMakeLists.txt
=> VKTRACE: Move vkreplay_vk_func_ptrs.h to use vk.xml-based codegen

build-android/android-generate.bat, build-android/android-generate.sh, scripts/lvl_genvk.py, scripts/vktrace_file_generator.py, scripts/vktrace_generate.py, vktrace/vktrace_layer/CMakeLists.txt, vktrace/vktrace_replay/CMakeLists.txt, vktrace/vktrace_trace/CMakeLists.txt, vktrace/vktrace_viewer/CMakeLists.txt
=> VkTrace: Move vktrace_vk_packet_id.h to xml-based codegen

via/via.cpp
Commit Joey's VIA changes to look in the HKEY_CURRENT_USER registry location for loader registry settings.  Plus, a few cleanups by me.
=> VIA changes

layersvt/api_dump.h, scripts/api_dump_generator.py
- fix `VkPipelineViewportStateCreateInfo::pViewports` UNUSED when not
dynamic
- fix `VkPipelineViewportStateCreateInfo::pScissors` "UNUSED" when not
dynamic
- fix  `VkCommandBufferBeginInfo::pInheritanceInfo "UNUSED" when
secondary
- add flexibility that can help handle similar hard to implement cases
=> layersvt: Fix false UNUSED reports

scripts/vktrace_file_generator.py
Change-Id: I337df3f77c27e5da25a17ef108b67de888cad780
=> vktrace: Fix RROutput cast in codegen

via/via.cpp
Fixes issue discovered in issue #358, but now waiting for @dor666 to verify the changes.  Manual testing on my end looks good.
Change-Id: I45ad38a2a0210da6f27a1fe7634db0f482a808cd
=> via: Fix device-specific registry queries

scripts/vktrace_file_generator.py, vktrace/vktrace_layer/vktrace_lib_trace.cpp
Instead of manually adding entrypoints to a function that takes in a entrypoint name and returns a function pointer, codegen this function.
Reduces pains when adding entrypoints to codegen.
=> vktrace: Codegen name to proc mapping

scripts/vktrace_file_generator.py, vktrace/vktrace_common/vktrace_multiplatform.h, vktrace/vktrace_common/vktrace_trace_packet_identifiers.h, vktrace/vktrace_replay/vkreplay_vkreplay.cpp, vktrace/vktrace_replay/vkreplay_vkreplay.h
=> vktrace: Add codegen for extensions

scripts/vktrace_file_generator.py
Change-Id: Iaf887b483ffd603c6d4344341e93c423fa1c515c
=> vktrace: Add codegen for VK_NV_external_memory_win32

layer_factory/CMakeLists.txt
Parallel build cmake changes broke VLF layers with *.cpp and header files.
=> Fix demo_layer cmake failure

.travis.yml, tests/vlf_test.sh
Also updated linux script for travis script invocation and normalized test output with other tests.
Took a look at the android versions of the test scripts and decided to leave that to The Experts.
=> tests: Add vlf_test to travis CI

tests/CMakeLists.txt, tests/_vktracereplay.ps1, tests/vktracereplay.py
Add vktracereplay.py. For now, this will handle scanning a directory of
old traces, tracing replays of them, and playing them back.
Change-Id: I3fe380dbdb00b72f0eecff83bceccfe3269dafb4
=> tests: Add vktrace/replay regression for Windows

tests/_vktracereplay.ps1
Change-Id: I591b06184e0d58d145d45faf434943c7b97a5079
=> tests: Fix _vktracereplay.ps1 for 32 bit tests

.travis.yml, tests/CMakeLists.txt, tests/apidump_test.ps1, tests/apidump_test.sh
Add powershell and bash scripts to sanity test apidump.  Also added to travis.
=> Add apidump test scripts

tests/vktracereplay.py
Change-Id: I423a792e016a907298f140d568e61d9f5e24b989
=> tests: Fix undefined reference when trace fails

build-android/android-generate.bat, build-android/android-generate.sh, scripts/lvl_genvk.py, scripts/tool_helper_file_generator.py, vktrace/vktrace_common/CMakeLists.txt, vktrace/vktrace_layer/CMakeLists.txt
This was previously in LVL, but was not used there.  Have a separate PR in LVL to remove that version.
=> Move struct_size helper generation into VulkanTools

tests/trace_positive_validation.ps1
Issues have been filed at github, skip these tests until
they are resolved.
Change-Id: I1eda58ff58739bb4e9cdb40682c565ca28d2fd6c
=> Skip tracing / replaying validation tests that have issues

build-android/android-generate.sh
Change-Id: I754641d171e76bc8cd8d78bd1bdcb4f87cc479c6
=> android: Fix reference to vlf_makefile_generator.py

BUILD.md
Update the VulkanTools "Clone the Repository" build steps to
include updating the sub-module.
=> build: Update build doc steps

tests/_vktracereplay.ps1
Change-Id: Ia26d2f7e50b1afad60fa7e6e2c9e1d174ce343d0
=> tests: Run trace_positive_validation for debug builds

via/README.md, vktrace/vktrace.md
Fixed various spelling errors in via and vktrace md files.
=> README: Fixed various spelling errors in via and vktrace .md files

vktrace/vktrace_replay/vkreplay_vkreplay.cpp
Change-Id: I3410a3f147cfc2c818cb81f362b5c24923b8ca83
=> vkreplay: Fix PipelineBarrier queue indices

layersvt/screenshot.cpp
Change-Id: Iff82e219116ebfc07aa757d6026aee6e8881000b
=> Screenshot: Make sure queue can take graphics

vktrace/vktrace.md, vktrace/vktrace_replay/vkreplay.cpp, vktrace/vktrace_replay/vkreplay_main.cpp, vktrace/vktrace_replay/vkreplay_main.h, vktrace/vktrace_replay/vkreplay_settings.cpp, vktrace/vktrace_replay/vkreplay_vkreplay.cpp
Change-Id: Icc8b08c179214eeb4080701fed4fdeb0649fc058
=> vkreplay: Implement --CompatibiltyMode

vktrace/vktrace_replay/vkreplay_vkreplay.cpp
To improve portabiliy of trace files: If presentMode for
vkCreatekSwapchain from trace file is not supported on replay
device, set the presentMode to VK_PRESENT_MODE_FIFO_KHR during
replay of vkCreatekSwapchain.
Change-Id: I4a51ee8f33d72d0b23edcc2c9c757ab929ecc906
=> vkreplay: Possibly modify presentMode in vCreatekSwapchain

layersvt/screenshot.cpp
For thread safety as well as ensuring that the correct
queue family index is used, create a command pool in
WritePPM instead of picking one of the application's.
Change-Id: Ic6b9a76dcdcc8ef5b93938e07f0c0a6cdf539126
=> Screenshot: Create command pool for use in WritePPM

vktrace/vktrace_trace/vktrace_process.cpp
Fix steam game running into crash during capture on console mode
Some Windows steam titles run into crash during capture on console mode,
the reason is the process which is created by vktrace quit right after
it start steam client, steam client then start running the title
binary. The change add child process handling to vktrace watch dog
thread to cover such case.
XCAP-965
Change-Id: Ifd9026351266714974244de8da0a5df54bd7487b
=> vktrace: Fix steam game running into crash during capture

vktrace/vktrace_common/vktrace_trace_packet_utils.c
This is a simple and quick fix to serialize API calls in trace file by
API issue time instead of completion time by setting a mutex lock in
vktrace_create_trace_packet() and release it in
vktrace_delete_trace_packet().
Exceptional APIs: (vktrace_create_trace_packet is called after API's
completion)
* vkCreateInstance
* vkEnumerateDeviceExtensionProperties
* vkEnumerateDeviceLayerProperties
* vkGetPhysicalDeviceQueueFamilyProperties
* vkGetPhysicalDeviceQueueFamilyProperties2KHR
* vkEnumeratePhysicalDevices
* vkGetQueryPoolResults
* vkAllocateDescriptorSets
* vkGetPipelineCacheData
* vkGetPhysicalDeviceSurfaceFormatsKHR
* vkGetPhysicalDeviceSurfacePresentModesKHR
* vkGetSwapchainImagesKHR
=> vktrace: GH473, Serialize API calls by issue time

tests/_vktracereplay.ps1
As of the repo-split, smoketest is removed. Will want to re-add once
smoketest and hologram have been consolodated to test push descriptors
and PMB.
Change-Id: I314e423de7a3575076e13bdc994ec09453e08e91
=> tests: Fix tests for repo-split

.gitignore
Ignore build configurations for the Visual Studio Code IDE
Change-Id: Ic336e171117c3b18cbda3af7eb767ce813aff033
=> gitignore: Add .vscode/ folder

build-android/build_vktracereplay.sh
Change-Id: If7072d5940dcb1909323d939b552cb522d285c51
=> Fix scope of glslang path in android build

build-android/jni/Android.mk, build-android/update_external_sources_android.bat, build-android/update_external_sources_android.sh, build-android/vulkan-tools_revision_android, build-android/vulkan-tools_url_android
This is a partial copy of 87b08879 from Vulkan-ValidationLayers
=> android: Use vulkan_wrapper from Vulkan-Tools

vktrace/vktrace_replay/vkreplay_vkreplay.cpp
Log the requested extensions from the VkInstanceCreateInfo struct when
vkCreateInstance fails with VK_ERROR_LAYER_NOT_PRESENT.
No need to do the same to vkCreateDevice because enabledLayerCount
and ppEnabledLayerNames in vkDeviceCreateInfo are deprecated and
ignored.
This change also moves the restore of saved layers and extensions after
the checking of VkResult returned by vkCreateInstance to make sure the
layers/extensions being printed are the ones being used in the real
call to vkCreateInstance.
=> vkreplay: Log requested layers on failure

vktrace/CMakeLists.txt, vktrace/vktrace_common/CMakeLists.txt, vktrace/vktrace_layer/CMakeLists.txt, vktrace/vktrace_replay/CMakeLists.txt, vktrace/vktrace_trace/CMakeLists.txt, vktrace/vktrace_viewer/CMakeLists.txt
Change-Id: I82895b80191504a820c3a0e0ec5daa7e04aabf64
=> vktrace: Generate gen'd files iff dependencies change

tests/vktracereplay.sh
Change-Id: If1e2edb8544d24cd08c888bedb3aeab586780a62
=> tests: Update vktracereplay.sh and remove smoketest

.appveyor.yml
Pull request needed to trigger AppVeyor on a branch.
Change-Id: If51027c95b735009a1e786e5c26e22513cefb8c9
=> ci: Get AppVeyor working again

tests/trace_positive_validation.ps1
Makes life easier in CI
Change-Id: I332df5c843dac180a61d3a687c62ef17cdb35820
=> tests: Add 32bit support to trace_positive_validation

build-android/build_vktracereplay.sh
No longer depending on SDK for anything
Generate necessary header files for vktrace, but don't build all the layers
Change-Id: If197d20d42a168996aa7007af78775e82339feb7
=> tests: Remove SDK ref and fix android vktrace build

tests/vktracereplay.py
Change-Id: I26dc63644a38ee7870601c277849ad32d9e53562
=> tests: Fix duplicate filenames in loop test

vktrace/vktrace_replay/vkreplay_vkreplay.cpp
Also clean up and make code consistent.
Change-Id: Id5b1e21dcf608bc505518d5fc1970d93c1a50be4
=> vktrace: Choose surface extension based on selected display

scripts/vktrace_file_generator.py, vktrace/vktrace_replay/vkreplay_vkreplay.cpp, vktrace/vktrace_replay/vkreplay_window.h
m_initedVK was not initialized, causing replays to fail.
Change-Id: Ic6170bf93830e2d86e6579030179b13ea97745b5
=> vktrace: Fix uninitialized variable in ReplayDisplay

vktrace/vktrace_layer/vktrace_lib_trace.cpp
vkAllocateDescriptorSets failed with VK_ERROR_OUT_OF_POOL_MEMORY during
some title trimmed trace file playback, it is caused by the error in
tracking allocated descriptorsets for DescriptorPool. The change fix
the error.
XCAP-952
Change-Id: I5c69adbbcf644d679eb6ce197994cffd3cbe3aa1
=> vktrace: fix error of vkAllocateDescriptorSets trim handling

layer_factory/assistant_layer/exclusive_qfi.h, layer_factory/assistant_layer/extension_type_warning.h, layer_factory/assistant_layer/load_op_load_undefined.h, layer_factory/assistant_layer/mem_objects.h, layer_factory/assistant_layer/pipeline_cache_warning.h, layer_factory/assistant_layer/stage_all_warn.h, layer_factory/assistant_layer/zero_counts.h, layer_factory/demo_layer/demo.h, layer_factory/starter_layer/memory_allocation_stats.h, scripts/layer_factory_generator.py
Remove dead constructor parameter and associated arguments.
Change-Id: I9d1fe33969d8820a84a098f57c0c1982b87bb688
=> vlf: Remove dead VLF code

vktrace/vktrace_replay/vkreplay_vkreplay.cpp
Change-Id: I78ed32b1bc8e099653ee098a840ef27cf9b4c618
=> vkreplay: vkCreateInstance give VK_SUCCESS on loop

via/via.cpp
Make sure cube does not generate a pop-up while running.
To resolve Issue #598 .
=> via: No pop-ups in cube

vktrace/vktrace_replay/vkreplay_vkreplay.cpp
This change checks and only uses available/supported instance/device
extensions in compatibility mode to make it possible for a trace file
to be replayed on a platform with less extensions.
=> vkreplay: Filter extensions in compatibility mode

vktrace/vktrace_replay/vkreplay_main.cpp, vktrace/vktrace_replay/vkreplay_vkreplay.cpp, vktrace/vktrace_replay/vkreplay_vkreplay.h
If screenshots are enabled, re-create the instance on the last loop.
Change-Id: Icbe601a2c95bc86cb731b8392688418e337fcab0
=> vkreplay: -s recreates instance on last loop

layer_factory/CMakeLists.txt
Change-Id: I7766e81a6af124f0850ee952132d628a30395908
=> vlf: Install layer_factory libraries

vktrace/vktrace_replay/vkreplay_vkreplay.cpp
fixed crash when playing large files
=> vkreplay: fixed conversion from uint64_t -> long -> uint64_t

.appveyor.yml, .travis.yml
Work in progress to test travis and appveyor builds using known good commits.
=> Use known good for CI builds

scripts/vktrace_file_generator.py, vktrace/vktrace_replay/vkreplay_vkreplay.cpp
This change skips VK_EXT_debug_report related calls when the extension
is not enabled in the trace file being replayed or the extension is not
supported.
=> vkreplay: Skip debug report calls when not enabled

scripts/known_good.json
Also fixes problem building loader with older Cmake
=> Update known-good for 1.1.90 header

CONTRIBUTING.md, build-android/build_all.sh, build-android/install_all.sh, tests/vktracereplay.py, vktrace/vktrace.md
This is to follow up a PR in Vulkan-Tools that will rename cube and cubepp
=> tests: Handle renaming of cube and cubepp

scripts/known_good.json
Also remove last MIR reference
=> repo: Update known-good for 1.1.91 header

layersvt/device_simulation.md
Requested change to specify LunarG's VulkanTools repo in dev sim doc.
=> docs: update to dev_sim.md to specify LunarG's VulkanTools repo

vktrace/vktrace_replay/vkreplay_vkdisplay_xcb.cpp
Change-Id: I4a15fb2b77c85ad1de3e976157fa2f3dbe9b7af0
=> vkreplay: Unmap xcb window before resizing to full screen

via/CMakeLists-SDK.txt
Allow make install via in the SDK using the build_tools.sh script
=> VKVIA: CMakeLists-SDK, Allow make install for via in the SDK

vkconfig/CMakeLists.txt
Allow for `make install` for vkconfig.
=> build: Allow make install on Unix for vkconfig

scripts/layer_factory_generator.py
Updated:
- `scripts/layer_factory_generator.py`
=> build: Prepare scripts for 1.1.97 header changes

BUILD.md
Add Linux package requirements and build info for VkConfig.
Also, add a note about the warning that is generated if the
dependencies aren't present.
Change-Id: If6cd70df8f098662f03a1096b763bd2eb9308620
=> vkconfig - Add build info

build-android/jni/Android.mk, vktrace/vktrace_layer/CMakeLists.txt, vktrace/vktrace_layer/vktrace_lib_trace.cpp, vktrace/vktrace_layer/vktrace_lib_trim.cpp, vktrace/vktrace_layer/vktrace_lib_trim.h, vktrace/vktrace_layer/vktrace_lib_trim_descriptoriterator.cpp, vktrace/vktrace_layer/vktrace_lib_trim_descriptoriterator.h
The pull request include commits related to trim descriptor set handling and  optimization, these commits fix a number of  trim problems for some titles.
=> Trim descriptorset handling fixes and related optimization

build-android/android-generate.bat
Update android-generate.bat for the latest LVL changes.
=> Fix Android Build for Windows

via/via_system.cpp, via/via_system.hpp, via/via_system_linux.cpp, via/via_system_windows.cpp
If only one driver JSON is bad, but at least one more is available,
keep testing.  Same with layers.
=> via: Better missing driver JSON handling

vktrace/vktrace_replay/vkreplay_vkreplay.cpp
Previously used to keep the starting position for portability table
searches in a static variable. This would break looping, because
after the 1st loop, the starting positon was at the end of the
portablity table, so vkAllocateMemory packets were not being
found in the portability table. Changed the code to always search
from the beginning.
Change-Id: Iebaaeec568f2a3d80a73c3d8fda168b0c76decf2
=> vkreplay: search full portability table

scripts/vktrace_file_generator.py
Changes so that vkGetPhysicalDeviceSurfaceCapabilities2KHR and
vkGetPhysicalDeviceSurfaceFormats2KHR trace/replay correctly.
Changes include correctly processing VkSurfaceFormatKHR array
of structures in vkGetPhysicalDeviceSurfaceFormats2KHR, and properly
remapping surface handles in vkSurfaceKHR args.
These changes allow vulkaninfo to be traced and replayed successfully.
Change-Id: I612536f30c9d99183d138644d822de417396fb2f
=> vktrace: fix vkGetPhysDevSurf(Capabilities/Formats)2KHR

layer_factory/layer_factory_linux.json, layer_factory/layer_factory_windows.json, layersvt/linux/VkLayer_api_dump.json, layersvt/linux/VkLayer_device_simulation.json, layersvt/linux/VkLayer_monitor.json, layersvt/linux/VkLayer_screenshot.json, layersvt/windows/VkLayer_api_dump.json, layersvt/windows/VkLayer_device_simulation.json, layersvt/windows/VkLayer_monitor.json, layersvt/windows/VkLayer_screenshot.json, scripts/known_good.json, vktrace/vktrace_layer/linux/VkLayer_vktrace_layer.json, vktrace/vktrace_layer/windows/VkLayer_vktrace_layer.json
Updated known_good.json.
Updated api version in layer json files.
Change-Id: I0958d761fc60a7469d2a2733e10f8534ae952476
=> repo: changes for 1.1.101 header

layer_factory/layer_factory_linux.json, layer_factory/layer_factory_windows.json, layersvt/linux/VkLayer_api_dump.json, layersvt/linux/VkLayer_device_simulation.json, layersvt/linux/VkLayer_monitor.json, layersvt/linux/VkLayer_screenshot.json, layersvt/windows/VkLayer_api_dump.json, layersvt/windows/VkLayer_device_simulation.json, layersvt/windows/VkLayer_monitor.json, layersvt/windows/VkLayer_screenshot.json, scripts/known_good.json, vktrace/vktrace_layer/linux/VkLayer_vktrace_layer.json, vktrace/vktrace_layer/windows/VkLayer_vktrace_layer.json
Change-Id: I48254237f3e607fc44ce18640c691d57dbff2956
=> repo: bump known_good to 1.1.102

scripts/vktrace_file_generator.py
Reverts LunarG/VulkanTools#759
=> Revert "vkreplay: Some title hang during trim playback"

scripts/api_dump_generator.py
apidump: Use debug_util names if available, update copyright
Changed VulkanFunction by adding funcDispatchType, which is used to seperate functions using
instance_dispatch_chain and the device_dispatch_chain. funcType is now only used in the
vkGetInstaceProcAddr/vkGetDeviceProcAddr trampoline code.
=> Charles gh690 api dump enable debug utils names

vktrace/vktrace_layer/vktrace_lib_trace.cpp, vktrace/vktrace_layer/vktrace_lib_trim.cpp
Change-Id: I74806aecb6b6b43e6d9c6724f80dbc4232e84f04
=> vktrace: address compiler warnings

scripts/vktrace_file_generator.py, vktrace/vktrace_replay/vkreplay.cpp, vktrace/vktrace_replay/vkreplay_vkreplay.cpp, vktrace/vktrace_replay/vkreplay_vkreplay.h
Added a common function to translate handles in pnext structs
during vkreplay.
This pull request is a more general implementation of pull requests #757 and #767.
Change-Id: I197c0b9f91f8a113f98678f460fd93388c6522d0
=> vkreplay: translate handles in pnext structs

CMakeLists.txt, layersvt/CMakeLists.txt, scripts/known_good.json
Added code, provided by Mike Schuchardt, to CMakelist.txt
files to provide build instructions for api_dump on MacOS.
=> api_dump: Add CMake code for api_dump on MacOS

layersvt/api_dump_layer.md
Updated api_dump_layer.md to include MacOS documentation.
=> docs: Update API Dump doc for MacOS

layersvt/screenshot.cpp
If a queue or cmdbuf handle is reused, the attempt to add an
entry to an unordered map using the reused queue or cmdbuf
handle as a key will fail. Added coded to remove the map entry
that is using the reused queue/cmdbuf key before adding the new
entry to the unordered map.
The following sequence caused this error:
vkCreateDevice() returns device D1
vkGetDeviceQueue(D1) returns queue Q1
vkDestroyDevice(D1)
vkCreateDevice() returns device D2
vkGetDeviceQueue(D2) returns queue Q1
vkQueuePresent(Q1)
The second call to vkGetDeviceQueue would not add Q1 to an unordered map
(leaving the previous entry in place), resulting in the vkQueuePresent
attempting to use the dispatch table from destroyed device D1.
An alternative fix would have been to change the behavior of vkDestroyDevice
to delete …
=> screenshot: Delete reused queue and cmdbuf keys from unordered maps

vktrace/vktrace_replay/vkreplay_vkreplay.cpp
Game title under test throws exception in processing
the pNext struct in both vkGetImageMemoryRequirements2 and
vkGetBufferMemoryRequirements2 calls during playback.
Split the calls with their KHR extension calls and remove
process pNext struct for these calls as there is no valid
pointers to be processed for these calls. This fix the
game playback exception issue.
VKTRACE-120
Change-Id: I5590abc4f019621ff79c41cee34e04ff1c972330
=> vkreplay: fix pNext exceptions during playback

layersvt/screenshot.cpp, layersvt/screenshot_layer.md
Change-Id: Idd7c577fc4cfb211c9e58962de4b1c8e91c6d321
=> screenshot: Add env var to specify directory of screenshot files

BUILD.md, update_external_sources.bat
Same change as pull request
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/955
Change-Id: Ia653f165ecce5e2c4cd1a1d145e63c65036a2377
=> docs: Improve instructions for using update_deps.

layer_factory/assistant_layer/extension_type_warning.h, layer_factory/assistant_layer/result_check.h, layer_factory/demo_layer/demo.cpp, layer_factory/demo_layer/demo.h, layer_factory/starter_layer/memory_allocation_stats.h, scripts/layer_factory_generator.py
Resolves point in KhronosGroup/Vulkan-ValidationLayers#24 to "Add warnings for non-success driver return values"
=> Camden gh24 result check

BUILD.md, CMakeLists.txt, layer_factory/CMakeLists.txt, layersvt/CMakeLists.txt, via/CMakeLists-SDK.txt, vkconfig/CMakeLists.txt, vktrace/CMakeLists.txt, vktrace/vktrace_common/CMakeLists.txt, vktrace/vktrace_dump/CMakeLists.txt, vktrace/vktrace_layer/CMakeLists.txt, vktrace/vktrace_replay/CMakeLists.txt, vktrace/vktrace_trace/CMakeLists.txt, vktrace/vktrace_viewer/CMakeLists.txt
Also, cmake_minimum_required() must occur before the project() command,
see https://cmake.org/cmake/help/latest/command/project.html
Change-Id: I76deaab5a629e5a8a851007268da2c298646abb3
=> build: Update cmake_minimum_required(VERSION 3.10.2)

tests/vktracereplay.py
Two types of spurious error (LunarG issues 225 and 222) can appear during
testing, with messages like:
Errors while tracing replay of original trace:
vktrace error: Failed to read trace packet with size of 144.
or:
Screenshot not taken while tracing
These issues typically disappear on re-run.  We've tried to identify
underlying code issues without any success; so now we're formalizing
the re-run into an automatic re-run for several iterations, so we
still catch "real" errors without hanging up on sporadic issues.
Change-Id: If0e80e2ebef714feafef675730cc54dd3fa11a37
=> tests: try to retrace several times

tests/vktracereplay.py
Currently, the script will exit after the first test failures.
It's helpful to continue to run the rest of the tests after a
failure; this can help determine whether a failure is
trace-specific or systemic, and ensures that a tester has a full
set of pass/fail information after a test run.
A switch is provided to restore the original behavior, if this
is desired.
Change-Id: Ie709a1123394d405f558ebd7656cd6f0b41650a1
=> tests: run all trace tests even after failure

scripts/api_dump_generator.py
Change-Id: I6a82abd4b3b969e359affd6db4603d1db2880794
=> Moved pNext Chain header to correct location

vktrace/vktrace_layer/vktrace_lib_trace.cpp
vkAllocateMemory will fail on some driver/hardware if allocationSize
is not a multiple of minImportedHostPointerAlignment, the change fix
the issue by make allocationSize multiple of system page size.
VKTRACE-138
Change-Id: Ib37aa9f75d9e62a424048437d4e0defd476956be
=> vktrace: fix an error for PMB host memory capture

vkconfig/vkconfig.cpp
Modified vkconfig.cpp to include VIA tab on MacOS.
Implements changes mentioned in issue #902
=> vkconfig: Add VIA tab to VkConfig on MacOS

vkconfig/layer_info.json
=> Add the Validation Features enables and disables pertinent to the SDK

vkconfig/vkconfig.cpp
Added argument `--disable_cube_tests` to VIA process run by
VkConfig.
=> vkconfig: Remove Cube Test at VkConfig Startup

vkconfig/macOS/vkconfig.sh
Fixes vkconfig.app bundle crashing on startup on MacOS.
=> vkconfig: Fix gitlab issue 181

vkconfig/layer_info.json
=> Removed duplicate devsim entries from layer_info.json file

vkconfig/vkconfig.cpp
Changes to be committed:
modified:   vkconfig/vkconfig.cpp
Change-Id: I337e4b5d940896dd8bfc582c3ce0974d557e48af
=> vkconfig: Support for high DPI displays

vkconfig/override_settings.cpp
=> vkconfig: update minor version for overide settings

layersvt/device_simulation.cpp, layersvt/screenshot.cpp, scripts/api_dump_generator.py, via/via_system_linux.cpp, via/via_system_macos.cpp, via/via_system_windows.cpp, vktrace/vktrace_layer/vktrace_lib_trace.cpp
Change-Id: I56863d3c74cda35253e8b86dbade05448b537e3a
=> VulkanTools: bump vk version in several files

via/via_system.cpp, via/via_system.hpp, via/via_system_linux.cpp, via/via_system_macos.cpp, via/via_system_windows.cpp
Added argument `--vkconfig_output` to send VIA output to
a JSON file that can be parsed by VkConfig.
=> via: Add output usable by VkConfig

layersvt/screenshot.cpp
android_getenv used to use a single static char array to store the
result of calls to android_getenv. Calling it more than once with
different env vars would result in value returned from one call to
be overwritten with the value returned by a second call. Using a
std::map stores values for different env vars in different
locations.
Change-Id: I049a38a6c51628c30c40e13abae81a42fadeb6eb
=> screenshot: Use a std::map to store return value of android_getenv

CONTRIBUTING.md
Change-Id: I5f250d11baa29527fd05f0dfdcb267559aacafc3
=> Documentation: Corrections to CONTRIBUTING.md

layersvt/monitor.cpp
Allows the monitor layer to work when enabled during gfxrecon-replay.
Change-Id: I1be8216c88ac34c31446f88b7bfdce05db22a7b2
=> Monitor Layer: Dynamically load the xcb library

vkconfig/vkconfig.md
Made some changes at the top of this document to make it more similar to the rest of the SDK documents.
Fixed a few typos.
=> Docs: Align to SDK documentation frameworks

via/README.md
This updates the README. 
Still need to identify where in the code the image is used to update the outputted html from vkvia
=> Docs: Update logo on via artwork

vkconfig/mainwindow.cpp, vkconfig/mainwindow.h
Change-Id: I311d10fa87cedf1940303a393664cb9403a54a03
Addresses this issue:
https://github.com/LunarG/Projects/issues/416
=> vkconfig: Fix for issue 416 with invalid configs

vkconfig/command_line.cpp, vkconfig/command_line.h, vkconfig/configurator.cpp, vkconfig/configurator.h, vkconfig/dlgcreateassociation.cpp, vkconfig/dlgcreateassociation.h, vkconfig/dlgcreateassociation.ui, vkconfig/khronossettingsadvanced.cpp, vkconfig/main.cpp, vkconfig/mainwindow.cpp, vkconfig/mainwindow.h, vkconfig/mainwindow.ui, vkconfig/mutemessagewidget.cpp, vkconfig/settingstreemanager.cpp, vkconfig/settingstreemanager.h, vkconfig/test.cpp, vkconfig/test.h, vkconfig/vkconfig.pro, vkconfig/vku.cpp, vkconfig/vku.h, vkconfig/vuidsearchwidget.cpp, vkconfig/vuidsearchwidget.h
Change-Id: I3a53289f2a1fbfb31b460f269f37b9b7512137e7
Cleans up several merge errors between beta cleanup, and new added functionaliyt.
=> vkconfig: Cleaning up merge errors

vkconfig/CMakeLists.txt, vkconfig/main.cpp
Change-Id: Iec43489e3bba5f8ed513bffb61ac438c60bf5c97
Should be ready to go for Qt 5.5.1 on Linux.
=> vkconfig: Allow Linux build w/Qt5.5.1

vkconfig/configurator.cpp
Change-Id: I6851221ec11d693f126ee8cbaaa69af2aea912db
Fixes bad regression with Linux paths for storage of configuration files.
=> vkconfig: Fixed linux directory regression

vkconfig/CMakeLists.txt, vkconfig/appsingleton.cpp, vkconfig/appsingleton.h, vkconfig/main.cpp, vkconfig/vkconfig.pro
Added new utility class so that only one instance of vkconfig can be run at a time.
=> Richard vkconfig single instance

vkconfig/configurator.cpp
Change-Id: Ibc50734c4e62fafa5d8f2618f8218381e50aea94
=> vkconfig: --validate prevent emitting log

vkconfig/vkconfig.md
Change-Id: I1fab170742e7754c13d9c2154f6a1aff2cc8bb2d
=> doc: Improve layout for vkconfig doc

vkconfig/vkconfig.md
Change-Id: I8a3c2e775e09ce682325317efef8848c5fe80eca
=> vkconfig: doc update

vkconfig/vkconfig.md
Change-Id: I0a450253d98447230e511857b1269a5df579f9f8
Removed email from documentation.
=> vkconfig: Removed email address from doc

vkconfig/configurator.cpp, vkconfig/configurator.h
Change-Id: Id8871a17049a931e4256dd73d9092ac5d653d949
A Windows specific registry key name error. QSettings did not like "ReInitializeFiles" as a key value.
=> vkconfig: Fixed initialization error

vkconfig/configurator.cpp, vkconfig/dlgcreateassociation.cpp, vkconfig/dlgcustompaths.cpp, vkconfig/mainwindow.cpp, vkconfig/mainwindow.ui
Fixes for Linux issues that arose during SDK testing.
=> Vkconfig adhock fixes

vkconfig/configurator.cpp, vkconfig/mainwindow.cpp, vkconfig/vkconfig.md
Change-Id: Ia3717860d95ac563d1f11b4ae3b438dec287f810
Addendum to .md file about known issue with screenshot layer.
Completed making API dump the default layer configuration.
=> vkconfig2: API dump and doc updates

vkconfig/configurator.cpp, vkconfig/configurator.h, vkconfig/dlgcustompaths.cpp, vkconfig/dlgprofileeditor.cpp, vkconfig/mainwindow.cpp, vkconfig/mainwindow.h
Change-Id: I4bb744ba9e7e84fdff0f6c0cf577fd28f117e728
Corrected display of layers in custom layer paths.
Addresses LunarG/Vulkan tools issue #1082 
Addresses LunarG/Projects issues #471, #449, #467, #468
=> vkconfig: Fixed several post SDK issues

vkconfig/mainwindow.cpp, vkconfig/mainwindow.h, vkconfig_core/path_manager.cpp, vkconfig_core/path_manager.h
Change-Id: Ic6eeaf1d13669e845333c191f83bb6a83541ef91
=> vkconfig: Fix log not written #1108

vkconfig/mainwindow.cpp, vkconfig/settingstreemanager.cpp, vkconfig/settingstreemanager.h, vkconfig_core/layer_setting.cpp, vkconfig_core/version.h
Richard works on richard_vkconfig_multiselect but without the large file in the commit history.
=> vkconfig: multiple debug actions simultaneously

vkconfig/CHANGELOG.md
Change-Id: I762346cec9418e3009cead575bff165ece64efc7
=> vkconfig: update changelog

scripts/api_dump_generator.py
Previous pNext chain printing put everything in a tree structure that is hard
to read. This makes the text output linear after the struct, making it easy
to understand.
Change-Id: I7d442d13fa9677bea42463f2bf6049948a2b7375
=> apidump: Make text pNext chain printing more legible

vkconfig/configurator.cpp
=> vkconfig: Indicate the version for which gfxrecon requires a different prefix

vkconfig/dlgprofileeditor.cpp, vkconfig_core/configuration.cpp, vkconfig_core/configuration.h
Change-Id: Idd71c2cf622ea24e835609374404827530024ba5
=> vkconfig: Fix custon path #1122

vkconfig/dlgprofileeditor.cpp
Change-Id: I2b6589d3107de9ef034b7564f0b65fdae63ac373
=> vkconfig: Better express the behavior of implicit layers #1124

vkconfig_core/environment.cpp
Change-Id: I7c142d357282043018fbe932f1963c62f312abeb
=> vkconfig: Fix asserts on environment that ran old dev versions

vkconfig/configurator.cpp, vkconfig/khronossettingsadvanced.cpp, vkconfig/mainwindow.cpp, vkconfig/settingstreemanager.cpp, vkconfig/settingstreemanager.h, vkconfig_core/configuration.cpp, vkconfig_core/platform.h
Change-Id: I1438c51e7606013ce2ef9afb27f0e1d566893d11
=> vkconfig: Mode to discard shader based configurations and presets #1130

vkconfig_core/path_manager.cpp
This PR fix issue #1138 
Change-Id: I578370ff353ed83dda9083187efbad6c529b42ea
=> vkconfig: Fix assert because only Windows has executable suffix #1138

vkconfig_core/environment.cpp
Change-Id: If61731d253926595bee6f5c54ef804520607e69a
=> vkconfig: Fix assert when the applist.json file was deleted #1136

vkconfig_core/environment.cpp
The exit message box would always appear even if we checked that we don't want to show it again.
Change-Id: I180b29e479cf8a79a0415700477843abd682e4c3
=> vkconfig: Fix exit notification not being saved

vkconfig/dlgcreateassociation.cpp, vkconfig_core/path_manager.cpp
Change-Id: Icf94251b3c61063d5a8d5523834b254d5d2f44e2
=> vkconfig: Fix for some macOS regressions

vkconfig/dlgcreateassociation.cpp
After this PR:
Before this PR:
Change-Id: Ibca1cf2afb1cb9b55dfcfc73d033f3005a1686ec
=> vkconfig: Fix application list always disabled #1153

vkconfig/configurator.cpp, vkconfig/configurator.h, vkconfig/dlgprofileeditor.cpp, vkconfig/dlgprofileeditor.h
Change-Id: I65dab03f61543e6dae73a6c26ed238db856ced3f
=> vkconfig: Fix layers window reset button #1162

vkconfig/configurator.cpp, vkconfig/dlgprofileeditor.cpp, vkconfig/dlgprofileeditor.h, vkconfig/mainwindow.cpp
Each time we accessed the layer window the setting would be reset...
Change-Id: I1261344d37ac256c507efff4f399a7524807311e
=> vkconfig: Don't reset systematically settings

vkconfig/widget_bool_setting.cpp
Change-Id: I3b9da79d78ecb5d9efc929b2fe29dd695c50adc6
=> vkconfig: Fix the display of numeric bool #1166

vkconfig_core/environment.cpp
Change-Id: Ic50a542f431cc4810234d60ee39e974034a99c21
=> vkconfig: Search vkcube at the package install path #1088

vkconfig/vulkan.cpp
Reenabled Vulkan status, crash is not happening anymore... strange...
Change-Id: Icb1d064331beed893256d749bf2f5f52558984af
=> vkconfig: Reenabled Vulkan status

scripts/known_good.json
Change-Id: I7088bc819e2f210ac5dd40812f21667069239f88
=> build: Changes for 1.2.154 header

vkconfig/configurator.cpp, vkconfig/resourcefiles/Frame Capture - Range (F5 to start and to stop).json, vkconfig/resources.qrc, vkconfig_core/test/Configuration 2.0.2 - Frame Capture.json, vkconfig_core/test/test_configuration.cpp
Change-Id: I4f432576b78b255a071eb80d4e7a262d71408a23
=> vkconfig: Fix Capture Frame Range configuration #1184 #1185

vkconfig/configurator.cpp
Change-Id: I8ef296e463005253f0f4ec9675cd8679bdbdcc0c
=> vkconfig: Fix crash when no configuration is actived

vkconfig/dlgprofileeditor.cpp
Change-Id: I37d94dffc779c3b4505d82d5ac2e161525bb2fe8
=> vkconfig: Fix ParameterRank

vkconfig/mainwindow.cpp, vkconfig/mainwindow.h
Change-Id: I31a282a224b9c8bc11a14ae39e7c4180073466cc
=> vkconfig: Fix terminate of hang launched application

vkconfig/configurator.cpp
Change-Id: I111945e21eb930181a11c8132d6ec72b799aa813
=> vkconfig: Make sure there isn't no configuration #1221

vkconfig/CHANGELOG.md, vkconfig/configurator.cpp, vkconfig/dialog_layers.cpp, vkconfig_core/configuration.cpp, vkconfig_core/parameter.cpp
Change-Id: I43fa724469a820bbf742a83f037647d5ae410103
=> vkconfig: Fix manual ordering of layers #1214

vkconfig/CHANGELOG.md, vkconfig/configurator.cpp, vkconfig/configurator.h, vkconfig/mainwindow.cpp, vkconfig/mainwindow.h
Change-Id: I04648dadd1330fe89d75a43326280645b2d14764
=> vkconfig: Fix warning about old loader when trying to use application list 

vkconfig/settingstreemanager.cpp, vkconfig_core/environment.cpp, vkconfig_core/environment.h
Change-Id: Idd5eb263352d94cb1815236f85234bdfb074dcae
=> vkconfig: fix warning

via/via_system_linux.cpp
This newline was creating non-valid json files.
=> via: remove newline from dpkg-query for system packages

vkconfig_core/test/test_version.cpp, vkconfig_core/version.cpp, vkconfig_core/version.h
Change-Id: Ifcdae5b5a8e77f7ba5d1cc311423267b83bf8f40
=> vkconfig: Make Version class easier to debug

.appveyor.yml
Change-Id: I9c51becb4fa48d38dec56050ce89e8f1283495d6
=> C.I.: Multithreaded NMake build

.appveyor.yml
Change-Id: I92cefde5d1d9910b103d591067bed4071c4bab0d
=> C.I.: Multiple threads cmake build in appveyor

vkconfig/dialog_applications.cpp, vkconfig/khronossettingsadvanced.cpp, vkconfig/vkconfig.pro, vkconfig/widget_filesystem_setting.cpp, vkconfig/widget_vuid_search.cpp, vkconfig_core/layer_setting.h, vkconfig_core/parameter.cpp, vkconfig_core/setting_type.cpp, vkconfig_core/setting_type.h, vkconfig_core/setting_value.cpp, vkconfig_core/setting_value.h, vkconfig_core/test/CMakeLists.txt, vkconfig_core/test/test_setting_type.cpp, vkconfig_core/test/test_setting_value.cpp
Foundation work for data driven settings
Change-Id: I2e89a0d1f7deba3f6aa8fe4e4ce348827fdd6229
=> vkconfig: Add setting value and setting type with unit tests

BUILD.md
Change-Id: Iac1a0e269057749a3f0ea582c54b6514364ad43a
=> vkconfig: Fix broken link, use python3 to build

vkconfig/main_layers.cpp
Change-Id: I5e723bb5fc0962a2de22e84f9304212cffa652e3
=> vkconfig: No application list support in cmd

layersvt/monitor.cpp
Previously, vkGetInstanceProcAddr was called with a null instance. This is illegal, so it now fetches the actual instance.
=> Correct monitor layer device creation

vkconfig/CHANGELOG.md
Change-Id: I776592fdb615bd032426ffbbd8efdaf0ce7f0268
=> vkconfig: Prepare CHANGELOG for 2020 december release

vkconfig/settingstreemanager.cpp
Change-Id: I52c26c608056b804910dc73bc7542833b38af456
=> vkconfig: Fix Clang format with Travis CI

vkconfig/vulkan.cpp
Change-Id: Ifb79e672ca9cbfca8691458b0a18835c34814faa
=> vkconfig: Fix status not reporting SDK path

vkconfig_core/path.cpp
Change-Id: Ie219fad95449e13b0abb89985d3004647f320d56
=> vkconfig: Make sure  is not given a full path

vkconfig/CHANGELOG.md, vkconfig/README.md
Change-Id: I6ce7af69bdc1cbea825c1095d6f38475e6e2cdd7
=> vkconfig: Update doc for Dec SDK release

vkconfig_core/layer.h, vkconfig_core/layer_state.cpp, vkconfig_core/platform.cpp, vkconfig_core/util.h
=> vkconfig: fix clang build

vkconfig/mainwindow.h, vkconfig/mainwindow.ui, vkconfig/resourcefiles/layers_1_2_154/VK_LAYER_KHRONOS_validation.json, vkconfig/settings_tree.cpp, vkconfig/settings_tree.h, vkconfig/settings_validation_areas.cpp, vkconfig/settings_validation_areas.h, vkconfig/vkconfig.pro, vkconfig/widget_preset.cpp, vkconfig/widget_preset.h
=> vkconfig: generic preset, any layer may have presets

layersvt/api_dump_layer.md
update doc to add note about enabling layer with vkconfig
=> apidump: update doc to add note about enabling layer with vkconfig

vkconfig_core/test/Configuration 2.0.3 - Best Practices.json, vkconfig_core/test/resources.qrc, vkconfig_core/test/test_configuration.cpp
Change-Id: I996b89cd2848821c57314837cc5179af19a3524e
=> vkconfig: Test configuration json format 2.0.3 compat

layersvt/device_simulation_examples/iOS_gpu_family_3_portability.json, layersvt/device_simulation_examples/iOS_gpu_family_5_portability.json, layersvt/device_simulation_examples/macOS_gpu_family_1_portability.json
Added files for devsim to simulate portability configurations from
different MoltenVK devices.
=> devsim: Add portability devsim config files

vkconfig/configurator.cpp, vkconfig/configurator.h, vkconfig/mainwindow.cpp
Change-Id: I8b06a485ee9f203abb256d1c8524ae90bd5c10f8
=> vkconfig: fix configuration export not up to date

vkconfig/settings_tree.cpp, vkconfig/settings_tree.h, vkconfig/settings_validation_areas.cpp, vkconfig/settings_validation_areas.h, vkconfig_core/layer.cpp
Change-Id: I538732c0ac398842e7de414d4ed0aaa44da2adbc
=> vkconfig: Clean up

vkconfig/resourcefiles/configurations/Portability.json, vkconfig/resourcefiles/layers_1_2_154/VK_LAYER_LUNARG_api_dump.json, vkconfig/resourcefiles/layers_1_2_154/VK_LAYER_LUNARG_gfxreconstruct.json, vkconfig_core/test/Configuration 2.1.0 - Frame Capture.json, vkconfig_core/test/Configuration 2.1.0 - Portability.json, vkconfig_core/test/resources.qrc, vkconfig_core/test/test_configuration.cpp
Change-Id: I78fef090615c6a89096289234dc834baf0a62582
=> vkconfig: Fix settings and add 2.1.0 tests

vkconfig/dialog_layers.ui
Change-Id: I9dc4f030fe1324ea5f9226130d3469662a99e01f
=> vkconfig: Improve description layout

vkconfig/CHANGELOG.md, vkconfig/configurator.cpp, vkconfig/resourcefiles/configurations/Portability.json, vkconfig_core/path.cpp
Change-Id: Icdb9dd93b37ec4c7f7229ba4cd5593167cc3ef85
=> vkconfig: Add devsim default configuration on macOS #1299

vkconfig/resourcefiles/layers_162/VK_LAYER_LUNARG_device_simulation.json, vkconfig/settings_tree.cpp, vkconfig_core/layer.cpp, vkconfig_core/layer_setting_meta.h
Change-Id: I1e40c987ac851ded03dbee7493bef15759100d55
=> vkconfig: Add per platform settings

vkconfig/resourcefiles/layers_latest/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layer.cpp, vkconfig_core/test/Layer 1.3.0.json, vkconfig_core/test/Layer 1.4.0 - presets.json, vkconfig_core/test/Layer 1.4.0 - setting platforms.json, vkconfig_core/test/Layer 1.4.0 - setting types.json, vkconfig_core/test/resources.qrc, vkconfig_core/test/test_layer.cpp
Change-Id: I2d502c77581ba1435e6a503a0e6742273f6876a4
=> vkconfig: Add JSON layer loader tests

vkconfig_core/path.cpp, vkconfig_core/platform.cpp
Change-Id: Ia509033ea5be74aded3a42f979c194e41f2a1bad
=> vkconfig: Fix devsim path

vkconfig/resourcefiles/configurations/Portability.json
To merge depending on @richard-lunarg results with devsim on macOS port
=> [2021 Jan SDK] vkconfig: Add 'Portability' default configuration for macOS

layersvt/CMakeLists.txt
Change-Id: Ifb86d613e548bdce080124ab6886b03c3751c4ac
Build device simulation layer on macOS.
=> devsim: Add build for macOS

vkconfig/resourcefiles/configurations/Portability.json, vkconfig/resourcefiles/layers_162/VK_LAYER_LUNARG_device_simulation.json, vkconfig_core/configuration.cpp, vkconfig_core/platform.cpp
Change-Id: I2682132609b417a3855c159b79137531a8bf73ae
=> vkconfig: Ignore layers unsupported by platforms in layers configuration

vkconfig/mainwindow.cpp, vkconfig/resourcefiles/configurations/API dump.json, vkconfig/resourcefiles/configurations/Frame Capture.json, vkconfig/resourcefiles/configurations/Portability.json, vkconfig/resourcefiles/configurations/Synchronization.json, vkconfig/resourcefiles/configurations/Validation.json, vkconfig/settings_tree.cpp, vkconfig/widget_bool_setting.cpp, vkconfig/widget_bool_setting.h, vkconfig_core/configuration.cpp, vkconfig_core/configuration.h, vkconfig_core/configuration_manager.cpp, vkconfig_core/layer.cpp, vkconfig_core/layer_setting_data.cpp, vkconfig_core/layer_setting_data.h, vkconfig_core/layer_setting_type.cpp, vkconfig_core/layer_setting_type.h, vkconfig_core/layer_setting_value.cpp, vkconfig_core/test/Configuration 2.0.2 - Override all layers.json, vkconfig_core/test/Configuration 2.1.0 - Override all layers.json, vkconfig_core/test/Configuration 2.2.0 - Override all layers.json, vkconfig_core/test/Layer 1.4.0 - setting types.json, vkconfig_core/test/resources.qrc, vkconfig_core/test/test_configuration.cpp, vkconfig_core/test/test_layer.cpp, vkconfig_core/test/test_layer_preset.cpp, vkconfig_core/test/test_layer_setting_type.cpp, vkconfig_core/version.h
Change-Id: Ic293cda99719905cb5552bdd8110c3fc0a46f138
=> vkconfig: read and write typed bool and int settings

vkconfig/CHANGELOG.md, vkconfig/resourcefiles/layers_130/VK_LAYER_LUNARG_api_dump.json, vkconfig/resourcefiles/layers_130/VK_LAYER_LUNARG_device_simulation.json, vkconfig/resourcefiles/layers_135/VK_LAYER_LUNARG_device_simulation.json, vkconfig/resourcefiles/layers_141/VK_LAYER_LUNARG_device_simulation.json, vkconfig/resourcefiles/layers_141/VK_LAYER_LUNARG_gfxreconstruct.json, vkconfig/resourcefiles/layers_148/VK_LAYER_LUNARG_api_dump.json, vkconfig/resourcefiles/layers_148/VK_LAYER_LUNARG_device_simulation.json, vkconfig/resourcefiles/layers_148/VK_LAYER_LUNARG_gfxreconstruct.json, vkconfig/resourcefiles/layers_154/VK_LAYER_LUNARG_api_dump.json, vkconfig/resourcefiles/layers_154/VK_LAYER_LUNARG_device_simulation.json, vkconfig/resourcefiles/layers_154/VK_LAYER_LUNARG_gfxreconstruct.json, vkconfig/resourcefiles/layers_162/VK_LAYER_LUNARG_api_dump.json, vkconfig/resourcefiles/layers_162/VK_LAYER_LUNARG_device_simulation.json, vkconfig/resourcefiles/layers_162/VK_LAYER_LUNARG_gfxreconstruct.json, vkconfig/resourcefiles/layers_latest/VK_LAYER_LUNARG_api_dump.json, vkconfig/resourcefiles/layers_latest/VK_LAYER_LUNARG_device_simulation.json, vkconfig/resourcefiles/layers_latest/VK_LAYER_LUNARG_gfxreconstruct.json, vkconfig/widget_filesystem_setting.cpp, vkconfig_core/layer.cpp
Change-Id: I526a48d4eba9d72548c7f69e6124bcf96e654112
=> vkconfig: Add extension filters to load and save file layer settings #1317

vkconfig/settings_tree.cpp, vkconfig/settings_validation_areas.cpp, vkconfig/settings_validation_areas.h
Change-Id: I4b9c1750747b6bb20229f122f536e684dc44804f
=> vkconfig: Expose shader-based individual settings on macOS

scripts/common_codegen.py
New platform added to the platform dictionary.
=> codegen: add new qnx screen platform from vk.xml

.github/workflows/ci_build.yml
Change-Id: I4d25eaf551452a11e1a1fb6c40160ba8de87d581
=> vkconfig: Enable Github actions build and unit tests run

vkconfig/CHANGELOG.md, vkconfig_core/layers/162/VK_LAYER_LUNARG_device_simulation.json, vkconfig_core/layers/latest/VK_LAYER_LUNARG_device_simulation.json
Change-Id: Ib0f126eb2e762f6adf81110d8b3d3632cd14497a
=> vkconfig: Expose 'modify_extension_list' setting from devsim

vkconfig/vulkan.cpp
Change-Id: I0322d39f4630e2c3de89d4c30de1eb16871fc000
=> vkconfig: fix typos

layersvt/device_simulation.md, vkconfig/CHANGELOG.md, vkconfig_core/layers/latest/VK_LAYER_LUNARG_device_simulation.json, vkconfig_core/test/test_layer_built_in.cpp
I also changed the devsim doc so that boolean get used from settings
=> devsim: expose modify_memory_flags in vkconfig

vkconfig_core/layers/latest/VK_LAYER_LUNARG_device_simulation.json
Change-Id: Id26895ff961299231dfd9ec7d1c57ff3f98a14d8
=> vkconfig: Fix devsim setting label

vkconfig/CHANGELOG.md, vkconfig/mainwindow.cpp, vkconfig/vulkan.cpp, vkconfig_core/configuration_manager.cpp, vkconfig_core/configuration_manager.h
Change-Id: I00b10b8c6949c5233a069d95de9e47d6c7ed3694
=> Refresh 'Vulkan Development Status' when the configuration changed #1366

.github/workflows/ci_build.yml
Change-Id: Id8f954a7247159e1e7f379d4f095630b55351ba5
=> C.I.: Fix build fail due to Ubuntu upgrade to 20.04

vkconfig/vulkan.cpp
Change-Id: I44c7a3a9407dac95bd9349c249f7cac2c8395040
=> vkconfig: Use 'environment variable' instead of &

vkconfig/CHANGELOG.md, vkconfig/resources.qrc, vkconfig_core/CMakeLists.txt, vkconfig_core/layer.cpp, vkconfig_core/layers/162/VK_LAYER_LUNARG_api_dump.json, vkconfig_core/layers/170/VK_LAYER_KHRONOS_synchronization2.json, vkconfig_core/layers/170/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layers/170/VK_LAYER_LUNARG_api_dump.json, vkconfig_core/layers/170/VK_LAYER_LUNARG_device_simulation.json, vkconfig_core/layers/170/VK_LAYER_LUNARG_gfxreconstruct.json, vkconfig_core/layers/170/VK_LAYER_LUNARG_monitor.json, vkconfig_core/layers/170/VK_LAYER_LUNARG_screenshot.json, vkconfig_core/version.cpp, vkconfig_core/version.h
Change-Id: I988f8064bb6318d3a2386e444a968314b2888984
=> vkconfig: First commit for April SDK release

vkconfig/settings_tree.cpp
=> vkconfig: bold font for layers in setting tree

vkconfig/settings_validation_areas.cpp, vkconfig/settings_validation_areas.h, vkconfig_core/layers/latest/VK_LAYER_KHRONOS_validation.json
We can edit labels and description in Vulkan Configurator using the layer JSON settings of the validation layer.
=> vkconfig: more data driven validation layer

vkconfig/CHANGELOG.md, vkconfig/mainwindow.cpp, vkconfig/mainwindow.h, vkconfig/mainwindow.ui, vkconfig/settings_tree.h, vkconfig/vulkan.cpp, vkconfig_core/environment.cpp, vkconfig_core/environment.h
=> Add Vulkan loader debug message to application launcher #1372

vkconfig/mainwindow.ui
Change-Id: Ieeaa555f38ee4dfc5253bcb1ff34acdf2431df9f
=> vkconfig: Fix loader debug message UI tooltip

vkconfig/dialog_custom_paths.cpp, vkconfig/resources.qrc, vkconfig/settings_tree.cpp, vkconfig/settings_validation_areas.cpp, vkconfig/widget_setting_float.cpp, vkconfig/widget_setting_float.h, vkconfig/widget_setting_frames.cpp, vkconfig/widget_setting_frames.h, vkconfig/widget_setting_int.cpp, vkconfig/widget_setting_int.h, vkconfig_core/layers/layers_schema.json, vkconfig_core/override.cpp, vkconfig_core/setting_meta.h, vkconfig_core/test/resources.qrc, vkconfig_core/test/test_layer_built_in.cpp, vkconfig_core/test/test_parameter.cpp, vkconfig_core/util.cpp
Change-Id: I37052c54b736520c4b55a7281fac6a902bd2f6c5
=> vkconfig: Improve float, int, frames setting types UI

vkconfig/settings_tree.cpp, vkconfig/widget_preset.cpp, vkconfig/widget_setting_enum.cpp, vkconfig/widget_setting_enum.h, vkconfig_core/test/Configuration 2.2.0.json, vkconfig_core/test/Configuration 2.2.1.json, vkconfig_core/test/VK_LAYER_LUNARG_reference_1_4_0.json, vkconfig_core/test/override_settings_2_2_0_schema_1_4_0.txt, vkconfig_core/test/override_settings_2_2_1_schema_1_4_0.txt, vkconfig_core/test/test_layer.cpp
This PR fix the usage of json schema view with enum setting type
=> vkconfig: fix enum setting with hidden values

vkconfig_core/layers/layers_schema.json
Change-Id: Id9bc6710c256546358ff3f1fdce46321468e453c
=> vkconfig: fix list values checking

vkconfig/CHANGELOG.md, vkconfig_core/override.cpp, vkconfig_core/test/override_layers_2_2_0_schema_1_4_0.json, vkconfig_core/test/override_layers_2_2_1_schema_1_4_0.json
Change-Id: Ida891b7cd0fea4e0697900d3741b19ee52345e1c
=> vkconfig: Fix crash when SDK path is included in 'VkLayer_override.json'

layersvt/device_simulation.cpp
Application may create several Vulkan instances and call `vkEnumeratePhysicalDevices` for each of them.
Thus, instead of populating physical device map only once, we should check whether we already seen the device very time.
Such case could be observed while replaying D3D11 RenderDoc trace via Wine + DXVK.
Fixes #1422
=> devsim: allow multiple enumerations of phys devices

vkconfig/settings_tree.cpp, vkconfig/settings_validation_areas.cpp, vkconfig/widget_setting_enum.cpp, vkconfig/widget_setting_enum.h, vkconfig/widget_setting_filesystem.cpp, vkconfig/widget_setting_filesystem.h, vkconfig/widget_setting_flags.cpp, vkconfig/widget_setting_flags.h, vkconfig/widget_setting_float.cpp, vkconfig/widget_setting_float.h, vkconfig/widget_setting_frames.cpp, vkconfig/widget_setting_frames.h, vkconfig/widget_setting_int.cpp, vkconfig/widget_setting_int.h, vkconfig/widget_setting_list.cpp, vkconfig/widget_setting_list.h, vkconfig/widget_setting_list_element.cpp, vkconfig/widget_setting_list_element.h, vkconfig/widget_setting_string.cpp, vkconfig/widget_setting_string.h, vkconfig_core/test/VK_LAYER_LUNARG_reference_1_4_0.json, vkconfig_core/test/override_settings_2_2_0_schema_1_4_0.txt, vkconfig_core/test/override_settings_2_2_1_schema_1_4_0.txt
Change-Id: I0faed785b5ada46c879d9000c552eaa672276a26
=> vkconfig: data-driven depedencies UI for all settings

vkconfig/dialog_custom_paths.cpp, vkconfig/dialog_layers.cpp, vkconfig/main_layers.cpp, vkconfig/settings_tree.cpp, vkconfig_core/configuration.cpp, vkconfig_core/layer.cpp, vkconfig_core/layer.h, vkconfig_core/layers/130/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layers/135/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layers/141/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layers/148/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layers/154/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layers/162/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layers/170/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layers/latest/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layers/layers_schema.json, vkconfig_core/override.cpp, vkconfig_core/parameter.cpp, vkconfig_core/setting_meta.cpp, vkconfig_core/setting_meta.h, vkconfig_core/test/test_configuration_manager.cpp, vkconfig_core/test/test_layer.cpp
Example: this setting dependence is now implemented using data-driven layer settings
=> vkconfig: add flag dependences

vkconfig_core/layers/130/VK_LAYER_LUNARG_api_dump.json, vkconfig_core/layers/135/VK_LAYER_LUNARG_api_dump.json, vkconfig_core/layers/141/VK_LAYER_LUNARG_api_dump.json, vkconfig_core/layers/148/VK_LAYER_LUNARG_api_dump.json, vkconfig_core/layers/154/VK_LAYER_LUNARG_api_dump.json, vkconfig_core/layers/162/VK_LAYER_LUNARG_api_dump.json, vkconfig_core/layers/170/VK_LAYER_LUNARG_api_dump.json, vkconfig_core/layers/latest/VK_LAYER_LUNARG_api_dump.json
Change-Id: I3bcff00821c04ba5d79a0b7aa924b19b55e55e14
=> vkconfig: refactor API dump settings dependences

layersvt/VkLayer_screenshot.json.in
Change-Id: Ie16a95f9ecbe6a913cc994596dddbe9aafa90105
=> Screenshot: add settings to layer manifest

vkconfig_core/configurations/2.2.0/Validation.json, vkconfig_core/configurations/2.2.1/Validation.json, vkconfig_core/layers/162/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layers/170/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layers/latest/VK_LAYER_KHRONOS_validation.json
Change-Id: I4bb1d9ba915deea953de75b8b81ad07639668a57
=> vkconfig: fix default buffer oob

vkconfig_core/layer.cpp
Change-Id: I220dde9d95a51bc2ba474221d33fa47577ec72d4
=> vkconfig: add loading of VUIDs from VULKAN_SDK path

vkconfig/settings_tree.cpp, vkconfig/settings_tree.h, vkconfig/settings_validation_areas.cpp, vkconfig/settings_validation_areas.h, vkconfig/widget_setting_bool.cpp, vkconfig/widget_setting_bool.h, vkconfig/widget_setting_enum.cpp, vkconfig/widget_setting_enum.h, vkconfig/widget_setting_filesystem.cpp, vkconfig/widget_setting_filesystem.h, vkconfig/widget_setting_flags.cpp, vkconfig/widget_setting_flags.h, vkconfig/widget_setting_float.cpp, vkconfig/widget_setting_float.h, vkconfig/widget_setting_frames.cpp, vkconfig/widget_setting_frames.h, vkconfig/widget_setting_int.cpp, vkconfig/widget_setting_int.h, vkconfig/widget_setting_list.cpp, vkconfig/widget_setting_list.h, vkconfig/widget_setting_list_element.cpp, vkconfig/widget_setting_list_element.h, vkconfig/widget_setting_string.cpp, vkconfig/widget_setting_string.h, vkconfig_core/setting_meta.cpp
- Refresh dependence was causing setting field to lose focus
- Validation settings was broken
=> vkconfig: refactor validation panel

layersvt/VkLayer_api_dump.json.in, vkconfig/CHANGELOG.md, vkconfig/dialog_layers.cpp, vkconfig/dialog_layers.h, vkconfig_core/configurations/2.2.1/API dump.json, vkconfig_core/layer.cpp, vkconfig_core/layers/130/VK_LAYER_LUNARG_api_dump.json, vkconfig_core/layers/135/VK_LAYER_LUNARG_api_dump.json, vkconfig_core/layers/141/VK_LAYER_LUNARG_api_dump.json, vkconfig_core/layers/148/VK_LAYER_LUNARG_api_dump.json, vkconfig_core/layers/154/VK_LAYER_LUNARG_api_dump.json, vkconfig_core/layers/162/VK_LAYER_LUNARG_api_dump.json, vkconfig_core/layers/170/VK_LAYER_LUNARG_api_dump.json, vkconfig_core/layers/latest/VK_LAYER_LUNARG_api_dump.json, vkconfig_core/test/test_layer_built_in.cpp
- Fix inconsistent API dump configuration
- Fix crash when collecting settings
=> vkconfig: fixes for sdk 176

vkconfig/CHANGELOG.md, vkconfig/dialog_custom_paths.cpp, vkconfig/settings_validation_areas.cpp, vkconfig_core/layer.cpp
Change-Id: I928c44471c10f2e99544d096a28b906853cd0d74
=> vkconfig: fix search built-in settings version

vkconfig/CHANGELOG.md, vkconfig/mainwindow.cpp, vkconfig/settings_tree.cpp, vkconfig/settings_tree.h, vkconfig/settings_validation_areas.cpp, vkconfig/settings_validation_areas.h, vkconfig/widget_preset.cpp, vkconfig/widget_preset.h, vkconfig/widget_setting.cpp, vkconfig/widget_setting.h, vkconfig/widget_setting_bool.cpp, vkconfig/widget_setting_bool.h, vkconfig/widget_setting_enum.cpp, vkconfig/widget_setting_enum.h, vkconfig/widget_setting_filesystem.cpp, vkconfig/widget_setting_filesystem.h, vkconfig/widget_setting_flags.cpp, vkconfig/widget_setting_flags.h, vkconfig/widget_setting_float.cpp, vkconfig/widget_setting_float.h, vkconfig/widget_setting_frames.cpp, vkconfig/widget_setting_frames.h, vkconfig/widget_setting_int.cpp, vkconfig/widget_setting_int.h, vkconfig/widget_setting_list.cpp, vkconfig/widget_setting_list.h, vkconfig/widget_setting_list_element.cpp, vkconfig/widget_setting_list_element.h, vkconfig/widget_setting_string.cpp, vkconfig/widget_setting_string.h
Change-Id: I9c82ef9bd5fcec4db0541452ec2a6ea090ea132c
=> vkconfig: redesign setting UI dependences

layersvt/vk_layer_settings.txt, vkconfig/CHANGELOG.md, vkconfig/mainwindow.cpp, vkconfig/settings_validation_areas.cpp, vkconfig_core/configurations/2.2.1/Synchronization.json, vkconfig_core/environment.cpp, vkconfig_core/environment.h, vkconfig_core/layer_manager.cpp
Change-Id: Iecac879326ecb34dfc73823949d7faa227bb9d51
=> vkconfig: SDK 1.2.176 bug fixing

vkconfig/CHANGELOG.md, vkconfig/settings_validation_areas.cpp, vkconfig/settings_validation_areas.h, vkconfig_core/environment.cpp
=> vkconfig: Improve 'High Validation Layer Overhead' warning UI

cmake/FindVulkanHeaders.cmake
Changes needed to adapt to 1.2.176 headers
=> Fix version to adapt to 1.2.176 headers

vkconfig/widget_setting_list.cpp, vkconfig/widget_setting_list_element.cpp, vkconfig_core/layer.cpp
Change-Id: Icee25acead40607aa1d356b3795607d5f74bd1e5
=> vkconfig: fix list UI

vkconfig/mainwindow.cpp, vkconfig/mainwindow.h, vkconfig/mainwindow.ui, vkconfig_core/help.cpp
Change-Id: I1e5310f3e2235b5c3fe7d5b6d24fcb9a8a65a223
=> vkconfig: fix urls

vkconfig/README.md
Change-Id: Ib0824a90a8a91b7566ade96f6146ba014e853354
=> vkconfig: fix windows location for override files

vkconfig_core/CMakeLists.txt
Change-Id: Ia5fdec5f454ed64645740fa5fcdcc94744cd4e35
=> vkconfig: less invasive cmake def

layersvt/VkLayer_device_simulation.json.in, layersvt/device_simulation.cpp, layersvt/device_simulation.md
Added additional methods to create devsim's simulated list of
VkExtensionProperties.
=> devsim: Add extension simulation modes

layersvt/VkLayer_monitor.json.in
Change-Id: I8a85e11fa796dd8d53122c0c86d8cf0a971437d1
=> monitor: add url and introduction to layer manifest

layersvt/VkLayer_screenshot.json.in
Change-Id: Ia5437c83f22fa06d1499ad043c3ad26e60e92643
=> screenshot: add url and introduction to layer manifest

vkconfig/CHANGELOG.md, vkconfig/alert.cpp, vkconfig/alert.h, vkconfig/dialog_custom_paths.cpp, vkconfig/dialog_layers.cpp, vkconfig/dialog_layers.h, vkconfig/dialog_layers.ui, vkconfig/main_layers.cpp, vkconfig/mainwindow.cpp, vkconfig/mainwindow.h, vkconfig_core/doc.cpp, vkconfig_core/layer.cpp, vkconfig_core/layer.h, vkconfig_core/override.cpp, vkconfig_core/test/test_configuration_manager.cpp, vkconfig_core/test/test_layer.cpp
=> vkconfig: Refactor the layer window to expose more layer documentation

vkconfig/CHANGELOG.md, vkconfig/configurator.cpp, vkconfig/dialog_custom_paths.cpp, vkconfig/dialog_custom_paths.h, vkconfig/dialog_custom_paths.ui, vkconfig/dialog_layers.cpp, vkconfig/dialog_layers.h, vkconfig/dialog_layers.ui, vkconfig/mainwindow.cpp, vkconfig/mainwindow.h, vkconfig/mainwindow.ui
=> vkconfig: improve user-defined path dialog

layersvt/VkLayer_device_simulation.json.in, layersvt/device_simulation.cpp, layersvt/device_simulation.md
Implemented format list and property modification to be separately
controlled by array combination mode enums.
=> devsim: Add combination modes for format props

vkconfig/CHANGELOG.md, vkconfig/settings_tree.cpp, vkconfig/settings_validation_areas.cpp, vkconfig/settings_validation_areas.h
=> vkconfig: Add indirect parameter setting to validation built-in UI #1522

vkconfig/CHANGELOG.md, vkconfig_core/environment.cpp
Change-Id: Iec8d45a2b0cb31ad1849135263d87bcd912c2893
=> vkconfig: Fix upgrade of 'vkcube' path when the path is no longer valid

vkconfig/vulkan.cpp
Change-Id: I19ca23449197f05ec2dc6ed9ce96770cf3b8e591
=> vkconfig: clean up, there is no local/global here

vkconfig/CHANGELOG.md, vkconfig/mainwindow.cpp, vkconfig/vkconfig.pro, vkconfig_core/date.cpp, vkconfig_core/date.h, vkconfig_core/test/CMakeLists.txt, vkconfig_core/test/test_date.cpp
=> vkconfig: add build date in the title bar

via/via_system.cpp
Summary:
Fix single backslash in settings file setting that causes JSON error
when outputting.  Replace all settings single backslashes with double.
=> via: Fix single backslash json failure in settings file

vkconfig_core/doc.cpp, vkconfig_core/layers/130/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layers/135/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layers/141/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layers/148/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layers/154/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layers/162/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layers/170/VK_LAYER_KHRONOS_validation.json
<html>
<body>
<h1 id="top" style="color: rgb(164, 30, 34); font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/khronos_validation_layer.html" style="color: rgb(164, 30, 34);">VK_LAYER_KHRONOS_validation</a></h1><h3 style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; …
=> vkconfig: fix platforms generated doc

layersvt/device_simulation.cpp, layersvt/device_simulation_examples/sdk_sample_configs/portability_desktop_1_0.json, layersvt/device_simulation_examples/sdk_sample_configs/portability_desktop_1_2.json, layersvt/device_simulation_examples/sdk_sample_configs/portability_minimum_vulkan_1_0.json, layersvt/device_simulation_examples/sdk_sample_configs/portability_minimum_vulkan_1_1.json, layersvt/device_simulation_examples/sdk_sample_configs/portability_minimum_vulkan_1_2.json, layersvt/device_simulation_examples/sdk_sample_configs/spec_minimum_vulkan_1_0.json, layersvt/device_simulation_examples/sdk_sample_configs/spec_minimum_vulkan_1_1.json, layersvt/device_simulation_examples/sdk_sample_configs/spec_minimum_vulkan_1_2.json
Added the ability for Devsim to read in values from the GPUinfo file
format.
Change-Id: Ie2e031f723dc56286f5fee763ab2324f634f965c
=> [FOR REVIEW] devsim: Add GPUinfo file format as valid config

vkconfig/CHANGELOG.md, vkconfig_core/layer.cpp, vkconfig_core/layers/layers_schema.json, vkconfig_core/setting.cpp, vkconfig_core/version.cpp, vkconfig_core/version.h
Change-Id: I77ce769a0dd2d1ea8ae6c9c50094875721739743
=> vkconfig: add examples and descriptions to the schema

vkconfig/settings_validation_areas.cpp
=> vkconfig: fix shader-based UI invalidaly enabled

scripts/update_deps.py
CMake heavily prefers forward slashes, this commit makes the helper.cmake
file print forward slashes instead of backwards slashes on windows. Also updates Update_deps.py
to match VVL.
=>  build: Update update_deps.py 

layersvt/device_simulation.cpp
Added vkGetPhysicalDeviceImageFormatProperties function overrides to the
device simulation layer to properly curate format support for each
images based on simulated format properties list.
Fixes #1604
=> devsim: Add image format properties

vkconfig/settings_validation_areas.cpp, vkconfig/settings_validation_areas.h
Change-Id: I5ce32839447bee45d6a7d80999ad004c21e88ef3
=> vkconfig: add gpuav_descriptor_indexing support to built-in UI

vkconfig/widget_setting_filesystem.cpp
Change-Id: I8d26ba77332a3ecae7ab9debb9acb87d91b5a69a
=> vkconfig: fix folder selection

vkconfig/dialog_custom_paths.cpp, vkconfig/dialog_layers.cpp, vkconfig_core/alert.cpp, vkconfig_core/alert.h, vkconfig_core/configuration_manager.cpp, vkconfig_core/configuration_manager.h
Change-Id: I69e49d4aa7c03c597e9cf6c6eeacfd5af5778029
=> vkconfig: add check of the api-version and layer version

vkconfig_core/override.cpp
Change-Id: I26b100eb4fae09e43b610cd6ea43b95836d72a4d
=> vkconfig: system paths are added last in override_paths

layersvt/screenshot.cpp
The screenshot layer needs a list of all devices queried by the app.
It gets them by intercepting calls to VkGetEnumeratePhysicalDevices.
vkEnumeratePhysicalDeviceGroups was later added to the Vulkan API,
and it too allows apps to get a list of devices.  This commit adds
vkEnumeratePhysicalDeviceGroups to the screenshot
layer so the layer gets the list of devices queried using that API call.
Fixes Issue #1314
=> Add vkEnumeratePhysicalDeviceGroups to screenshot layer

vkconfig/configurator.cpp, vkconfig/dialog_layers.ui, vkconfig/main_doc.cpp, vkconfig/mainwindow.cpp, vkconfig/mainwindow.ui, vkconfig/widget_setting_filesystem.cpp, vkconfig_core/alert.cpp, vkconfig_core/configuration_manager.cpp, vkconfig_core/configuration_manager.h, vkconfig_core/help.cpp, vkconfig_core/layer.cpp, vkconfig_core/layer.h, vkconfig_core/parameter.cpp, vkconfig_core/setting_float.cpp, vkconfig_core/setting_int.cpp, vkconfig_core/test/test_configuration_manager.cpp, vkconfig_core/test/test_parameter.cpp
Change-Id: Id890a0d84e0e0cc3ad2bd40bea2439e3c6e3f705
=> vkconfig: bugfixing

vkconfig/configurator.cpp, vkconfig/configurator.h, vkconfig/main_layers.cpp, vkconfig/main_reset.cpp, vkconfig/mainwindow.cpp, vkconfig/mainwindow.ui, vkconfig/vulkan.cpp, vkconfig_core/help.cpp
- Resolve button style changing on macOS
=> vkconfig: 209 bugfixing

vkconfig/CHANGELOG.md, vkconfig/dialog_layers.ui, vkconfig/mainwindow.ui
Change-Id: Ia65c3d510cb96f0e3cd127b325c909357c988208
=> vkconfig: 211 bugfixing

vkconfig_core/override.cpp
Change-Id: I759bfd083cc7d91464726eb6b2dbf69c42a37638
=> vkconfig: fix app list regression

vkconfig/settings_tree.cpp, vkconfig/settings_validation_areas.cpp, vkconfig/settings_validation_areas.h
=> vkconfig: add support for vma_linear_output built-in setting

vkconfig/mainwindow.cpp, vkconfig/mainwindow.h, vkconfig/mainwindow.ui
=> vkconfig: add vulkancapsviewer launcher

vkconfig/mainwindow.cpp, vkconfig/mainwindow.h, vkconfig/mainwindow.ui
We will have an option to launch it at the end of the installer
=> vkconfig remove vkcapsviewer launcher

vkconfig/dialog_custom_paths.cpp, vkconfig/dialog_layers.cpp, vkconfig_core/alert.cpp
=> vkconfig: prevent mixing layer versions

BUILD.md, build-android/android-generate.bat
=> Fix Android build and doc

vkconfig_core/environment.cpp
Change-Id: I527c116fc8b3b84af8edca8f4530292b803d3b90
=> vkconfig: search for executable locally if not found

via/via_system_bsd.cpp, via/via_system_linux.cpp, via/via_system_macos.cpp, via/via_system_windows.cpp
Display the Vulkan version from vulkan_core.h
=> Display correct Vulkan API Version in vkvia

vkconfig/configurator.cpp, vkconfig/configurator.h, vkconfig/main.cpp, vkconfig/main_doc.cpp, vkconfig/main_gui.cpp, vkconfig/main_gui.h, vkconfig/main_layers.cpp, vkconfig/main_signal.cpp, vkconfig/settings_validation_areas.cpp, vkconfig/settings_validation_areas.h, vkconfig/vulkan_util.cpp, vkconfig_core/command_line.cpp, vkconfig_core/command_line.h, vkconfig_core/configurations/2.2.2/Synchronization.json, vkconfig_core/environment.cpp, vkconfig_core/environment.h, vkconfig_core/path_manager.cpp, vkconfig_core/path_manager.h, vkconfig_core/test/test_configuration_built_in.cpp, vkconfig_core/test/test_configuration_manager.cpp, vkconfig_core/test/test_environment.cpp, vkconfig_core/test/test_layer_manager.cpp, vkconfig_core/test/test_override.cpp, vkconfig_core/test/test_path_manager.cpp
Change-Id: Ib56297c72e3655e5bf7fd1b4e2376102744ae937
=> vkconfig: add VULKAN_SDK undocumented cmd arg

via/via_system_bsd.cpp, via/via_system_linux.cpp, via/via_system_macos.cpp, via/via_system_windows.cpp
Fixes https://github.com/LunarG/VulkanTools/issues/930
=> via: Change "LunarG Vulkan SDKs" to "Vulkan SDKs" in output

vkconfig/settings_validation_areas.cpp, vkconfig/settings_validation_areas.h
=> vkconfig: add nvidia best practices setting

via/via_system.cpp, via/via_system_linux.cpp
Addresses issue https://github.com/LunarG/VulkanTools/issues/948
=> via: Report if failed test is due failure or if test is missing

vkconfig/main_gui.cpp, vkconfig_core/application_singleton.cpp, vkconfig_core/application_singleton.h
- fix blocking other instances
=> vkconfig: 224 bugfixes

via/via_system.cpp
Added portability extensions to vkCreateDevice and vkCreateInstance
calls so that when via is run from vkconfig, validation errors
are not generated.
Addresses issue https://github.com/LunarG/VulkanTools/issues/1495
=> via: Address validation errors on macOS

layersvt/monitor.cpp, scripts/layer_factory_generator.py
Unused header so it should be removed.
=> monitor: Remove vk_loader_platform.h header

.github/workflows/ci_build.yml, vkconfig/CHANGELOG.md, vkconfig/settings_validation_areas.cpp, vkconfig/settings_validation_areas.h, vkconfig_core/version.cpp
=> vkconfig: add warn_on_robust_oob val setting

vkconfig/settings_validation_areas.cpp, vkconfig/settings_validation_areas.h
=> vkconfig: Add Imagination Technologies best practices

vkconfig/settings_tree.cpp, vkconfig_core/configuration.cpp, vkconfig_core/parameter.cpp, vkconfig_core/parameter.h
=> vkconfig: fix validation layer with generic layer settings

vkconfig/configurator.cpp, vkconfig/configurator.h, vkconfig/mainwindow.cpp, vkconfig/vulkan_util.cpp, vkconfig/widget_setting_enum.cpp
=> vkconfig: add built-in variation to list physical devices

vkconfig/widget_setting_enum.cpp
Ensure when no physical device when chosen that the first one is selected.
=> vkconfig: fix force physical device by name

vkconfig/resources.qrc, vkconfig_core/configurations/2.2.2/Physical Device Selection.json
=> vkconfig: add default physical device selection config

vkconfig_core/doc.cpp
Changed code so these values are displayed on separate lines
=> vkconfig doc: Change output of "Setting Type" & "Setting Default Value"

via/via_system_macos.cpp
The MacOS on the M1 produced a product version that seems to have a tab in it which messes up VkVia.  Attempt to fix this.
=> Fix JSON output on Mac M1

layersvt/monitor.cpp
The monitor layer uses GetWindowText to retrieve the title bar text.
This function is effectively SendMessage(WM_GETTEXT), and so has all
the same threading behavior of SendMessage. That is fine if the thread
calling into monitor layer is able to handle it. But in certain
circumstances, calling GetWindowText causes a deadlock, such as when
the monitor layer is enabled during the replay of a renderdoc capture.
The fix is to move the call of GetWindowText to vkQueuePresentKHR, since
that does get called from a thread that can handle GetWindowText.
A more robust method would be to not use GetWindowText but instead use
Windows API calls that have better threading characteristics.
To recreate the issue without the fix, set VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_monitor in the global environment …
=> monitor: Fix windows crash when using renderdoc

scripts/known_good.json
Skip updating Android due to VVL Android cmake build
=> Update to 1.3.260 headers

.github/workflows/ci.yml, .github/workflows/format.yml, CMakeUserPresets.json, scripts/github_ci_android.py
Fixup performance issues
Fixup CI warnings
=> ci: Cleanup GitHub Actions CI

scripts/api_dump_generator.py
vkGetInstanceProcAddr is able to query device functions, which was not being done by api_dump. This caused debug utils functions to not be intercepted due to changes in how the loader queries those functions.
=> apidump: Query device functions during GetInstanceProcAddr

CMakeLists.txt, layersvt/CMakeLists.txt, layersvt/VkLayer_api_dump.json.in, layersvt/api_dump.h, layersvt/test/CMakeLists.txt, layersvt/test/layer_test_framework.cpp, layersvt/test/layer_test_framework.h, layersvt/test/layer_test_helper.cpp, layersvt/test/layer_test_helper.h, layersvt/test/layer_test_main.cpp, layersvt/test/test_api_dump.cpp, layersvt/test/test_monitor.cpp, layersvt/test/test_screenshot.cpp, scripts/api_dump_generator.py, scripts/known_good.json
I added a layer test framework, based on the Profiles solution layer test framework, so that we can use it to debug, step in layer code, with Visual Studio
=> layer: Use layer settings library in API dump

layersvt/api_dump.h
If the filename provided in the settings file does not end with the corresponding extension for the output type, api dump will append it.
=> apidump: Append file extension is not present

.github/dependabot.yml, .github/workflows/ci.yml
- Add dependabot
- Check that we don't break ubuntu backcompat
=> dependabot / ubuntu back compat

CMakeLists.txt, scripts/known_good.json, via/CMakeLists.txt
=> Use jsoncpp package config support

scripts/known_good.json
Need newer version of the loader which contains fixes for iOS
=> scripts: Update dependencies to version 1.3.269

.github/workflows/ci.yml, CMakeLists.txt, layersvt/CMakeLists.txt, layersvt/api_dump.h
Currently only API dump is being built/installed
=> Add iOS build to CI

layersvt/test/layer_test_helper.h
std::strlen is defined in cstring
=> Fix build failure

CMakeLists.txt, layersvt/json/VkLayer_screenshot.json.in, layersvt/screenshot.cpp, layersvt/test/layer_test_helper.cpp, layersvt/test/test_api_dump.cpp
Tested it locally using vkconfig and it worked just like on Linux.
=> Build screenshot layer for MacOS

scripts/api_dump_generator.py, scripts/known_good.json
Also removes workaround for missing tags in video.xml
=> Update Headers to 1.3.280

layersvt/screenshot.cpp
Ensures that the printf statement makes it to the output.
=> screenshot: Flush after printf

layersvt/screenshot.cpp
When a user's output image format is SINT or UINT, and screenshot has to change it back to whatever is compatible with the swapchain image format, make sure to choose one with the correct swizzling.
=> screenshot: Use RGBA format if output is BGRA

vkconfig/widget_setting_enum.cpp, vkconfig/widget_setting_enum.h, vkconfig_core/alert.cpp, vkconfig_core/alert.h, vkconfig_core/json.cpp, vkconfig_core/layer.cpp, vkconfig_core/path.cpp, vkconfig_core/util.h
=> vkconfig: Fix profile names enum behavior

vkconfig/CHANGELOG.md, vkconfig/configurator.cpp, vkconfig/configurator.h, vkconfig/dialog_layers.cpp, vkconfig/mainwindow.cpp, vkconfig/mainwindow.h, vkconfig/mainwindow.ui, vkconfig/widget_preset.cpp
Some Qt event things evolved recurvice of UpdateUI calls which create UI slow downs
=> vkconfig: Fix UpdateUI calling UpdateUI recursively and add status button

vkconfig/mainwindow.cpp
=> vkconfig: Fix 'import' being disabled in the context menu

vkconfig/CHANGELOG.md, vkconfig/README.md, vkconfig/main.cpp, vkconfig3/main.cpp
Reffectively revert: https://github.com/LunarG/VulkanTools/pull/1978/files
=> vkconfig: Disable command line output redicrection on Windows

vkconfig/CHANGELOG.md, vkconfig/CMakeLists.txt, vkconfig/README.md, vkconfig/main.cpp, vkconfig/mainwindow.cpp
Another try at https://github.com/LunarG/VulkanTools/issues/1666
=> vkconfig: Add 'Command Prompt' support with command line mode

vkconfig/mainwindow.cpp, vkconfig_core/environment.cpp
Now the pop up message appears when clicking the "Keep Vulkan Configurator Running...." check box which is unchecked by default.
=> vkconfig: Closing main window exit by default

vkconfig/mainwindow.cpp, vkconfig/vulkan_util.cpp, vkconfig_core/configuration_manager.cpp
=> vkconfig: Fix disabled mode display on start

vkconfig_core/configuration.h, vkconfig_core/test/CMakeLists.txt, vkconfig_core/test/test_ui.cpp, vkconfig_core/ui.cpp, vkconfig_core/ui.h, vkconfig_gui/mainwindow.cpp, vkconfig_gui/mainwindow.h, vkconfig_gui/vkconfig.pro
=> vkconfig3: Add layers configuration context menu

vkconfig_core/configuration.cpp, vkconfig_core/configuration.h, vkconfig_core/configurator.cpp, vkconfig_gui/mainwindow.cpp, vkconfig_gui/mainwindow.h, vkconfig_gui/mainwindow.ui
=> vkconfig3: Add loader messages types per configuration

vkconfig_core/util.h, vkconfig_gui/mainwindow.ui, vkconfig_gui/tab_applications.cpp, vkconfig_gui/tab_applications.h
=> vkconfig3: Implement applications options

vkconfig/CHANGELOG.md, vkconfig/mainwindow.cpp, vkconfig_core/setting.cpp, vkconfig_core/setting_flags.cpp, vkconfig_core/version.cpp
=> vkconfig: Fix flags settings dependencies

vkconfig/CHANGELOG.md, vkconfig_core/parameter.cpp, vkconfig_core/test/test_parameter.cpp
=> vkconfig: Fix implicit layer ordering

vkconfig_core/layer.h, vkconfig_core/layer_manager.cpp, vkconfig_core/layer_manager.h, vkconfig_core/test/test_layer_manager.cpp, vkconfig_core/type_layer_control.cpp, vkconfig_core/type_layer_control.h, vkconfig_core/type_layer_path_view.cpp, vkconfig_core/type_layer_path_view.h, vkconfig_core/type_layers_paths.cpp, vkconfig_core/type_layers_paths.h, vkconfig_gui/mainwindow.ui, vkconfig_gui/tab_configurations.cpp, vkconfig_gui/tab_layers.cpp, vkconfig_gui/tab_layers.h, vkconfig_gui/vkconfig.pro, vkconfig_gui/widget_tab_configurations_layer.cpp, vkconfig_gui/widget_tab_layers_path.cpp
=> vkconfig3: Layer tabs UI improvements

vkconfig_core/configuration.cpp, vkconfig_core/configuration.h, vkconfig_core/configurations/3.0.0/API dump.json, vkconfig_core/configurations/3.0.0/Crash Diagnostic.json, vkconfig_core/configurations/3.0.0/Frame Capture.json, vkconfig_core/configurations/3.0.0/Log Loader Messages.json, vkconfig_core/configurations/3.0.0/Portability.json, vkconfig_core/configurations/3.0.0/Synchronization.json, vkconfig_core/configurations/3.0.0/Validation.json, vkconfig_core/configurator.cpp, vkconfig_core/configurator.h, vkconfig_core/test/test_configuration_manager.cpp, vkconfig_gui/mainwindow.ui, vkconfig_gui/resources.qrc, vkconfig_gui/settings_tree.cpp
=> vkconfig3: Add Log Loader Messages built-in configuration

vkconfig_core/configuration.cpp, vkconfig_core/configuration.h, vkconfig_core/configurations/3.0.0/API dump.json, vkconfig_core/configurations/3.0.0/Crash Diagnostic.json, vkconfig_core/configurations/3.0.0/Disable All Vulkan Layers.json, vkconfig_core/configurations/3.0.0/Frame Capture.json, vkconfig_core/configurations/3.0.0/Portability.json, vkconfig_core/configurations/3.0.0/Synchronization.json, vkconfig_core/configurations/3.0.0/Validation.json, vkconfig_gui/resources.qrc
=> vkconfig3: Add disabled all layers configuration

vkconfig_core/layer_manager.cpp, vkconfig_core/registry.cpp, vkconfig_core/registry.h, vkconfig_gui/tab_configurations.cpp
=> vkconfig3: Fix loading of layers from Windows Registry

vkconfig_core/configurator.cpp, vkconfig_gui/settings_tree.cpp, vkconfig_gui/settings_tree.h, vkconfig_gui/tab_configurations.cpp, vkconfig_gui/tab_configurations.h, vkconfig_gui/vkconfig.pro, vkconfig_gui/widget_layer_version.cpp, vkconfig_gui/widget_layer_version.h, vkconfig_gui/widget_tab_configurations_layer.cpp
=> vkconfig3: Multiple layer versions only when multiple loaded

vkconfig_core/configuration.cpp, vkconfig_core/configurations/3.0.0/Disable All Vulkan Layers.json, vkconfig_core/configurator.cpp, vkconfig_core/configurator.h, vkconfig_core/layer.cpp, vkconfig_core/layer.h, vkconfig_core/layer_manager.cpp, vkconfig_core/parameter.h, vkconfig_core/registry.cpp, vkconfig_core/test/test_configuration.cpp, vkconfig_core/test/test_type_layer_type.cpp, vkconfig_core/type_layer_builtin.cpp, vkconfig_core/type_layer_builtin.h, vkconfig_core/type_layer_control.cpp, vkconfig_core/type_layer_control.h, vkconfig_core/type_layers_paths.cpp, vkconfig_core/type_layers_paths.h, vkconfig_gui/tab.h, vkconfig_gui/tab_about.h, vkconfig_gui/tab_applications.h, vkconfig_gui/tab_configurations.cpp, vkconfig_gui/tab_configurations.h, vkconfig_gui/tab_diagnostics.h, vkconfig_gui/tab_documentation.h, vkconfig_gui/tab_layers.cpp, vkconfig_gui/tab_layers.h, vkconfig_gui/vkconfig.pro, vkconfig_gui/widget_resize_button.cpp, vkconfig_gui/widget_resize_button.h, vkconfig_gui/widget_tab_configurations_layer.cpp
=> vkconfig3: Add 'Discard' layer control

vkconfig_gui/mainwindow.ui, vkconfig_gui/tab_layers.cpp
=> vkconfig: Fix layer paths rebuild on enabling/disabling path

layersvt/generated/api_dump.cpp, layersvt/generated/api_dump_html.cpp, layersvt/generated/api_dump_html.h, layersvt/generated/api_dump_json.cpp, layersvt/generated/api_dump_json.h, layersvt/generated/api_dump_text.cpp, layersvt/generated/api_dump_text.h, layersvt/json/VkLayer_api_dump.json.in, scripts/known_good.json
Uses the tmp branch for Volk for the time being
=> build: Update to Vulkan-Header 1.4.309

vkconfig_core/configurations/3.0.0/Frame Capture.json, vkconfig_core/configurator.cpp, vkconfig_core/path.cpp, vkconfig_core/test/test_path.cpp, vkconfig_gui/mainwindow.ui, vkconfig_gui/tab_preferences.cpp
=> vkconfig: Add Qt version to diagnostic

vkconfig_core/executable.cpp, vkconfig_core/layer.cpp, vkconfig_core/layer.h, vkconfig_core/layer_manager.cpp, vkconfig_core/layer_manager.h, vkconfig_core/setting.cpp, vkconfig_core/setting.h, vkconfig_core/test/test_executable.cpp, vkconfig_core/test/test_executable_manager.cpp, vkconfig_core/test/test_layer.cpp, vkconfig_core/test/test_layer_manager.cpp, vkconfig_core/test/test_layer_preset.cpp, vkconfig_core/test/test_path.cpp, vkconfig_gui/CHANGELOG.md, vkconfig_gui/mainwindow.ui, vkconfig_gui/tab_preferences.cpp, vkconfig_gui/widget_setting_filesystem.cpp
- Clean up environment variables
- Add ignoring invalid layer manifest when invalid until the file is modified
=> vkconfig: March 2025 SDK fixes

vkconfig_cmd/CMakeLists.txt, vkconfig_gui/CMakeLists.txt
Just fixing some copy and paste errors concerning messages when building Vkconfig against the static runtime.
=> Just fixes to some messages

vkconfig_core/executable.cpp, vkconfig_core/test/test_executable.cpp, vkconfig_core/test/test_executable_manager.cpp, vkconfig_gui/CHANGELOG.md, vkconfig_gui/main.cpp, vkconfig_gui/settings_tree.cpp, vkconfig_gui/style.cpp, vkconfig_gui/vkconfig.pro
- Fix built-in executable init on macOS
- Tentative fix for screenshot layer crash
=> vkconfig: Fix vkconfig.pro build on macOS

vkconfig_core/configurator.cpp, vkconfig_gui/CHANGELOG.md, vkconfig_gui/mainwindow.ui, vkconfig_gui/tab_about.cpp
=> vkconfig: Add Vulkan Header version to about tab

.github/workflows/ci.yml, vkconfig_core/configurator.cpp, vkconfig_core/configurator.h, vkconfig_core/type_theme_mode.cpp, vkconfig_core/type_theme_mode.h, vkconfig_gui/CHANGELOG.md, vkconfig_gui/main.cpp, vkconfig_gui/mainwindow.cpp, vkconfig_gui/mainwindow.h, vkconfig_gui/mainwindow.ui, vkconfig_gui/resourcefiles/DOCUMENTATION.md, vkconfig_gui/resources.qrc, vkconfig_gui/style.cpp, vkconfig_gui/tab_about.cpp, vkconfig_gui/tab_applications.cpp, vkconfig_gui/tab_configurations.cpp, vkconfig_gui/tab_diagnostics.cpp, vkconfig_gui/tab_documentation.cpp, vkconfig_gui/tab_layers.cpp, vkconfig_gui/tab_preferences.cpp, vkconfig_gui/tab_preferences.h, vkconfig_gui/vkconfig.pro
=> vkconfig: Add appearance selection: dark, light, device theme modes

vkconfig_core/configurator.h, vkconfig_core/type_diagnostic_mode.cpp, vkconfig_core/type_diagnostic_mode.h, vkconfig_gui/tab_diagnostics.cpp
=> vkconfig: Add diagnostic file export

vkconfig_core/doc.cpp
=> vkconfig: doc generation show Android variable

vkconfig_core/doc.cpp, vkconfig_core/layer.cpp, vkconfig_core/layer.h, vkconfig_core/layers/layers_schema.json, vkconfig_core/vulkan_util.cpp, vkconfig_core/vulkan_util.h, vkconfig_gui/CHANGELOG.md
=> vkconfig: Add layer prefix for Android system properties

vkconfig_core/configurator.cpp, vkconfig_core/configurator.h, vkconfig_core/layer.cpp, vkconfig_core/layer.h, vkconfig_core/message.cpp, vkconfig_core/message.h, vkconfig_core/setting.cpp, vkconfig_core/setting.h, vkconfig_core/type_button.cpp, vkconfig_core/type_button.h, vkconfig_core/type_severity.cpp, vkconfig_core/type_severity.h, vkconfig_gui/CHANGELOG.md, vkconfig_gui/main.cpp, vkconfig_gui/settings_tree.cpp, vkconfig_gui/vkconfig.pro, vkconfig_gui/widget_setting_bool.cpp
=> vkconfig: Add layer-defined messages

vkconfig_core/configurator.cpp, vkconfig_core/doc.cpp, vkconfig_core/header.cpp, vkconfig_core/header.h, vkconfig_core/layer.cpp, vkconfig_core/layers/layers_schema.json, vkconfig_gui/CHANGELOG.md, vkconfig_gui/settings_tree.cpp, vkconfig_gui/widget_setting_bool.cpp, vkconfig_gui/widget_setting_enum.cpp, vkconfig_gui/widget_setting_flags.cpp, vkconfig_gui/widget_setting_float.cpp, vkconfig_gui/widget_setting_int.cpp
=> vkconfig: Add deprecated_by setting property

vkconfig_core/doc.cpp, vkconfig_core/header.cpp, vkconfig_core/header.h, vkconfig_core/layers/layers_schema.json, vkconfig_core/path.cpp, vkconfig_core/path.h, vkconfig_gui/CHANGELOG.md, vkconfig_gui/tab_configurations.cpp
=> vkconfig: Add per-setting documentation

vkconfig_core/configurator.cpp
``` sh
#! Enable instrumenting shaders selectively - gpuav_select_instrumented_shaders
#! ==========================================
#!  Select which shaders to instrument by passing a VkValidationFeaturesEXT
#!  struct with GPU-AV enabled in the VkShaderModuleCreateInfo pNext or using a
#!  regex matching a shader/pipeline debug name. Because this only validates the
#!  selected shaders, it will allow GPU-AV to run much faster.
#! This setting requires ALL of the following values:
#! - export VK_KHRONOS_VALIDATION_GPUAV_ENABLE=true
#! - export VK_KHRONOS_VALIDATION_GPUAV_SHADER_INSTRUMENTATION=true
#! export VK_KHRONOS_VALIDATION_GPUAV_SELECT_INSTRUMENTED_SHADERS=false (Commented out as the set of dependences is not satisfied)
```
``` bat
:: Enable instrumenting shaders selectively - …
```
=> vkconfig: Add layer setting deps to generated env variable scripts

vkconfig_core/configurator.cpp, vkconfig_core/configurator.h, vkconfig_gui/CHANGELOG.md, vkconfig_gui/mainwindow.ui, vkconfig_gui/tab_preferences.cpp, vkconfig_gui/tab_preferences.h, vkconfig_gui/widget_tab_configurations_layer.cpp
vs
Configured with, disabled by default:
=> vkconfig: Add custom alternate row colors

vkconfig_core/doc.cpp, vkconfig_core/setting.cpp, vkconfig_core/setting.h
=> vkconfig: Add generated doc sub-setttings and usage examples to each setting

vkconfig_core/configurator.cpp, vkconfig_core/vulkan_util.cpp, vkconfig_core/vulkan_util.h, vkconfig_gui/tab_drivers.cpp
=> vkconfig: Add multiple driver version support
