LunarG/VulkanTools

icd/nulldrv/nulldrv.c, icd/nulldrv/nulldrv.h
This series untangles some of the extension handling in nulldrv, and has it claim to support KHR_xcb_surface. The entrypoints associated are not implemented, as they are never called when nulldrv is used with the loader.
Also assorted fixes to queries to avoid confusing the app with junk.
(Is just enough to get demos/tri working again)
=> Re-expose KHR_xcb_surface from nulldrv

vktrace/src/vktrace_layer/vktrace_lib_helpers.h
rangeoffset is not correctly set, so vktrace capture not correct for range offset not equal 0 in vkFlushMappedMemoryRanges.
=> fix rangeoffset problem

vktrace/vktrace_generate.py
* If the trace file recorded VK_SUCCESS as a result, then loop on the call to vkGetQueryPoolResults until it also has a successful return value. It can validly happen that the replay will return VK_NOT_READY, and the replay simply needs to wait a bit longer for the result to come back. This fix puts a do-while loop around vkGetQueryPoolResults and loops as needed.
=> vkreplay: Loop on vkGetQueryPoolResults return value.

vktrace/src/vktrace_viewer/vktraceviewer.cpp, vktrace/src/vktrace_viewer/vktraceviewer_qtimelineview.cpp
Fix issue #82. The timeline PaintEvent() handler was calling Update() which was issuing another paint event. Removing the extra Update didn't seem to have any negative side-effects, but fixed the CPU utilization.
=> Amd fix vktraceviewer paint

update_external_sources.sh
Not sure which file changed, but the second "git checkout" in the LunarGLASS path was complaining about overwriting files.  I don't think we need two checkouts, so I merged them to one forced checkout at a specific version.  This gets the toolchain building again.  vktracereplay.sh passes on Nvidia Linux.
=> toolchain: Get LunarGLASS building again

build-android/android-generate.bat, build-android/android-generate.sh, build-android/jni/Android.mk, scripts/vktrace_generate.py, vktrace/.gitignore, vktrace/CMakeLists.txt, vktrace/src/vktrace_extensions/vktracevulkan/CMakeLists.txt, vktrace/src/vktrace_extensions/vktracevulkan/vkreplay/CMakeLists.txt, vktrace/src/vktrace_extensions/vktracevulkan/vktraceviewer/CMakeLists.txt, vktrace/src/vktrace_layer/CMakeLists.txt, vktrace/src/vktrace_layer/vktrace_lib_trace.cpp, vktrace/src/vktrace_viewer/CMakeLists.txt
Common code-gen'd files now end up in single location, including those in vktrace.  VKtrace code-gen'd files now end up in build directory.  Common generated files are now built from dependencies instead of when cmake is run (vktrace files are still built at cmake time -- this is next).
=> VT generated files rework

vktrace/vktrace_layer/vktrace_lib_helpers.h, vktrace/vktrace_replay/vkreplay_vkreplay.cpp
Fix capture/playback error when target app create multiple graphics pipelines in one vkCreateGraphicsPipelines call, the error cause playback crash in later command call.
XCAP-585
Change-Id: I40280fcc3097f658ffb2e4d836a102d59dd4a447
=> vktrace: Fix error in creating multiple graphics pipelines

vktrace/vktrace_layer/vktrace_lib_trace.cpp
Add ROUNDUP_TO_4 when calculate VkGraphicsPipelineCreateInfo size in __HOOKED_vkCreateGraphicsPipelines, the change is for fix some title crash on vkCreateGraphicsPipelines problem during capture.
XCAP-585
Change-Id: I0a2e9d58910f373fd17087cb74c60ba42333783e
=> Add ROUNDUP_TO_4 when calculate VkGraphicsPipelineCreateInfo size

layersvt/screenshot.cpp
Screenshot layer was not handling the case that the most recently created
CommandPool object was also being destroyed, and thus was trying to use a
destroyed object. The layer now keeps a most-recently-created list of
CommandPools, and will utilize the one that was most recently created and
not yet destroyed. If there are no available CommandPools, then the
screenshot layer will not generate a file.
Fixes issue #182 
Change-Id: I8f248b44272f6b414f6ef578b962a2584c200e62
=> screenshot: Fix screenshot layer + trim compatibility.

vktrace/vktrace_layer/vktrace_lib_trace.cpp
Change *ppData to ppData in vktrace_add_buffer_to_trace_packet. The error cause unexpected page guard exception and wrong read PMB process on Windows platform.
XCAP-585
Change-Id: I522939fabe3bed86d13e5fa7a38cde85d301c474
=> vktrace: fix add buffer error in __HOOKED_vkMapMemory

vktrace/vktrace_layer/vktrace_lib_pageguard.cpp, vktrace/vktrace_layer/vktrace_lib_pageguardmappedmemory.cpp, vktrace/vktrace_layer/vktrace_lib_pageguardmappedmemory.h, vktrace/vktrace_layer/vktrace_lib_pagestatusarray.cpp, vktrace/vktrace_layer/vktrace_lib_pagestatusarray.h
In current implementation, once vkMapMemory get captured, vktrace allocate shadow memory with same mapped size, then memcpy real mapped memory to shadow memory. The change (only for Windows) removes the memcpy, and adds additional process in page guard exception handler: only if a page is first time accessed, the handler memcpy that page from real mapped memory to shadow memory. This optimization significantly improve target title capture time from hours to minutes, because the title use lots of big size map/unmap, and only a small portion of mapped size accessed by host side.
XCAP-585
Change-Id: I29f3add4553576679b3196f0b1595c096b77143e
=> vktrace: Remove memcpy to shadow memory in map memory process

vktrace/vktrace_layer/vktrace_lib_trim.cpp
Some titles hang when start to trimming on some hardware/drivers and
the reason is writing out of memory size when copy image to staging
buffer, the change fix the problem.
XCAP-647
Change-Id: I69ef8632365c6992619bb6b0054c5f077a10ea10
=> vktrace: Fix copy image to buffer error in trim

CMakeLists.txt
The only dependent component on JSONCPP is VIA. So
only search for JSONCPP when VIA is enabled.
Signed-off-by: Awais Belal <awais_belal@mentor.com>
=> CMakeLists: conditionalize JSONCPP search

vktrace/vktrace_replay/CMakeLists.txt, vktrace/vktrace_trace/CMakeLists.txt
Using hardcoded paths for source/header files
tends to break out-of-tree builds.
Signed-off-by: Awais Belal <awais_belal@mentor.com>
=> CMakeLists: do not use hardcoded paths

vktrace/README.md
Without the spaces between the title and the pound symbols, it looks awful when viewed by GitHub's Markdown render
=> vktrace: Fixed markdown headers rendering

vktrace/vktrace_layer/vktrace_lib_trace.cpp
Fixes a crash when an application uses a static const array for
ppEnabledLayerNames or ppEnabledExtensionNames.
Allocate memory for ppEnabledLayerNames and ppEnabledExtensionNames
arrays similarly how it's done in __HOOKED_vkCreateInstance().
=> Avoid modifying application memory in __HOOKED_vkCreateDevice()

layersvt/vk_layer_settings.txt
i.e. add `output_format` and `show_shader` documentation in `vk_layer_settings.txt`.
=> layersvt: Document api_dump settings

vktrace/CMakeLists.txt
The new `/guard:cf` flag conflicts with the `/ZI` flag in vktrace. This replaces `/ZI` with `/Zi` to resolve the error.
=> build: Fix windows build

CMakeLists.txt, scripts/vktrace_file_generator.py, vktrace/CMakeLists.txt, vktrace/vktrace_common/vktrace_multiplatform.h, vktrace/vktrace_common/vktrace_trace_packet_identifiers.h, vktrace/vktrace_layer/vktrace_lib_trace.cpp, vktrace/vktrace_replay/CMakeLists.txt, vktrace/vktrace_replay/vkreplay_vkdisplay.cpp, vktrace/vktrace_replay/vkreplay_vkdisplay.h, vktrace/vktrace_replay/vkreplay_vkreplay.cpp, vktrace/vktrace_replay/vkreplay_vkreplay.h, vktrace/vktrace_replay/vkreplay_window.h
In CMake, define VKREPLAY_WSI_SELECTION=<XCB/XLIB/WAYLAND> to choose which windowing system vkreplay will use.
=> vktrace/replay: Add Wayland support

layersvt/README.md, layersvt/device_simulation.cpp, layersvt/device_simulation.md, layersvt/device_simulation_examples/tiny1.json, tests/CMakeLists.txt, tests/devsim_layer_test.sh, tests/devsim_test1.json, tests/devsim_test1_gold.json
- port layer code and test data to devsim JSON schema at https://schema.khronos.org/vulkan/devsim_1_0_0.json
- remove references to vkjson
- minor code rearrangement and comments
- create config file samples subdir
- create gold result file for test comparison
- bump version
Known issues include: FIXME in documentation, await info re gpuinfo.
Change-Id: Ia75cf078bb65fa959959affbd1771ce6e977b24c
=> layersvt: Enhance devsim layer version 0.2.0

layersvt/device_simulation.cpp
Bump version to 1.0.0 for SIGGRAPH BoF announcement.
Minor change to schema URI: added trailing hash character.
Change-Id: I39a45b945c7f0d0939e5ae0070bd80d7a24f22d2
=> layersvt: Bump DevSim version to 1.0.0

vktrace/vktrace_replay/vkreplay.cpp, vktrace/vktrace_replay/vkreplay.h, vktrace/vktrace_replay/vkreplay_factory.h, vktrace/vktrace_replay/vkreplay_main.cpp, vktrace/vktrace_replay/vkreplay_vkreplay.h
This change sets m_frameNumber to loopStartFrame after each loop to
make the frame number counter m_frameNumber consistent with the frame
which startingPacket belongs to.
Otherwise the vkreplay will replay frames starts from loopStartFrame to
(loopStartFrame + loopEndFrame) in the second or later loop.  Because
the startingPacket is set to the first packet of frame "loopStartFrame"
but the m_frameNumber is reset to 0 which means the replayed content is
starts from the expected loopStartFrame but the internal frame counter
is starts from 0 instead of loopStartFrame.
=> vkreplay: Fix reset frame number when loopStartFrame is given.

layersvt/linux/VkLayer_device_simulation.json, layersvt/windows/VkLayer_device_simulation.json
Update the JSON manifest files to match the devsim .cpp version
An oversight, this should have been included in commit 8ef88437e184986bfa2ab2925e91094edf46fd20
It's very easy to forget to update the 3 files together.
=> layersvt: Update devsim versions in JSON manifest

layersvt/device_simulation.cpp, layersvt/linux/VkLayer_device_simulation.json, layersvt/windows/VkLayer_device_simulation.json
DevSim now verifies the contents of the "$schema" property and can
use that to determine how to parse the config file.
Bump version to 1.0.2.
A couple other minor tweaks and clang-format.
Change-Id: I68cf6adb948bc648e3d5da1612517dd880a6f1c9
=> layersvt: DevSim to verify schema is acceptable

layersvt/api_dump.h
Fixes crashes caused by asserts() in api_dump layer.
=> layersvt: Fix api_dump asserts

layersvt/device_simulation.cpp, layersvt/linux/VkLayer_device_simulation.json, layersvt/windows/VkLayer_device_simulation.json
Bump version to 1.0.3
This commit is a collection of small changes that don't affect existing
functionality.  There are general code improvements, and some preparation
for new functionality in development.
Among minor code reorganizations, function renames, comments added, also:
1) Use JsonCpp value.type() rather than value.is*().
An old JsonCpp design decision (and tagged as will-not-change): isObject()
unfortunately returns TRUE for nullValue.  Therefore, use explicit test of
type() to ensure a value is really only an objectValue.  isArray() has same
issue.  Changing all type checks to avoid value.is*().
2) Reduce type checking code, since types are enforced by schema validation.
3) Rename ApplyOverrides() to GetValue().  Split the value argument into
separate parent and name arguments. …
=> layersvt: DevSim 1.0.3 minor code reorgs

layersvt/device_simulation.cpp, layersvt/device_simulation.md, layersvt/linux/VkLayer_device_simulation.json, layersvt/windows/VkLayer_device_simulation.json
Bump version to 1.0.4
See issue https://github.com/LunarG/VulkanTools/issues/296
This depends upon pull request https://github.com/LunarG/VulkanTools/pull/304
Add some informational messages to help diagnose when values of a simulated device configuration are not compatible with the VkPhysicalDeviceLimits of the underlying actual device.  Those messages are enabled, along with other debug messages, using: export VK_DEVSIM_DEBUG_ENABLE="1"
=> layersvt: DevSim 1.0.4 GH296 Add debug msgs

layersvt/device_simulation.cpp, layersvt/device_simulation.md, layersvt/linux/VkLayer_device_simulation.json, layersvt/windows/VkLayer_device_simulation.json, tests/devsim_test1.json, tests/devsim_test1_gold.json
Add new Device Simulation layer support for the JSON sections VkPhysicalDeviceMemoryProperties and ArrayOfVkQueueFamilyProperties.
Changes include:
- Add JSON-loading and Vulkan-intercepting functions for the new sections
- Extend tests to exercise new features.
- Extend documentation.
- Some other small enhancements.
- Overall clang-format.
Change-Id: Id2327237ca61511e8efa1723e2d0d55476ae006a
=> layersvt: DevSim 1.1.0 add new features

scripts/api_dump_generator.py
Added exceptions for vkGetDeviceProcAddr and vkGetInstanceProcAddr in api_dump_generator as these functions require special cases which are already in place.
Fixes issue #253
=> tools: Remove unnecessary functions from codeGen

scripts/vktrace_file_generator.py, vktrace/vktrace_replay/CMakeLists.txt, vktrace/vktrace_replay/vkreplay_vkreplay.cpp, vktrace/vktrace_replay/vkreplay_vkreplay.h
Previously, vkreplay was generating its own dispatch table. Now use
dispatch table generated for the layers.
Change-Id: I2b10e97611f4dd8287eef57f631df1c0b59ed2a0
=> vkreplay: Use vk_layer_dispatch_table

build-android/devsim_layer_test_android.sh, layersvt/device_simulation.cpp, layersvt/device_simulation.md, layersvt/linux/VkLayer_device_simulation.json, layersvt/windows/VkLayer_device_simulation.json, tests/devsim_layer_test.sh, tests/devsim_test1.json, tests/devsim_test1_gold.json
Add ability to override the results of vkGetPhysicalDeviceFormatProperties()
DevSim currently supports only Vulkan v1.0.  Check and cleanly emit an error
message if the application requests a Vulkan version other than v1.0.
Rework the test script to use 'jq' to extract sections of the test's JSON
output, sort, and reformat for consistent comparison against gold file.
Disable some of the noisier debug outputs.
Fix VisualStudio warnings
Update the .md documentation file.
Bump version to v1.2.0
Change-Id: I54deec8772056ad8649e3b0ae16a6d6c16148ba5
=> layersvt: DevSim 1.2.0 add new features

scripts/api_dump_generator.py
This change is to fix the unexpected "UNUSED" being recorded in VkWriteDescriptorSet.pImageInfo
for image with VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT type.
=> layersvt: api dump fix incorrect pImageInfo

BUILDVT.md, build-android/devsim_layer_test_android.sh, layersvt/device_simulation.cpp, layersvt/device_simulation.md, layersvt/linux/VkLayer_device_simulation.json, layersvt/windows/VkLayer_device_simulation.json, tests/CMakeLists.txt, tests/devsim_layer_test.sh, tests/devsim_test1_in.json, tests/devsim_test1_in_ArrayOfVkFormatProperties.json
Device Simulation Layer can now load multiple configuration files by specifying a delimited list of filenames in the VK_DEVSIM_FILENAME environment variable.  The delimited list borrows the syntax of the PATH environment variable: on Windows, separate the filenames with ';', on Linux separate with ":".
Add documentation for the multiple configuration filename to the .md file.
Some minor rearrangement of comments and debug messages.
Restructure/rename the regression test input files to exercise and make use of the new list of configuration files feature.
The "test1" input configuration now consists of several file fragments that are all loaded at runtime to create the complete configuration.
This feature permits configuration files to be modular, with boilerplate data in separate files.
=> Devsim 1.2.1 multiple input files

vktrace/vktrace_replay/vkreplay_vkreplay.cpp
Fixes error in replay of old 32-bit trace files.
Change-Id: I5303e8dba73e30050c8b270e65be5fbdbad71d9b
=> vktrace: Extract correct ret val of vkAllocMem on replay

vktrace/vktrace_common/vktrace_pageguard_memorycopy.cpp, vktrace/vktrace_common/vktrace_pageguard_memorycopy.h, vktrace/vktrace_layer/vktrace_lib_pageguardmappedmemory.cpp, vktrace/vktrace_layer/vktrace_lib_pageguardmappedmemory.h
=> vktrace: Remove trace layer warnings

vktrace/vktrace_common/vktrace_pageguard_memorycopy.h
Made an an assumption when cleaning up warnings, undoing change.
Change-Id: If46589d893130a9e8b7fbe6b2b45dc175a04ece7
=> vktrace/replay: Fix pageguard delta structure type

scripts/layer_factory_generator.py
Deleting (possibly) invalid keys at destroy instance and device time.  This showed up occasionally as an assert on Windows and more often on Linux when terminating a test app with a VLF layer running.
=> Fix bad VLF device/instance dispatch_keys

layer_factory/CMakeLists.txt
@karl-lunarg, this seems to work fine on Linux, but (at least on my system) will consistently fail on Windows.  I have more than a hunch that this is due to some quirk with Visual Studio and the Generated File facilities of CMake.
These two commits make the VLF cmake file a bit easier to understand and are more consistent with VT and with internet consensus.
Note: I still see multiple 'Generating layer_factory.cpp' outputs in the top of master-submodules-cleanup branch, though I do NOT see them with this branch.
=> VLF Parallel Build Cmake Fixes

tests/CMakeLists.txt, tests/vlf_test.ps1, tests/vlf_test.sh
These powershell and bash scripts will set up and excute vulkaninfo with the demo_layer and check the output for correctness.  Need to add one for api_dump soon, and to fix the currently busted vktrace_replay test scripts.
=> Add VLF test scripts

build-android/build_vktracereplay.sh, build-android/install_all.sh, layersvt/screenshot.cpp
Screenshot has been broken since end of December merge from LVL.  Found time to track it down today.  The switch from gnustl_static to c++_static STL libraries exposed a bug where a pointer to contents of a local string were being returned.  Writing the value back to our global envvar gets things working again.
Also, updated some scripts that were missed during move to submodules.
vktrace/vkreplay and screenshot are working now.  devsim has one difference I'll work with @mikew-lunarg  on.
=> Android fixes

via/via.cpp
For gcc version 5.4.0 of Ubuntu 16.04.3 LTS, resolve this compilation message:
warning: ignoring return value of ‘int chdir(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
Change-Id: Idcc2f867d997d96e28c4109e62f9efbd61eca87b
=> via: Quiet annoying GCC warning message

layer_factory/layer_factory_linux.json, layer_factory/layer_factory_windows.json, layersvt/linux/VkLayer_api_dump.json, layersvt/linux/VkLayer_device_simulation.json, layersvt/linux/VkLayer_monitor.json, layersvt/linux/VkLayer_screenshot.json, layersvt/windows/VkLayer_api_dump.json, layersvt/windows/VkLayer_device_simulation.json, layersvt/windows/VkLayer_monitor.json, layersvt/windows/VkLayer_screenshot.json, vktrace/vktrace_layer/linux/VkLayer_vktrace_layer.json, vktrace/vktrace_layer/windows/VkLayer_vktrace_layer.json
- updated layer json files
- updated LVL submodule to TOT, including 69 header changes
=> Update VulkanTools to 1.0.69 Vulkan Header

tests/vktracereplay.py
vktrace.exe would continue to run in the background when an application
failed to replay in vktracereplay.py regression test.
Change-Id: I68f9a180a37b821b5be292c70ab40251107b9891
=> tests: Fix rogue vktrace.exe when test fails

tests/vktracereplay.py
When the application fails to trace or replay when running trace/replay
regression, print the output of the application that contains errors.
Change-Id: I2cad892ba0e7c0329baf9f19bd6dc5476b0b2911
=> tests: Print error lines in vktracereplay.py

scripts/vktrace_file_generator.py
Remove assignment of VK_SUCCESS to failed device layer enumerations.
Change-Id: Ifd3ff1b51842b44f7cdd9102ea282f323e4ff228
=> vktrace: Remove VkResult reassignment in replay

scripts/vktrace_file_generator.py, vktrace/vktrace_replay/vkreplay_vkreplay.cpp, vktrace/vktrace_replay/vkreplay_vkreplay.h
Instead of replaying vkEnumerateDeviceExtensionProperties with the
pPropertyCount in the packet, use the value from the last query on the
physical device.
Change-Id: I2755376ebd8c73c7eba45d4f7521d005ddf2022e
=> vktrace: Use mapped property count for device ext.

layer_factory/assistant_layer/exclusive_qfi.h, layer_factory/assistant_layer/interceptor_objects.h
Added an interceptor to the assistant layer which warns if an app specifies a queueCount > 1 while also specifying a sharing mode of EXCLUSIVE. See github issue #2137.
=> Assistant Layer: Add check for too many queues

layer_factory/assistant_layer/zero_counts.h
From LVL issue #1912, add this to assistant layer in the existing zero_counts interceptor.  Also fixed a leftover bug in the original.
=> Add new Assistant Layer Check for CmdDispatch groupCounts set to Zero

layersvt/api_dump.h, scripts/api_dump_generator.py
This change addresses LVL github issue [#2107](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2107).
VK_LAYER_LUNARG_api_dump layer now displays object handle and name if set.
=> apidump : Display object name with handle

vktrace/vktrace_replay/vkreplay_vkreplay.cpp
Fix gcc "may be used uninitialized in this function" warnings.
Change-Id: I6de28d3ad150b97c166f44ecfd9a161d1f329138
=> vktrace: Fix vkreplay warnings

vktrace/vktrace_replay/vkreplay_vkreplay.cpp
In CreateDescriptorSetLayout, pImmutableSamplers should only be
dereferenced in certain cases.
Change-Id: I8a4522ec467fc0cae1a10611b8118b0501e08573
=> vktrace: Fix invalid deference of samplers

vktrace/vktrace_trace/vktrace_process.cpp
If the RecordTraceThread fails to create the header, exit but don't
delete the process info. This is deleted at the end of main() anyways.
Change-Id: I1e8873db36b55daddc3d091e54b6c36d4d306724
=> vktrace: Fix crash after header failure

vktrace/vktrace_common/vktrace_settings.c, vktrace/vktrace_replay/vkreplay.cpp, vktrace/vktrace_replay/vkreplay_main.cpp, vktrace/vktrace_replay/vkreplay_main.h, vktrace/vktrace_replay/vkreplay_settings.cpp
Fixes #395 
and addresses a similar problem with the -lsf and -lef settings.
=> Fix vkreplay arg processing to reject negative values for unsigned settings.

vktrace/vktrace_replay/vkreplay_vkreplay.cpp, vktrace/vktrace_replay/vkreplay_vkreplay.h
When enumerating physical devices in vkreplay, first check for a
matching device based on the vendor and hardware IDs. If no match is
found, map based on the indices.
Change-Id: I606886de30408380aba68a6ad3039ffa9a78420a
=> vktrace: Search for matching physical device

scripts/vktrace_file_generator.py
Fix for LunarXchange 757.
The pNext field for VkPipelineRasterizationStateCreateInfo structs was getting interpreted (converted) twice.  This would cause vkreplay to crash if this pNext pointed to something.
Can easily repro this problem by adding a struct to pNext in the cube demo.  Then create a trace and then replay.
```diff
diff --git a/demos/cube.c b/demos/cube.c
index b8b4950..4e9180f 100644
--- a/demos/cube.c
+++ b/demos/cube.c
@@ -1971,6 +1971,10 @@ static void demo_prepare_pipeline(struct demo *demo) {
rs.rasterizerDiscardEnable = VK_FALSE;
rs.depthBiasEnable = VK_FALSE;
rs.lineWidth = 1.0f;
+    VkPipelineRasterizationStateRasterizationOrderAMD a;
+    a.sType = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_RASTERIZATION_ORDER_AMD;
+    a.pNext = NULL;
+    rs.pNext = …
```
=> vkreplay: Fix pNext processing error

vktrace/vktrace_common/vktrace_trace_packet_utils.c
Removes an assert from vktrace_add_buffer_to_trace_packet() that
required the buffer size to be a multiple of 4. This function handles
buffers with sizes that are not multiples of 4, and the unnecessary
assert is causing some traces to fail.
=> vktrace: Remove buffer size assert from data copy

vktrace/vktrace_replay/vkreplay_vkreplay.cpp
When CreateInstance or CreateDevice fails with EXTENSION_NOT_PRESENT, the first thing I always want to know is what extensions were being asked for.  This makes finding that out easier.
Change-Id: I972600af7346e26497cc1fd9a12eb5267d7717fa
=> vkreplay: Log requested extensions on failure

build-android/android-generate.bat, build-android/android-generate.sh
build_all.sh in Android failed to build because the LVL submodule
did not have the generated include files in the proper location.
This has been verified on Linux, and needs to be verified on
Windows.
=> android: Fix android build

scripts/tool_helper_file_generator.py
vktrace layer needs strings sizes to be multiple of 4 for
data alignment in the trace file.
Migrated from https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/pull/2457
=> Roundup strings sizes in struct to multiple of 4

vktrace/vktrace_viewer/CMakeLists.txt
Add a CMake install target for vktraceviewer when generating build files for CMake UNIX targets.
Addresses #468.
=> Add install target for vktraceviewer

vktrace/vktrace_layer/vktrace_lib_trim.cpp
The trace trim code was not initializing VkFenceCreateInfo::pNext to
NULL and an uninitialized value was written to the trace file.  This
would lead to replay crashes at fence creation when pNext contained
a non-zero value, such as an uninitialized memory debug pattern.
=> vktrace: Fix trimming for VkFenceCreateInfo

scripts/vktrace_file_generator.py, vktrace/vktrace_layer/vktrace_lib_trace.cpp
With this change, not only images being bound to device only memory but
also images with optimal tiling will be saved in linear layout using a
staging buffer via vkCmdCopyImageToBuffer.
It helps the trimmed trace file to have possibility to work on a
different GPU by saving image data in linear because image with optimal
tiling may have different memory layout on different GPUs.
=> vktrace: store image in linear when doing trim

build-android/vkreplay/AndroidManifest.xml, vktrace/vktrace_replay/vkreplay_main.cpp, vktrace/vktrace_replay/vkreplay_vkdisplay.cpp, vktrace/vktrace_replay/vkreplay_vkdisplay.h, vktrace/vktrace_replay/vkreplay_window.h
Implements vkDisplay::resize_window for Android, to adjust the
screen orientation based on the requested window width and height.
Screen orientation is changed by invoking Activity.setRequestedOrientation
through JNI.
=> vktrace: Adjust Android screen orientation for replay

build-android/vktracereplay.sh
When running vktracereplay.sh, if the screenshot image is never received,
kill the app.
Change-Id: I292fb91e1ed35063032e443eefc113a0602f4dda
=> android: vktracereplay.sh: Stop timed out app

layersvt/VkLayer_device_simulation.def, layersvt/device_simulation.cpp, layersvt/linux/VkLayer_device_simulation.json, layersvt/windows/VkLayer_device_simulation.json, tests/devsim_test2_gold.json, tests/devsim_test2_in1.json
This is basically PR #483 without the pre-instances calls and test.
(Saving those pre-instance changes for the resolution of the Loader design.)
Prepare code for upcoming devsim_1_1_0 schema support.
Implemented devsim_1_0_0 schema's ArrayOfVkLayerProperties section.
Schema devsim_1_0_0 ArrayOfVkExtensionProperties section is deprecated due to shortcomings in its design; that section will be superseded by new sections in the upcoming devsim_1_1_0 schema.
Code reorganization, clean up of comments and debug output.
Change-Id: I1d830f8f9b90646da2da819488230b1702d09da5
=> layersvt: DevSim 1.2.5

scripts/vktrace_file_generator.py
The return result was initialized to an error code, but this
can cause problems for vkDestroyInstance which only allows success.
=> vkreplay: Set replayResult to VK_SUCCESS

layersvt/device_simulation.cpp, layersvt/linux/VkLayer_device_simulation.json, layersvt/windows/VkLayer_device_simulation.json
Set up GetPhysicalDeviceFeatures2(KHR) to make calls to the
corresponding vulkan function instead of simply calling the non-extended
vkGetPhysicalDeviceFeatures.
=> layersvt: Enable GetPhysicalDeviceFeatures2

vktrace/vktrace_layer/vktrace_lib_trace.cpp
This change fixes deadlock when tracing a multithread application by
making sure the locks in an API call are acquired in a consistent order.
=> vktrace: GH500, Fix deadlock in vktrace

tests/devsim_layer_test.sh
Tweaks to DevSim test script following VulkanTools using new KhronosGroup repos.
Test 1 (using vkjson) is commented out, since vkjson is not included in the submodules, and we want to move away from it anyway.
=> tests: Adjust DevSim test after repo reorg

CMakeLists.txt, via/CMakeLists.txt, vktrace/vktrace_replay/CMakeLists.txt, vktrace/vktrace_viewer/CMakeLists.txt
Fix searches for glslang / vulkan loader in an SDK when not specified on cmake command line
=> Tools: Better searches for loader and glslang

CMakeLists.txt, build-android/android-generate.bat, build-android/android-generate.sh, scripts/layer_factory_generator.py, scripts/tool_helper_file_generator.py, scripts/vt_genvk.py, vktrace/vktrace_common/CMakeLists.txt, vktrace/vktrace_layer/CMakeLists.txt, vktrace/vktrace_replay/CMakeLists.txt, vktrace/vktrace_trace/CMakeLists.txt, vktrace/vktrace_viewer/CMakeLists.txt
This change required updating the build files and scripts to account for moved registry files (reg.py, vk.xml, etc.). Also several fixes for registry changes and VVL repo updates.
Change-Id: I6476b1cb757005337f9c120027def058f48bfc6e
=> Update VulkanTools to header version 1.1.75

vktrace/vktrace_common/vktrace_trace_packet_utils.c, vktrace/vktrace_common/vktrace_trace_packet_utils.h, vktrace/vktrace_layer/vktrace_lib_trim.cpp, vktrace/vktrace_replay/vkreplay_seq.cpp, vktrace/vktrace_trace/vktrace_process.cpp
This change fixes the bug mentioned in
https://github.com/LunarG/VulkanTools/commit/3d3c8e59f67a5d6262200433e3780d133ec7e234#commitcomment-29121242
This change adds an alternate to vktrace_delete_trace_packet() that
does not try to leave the critical section which only initialized and
entered in vktrace_initialize_trace_packet_utils() and
vktrace_create_trace_packet(). It will help to safely delete trace
packet read via vktrace_read_trace_packet() without having problem of
leaving uninitialized/already left critical section.
=> vktrace: Fix unlock uninitialized/unlocked mutex lock

vktrace/vktrace_layer/vktrace_lib_trim_generate.cpp
vkCreateGraphicsPipelines lack pnext handling for trim, it cause generate
wrong trimmed trace file and crash when playback the trace file. The
change fix the error.
XCAP-952
Change-Id: Ic1c83c1509479ee0b26fad5eb8fb9cc12371eed6
=> vktrace: fix trim pnext handling error in vkCreateGraphicsPipelines

vktrace/vktrace_layer/vktrace_lib_pageguard.cpp, vktrace/vktrace_layer/vktrace_lib_trim.cpp
vktrace_delete_trace_packet() which will leave critical section
s_trace_lock is not always being called after CREATE_TRACE_PACKET
which will enter critical section s_trace_lock in:
1. vkFlushMappedMemoryRangesWithoutAPICall()
2. generateMapUnmap()
3. generate a vkMapMemory to recreate the persistently mapped buffers
in snapshot_state_tracker()
This will cause missing "leave critical section" or lock on an already
locked mutex lock.
This change fixed it by always call vktrace_delete_trace_packet() after
CREATE_TRACE_PACKET.
=> vktrace: Fix lock on locked mutex lock

vktrace/vktrace_common/vktrace_common.h, vktrace/vktrace_replay/vkreplay_vkdisplay.cpp, vktrace/vktrace_replay/vkreplay_vkdisplay.h, vktrace/vktrace_replay/vkreplay_vkreplay.cpp, vktrace/vktrace_replay/vkreplay_window.h
Make all use of the preprocessor defined token use the 'defined(X)'
syntax, instead of 'defined X'.
This is a follow up to comments made on #478.
=> vktrace: Use consistent syntax for defined

vktrace/vktrace_trace/vktrace.cpp, vktrace/vktrace_viewer/vktraceviewer_qtracefileloader.cpp
This change replaces the remaining fseek calls with Fseek which is a
follow up of PR #329 to make the code consistent.
=> vktrace: Use Fseek instead of fseek

scripts/vktrace_file_generator.py, vktrace/vktrace_common/vktrace_multiplatform.h, vktrace/vktrace_replay/vkreplay_vkreplay.h
Allow traces created on Windows to be replayed on Linux, and vise-versa.
Cross platform replay probably requires that GPUs be from the same vendor
and that the driver versions be close.
Tested by tracing a simple program (cube) on Linux and replaying on
Windows using nVidia GPUs, and vise-versa.  This worked, but many
configurations will not work because of inherent differences in
GPUs and driver implementations.
This used to work many commits ago, got broken sometime in the past,
and it has been fixed to work again.
=> vkreplay: Re-implement cross platform replay

tests/_vktracereplay.ps1, tests/vktracereplay.py, tests/vktracereplay.sh
Make vktrace/replay tests between Windows/Linux consistent. Added cube/trim tests to the python.
Remove redundant code from the bash and powershell scripts.
When the 'make install' functionality and pattern is established for testing, the bash and powershell scripts will be removed. Temporarily they are used to setup to gather up the dependencies for the tests on windows vs linux.
=> Consolidate and cleanup vktracereplay tests

vktrace/vktrace_replay/vkreplay_vkreplay.cpp, vktrace/vktrace_replay/vkreplay_vkreplay.h
If the trace/replay platforms are identical, don't translate the
queue family indices in trace packets when playing back those packets.
Change-Id: I791b11145519b43d90dc8318aa65e635c4730af1
=> vkreplay: Don't translate queue family indices

vktrace/vktrace_replay/vkreplay_vkdisplay.cpp
Reverts this commit:
https://github.com/LunarG/VulkanTools/commit/8664ed77230bafadc42c3495c4c9b962a8aed2dd
Due to "bad window size" error when vktrace/replay run in quick succession and preventing tests from passing.
=> Revert "synchronize window sizes on Linux"

vktrace/vktrace_layer/vktrace_lib_trim.cpp
This change makes the use of TRIM_USE_ORDERED_IMAGE_CREATION
consistent in vktrace.
Previously it was used in two ways:
1. #if TRIM_USE_ORDERED_IMAGE_CREATION
2. #if defined(TRIM_USE_ORDERED_IMAGE_CREATION)
Now it is used in a consistent way:
1. #if TRIM_USE_ORDERED_IMAGE_CREATION
Because TRIM_USE_ORDERED_IMAGE_CREATION is defined as 1 by default. If
the allowed value of TRIM_USE_ORDERED_IMAGE_CREATION is either 1 or 0,
then only "#if TRIM_USE_ORDERED_IMAGE_CREATION" will work as expected
when TRIM_USE_ORDERED_IMAGE_CREATION is defined as 0.
=> vktrace: Fix inconsistent use of macro in trim

vktrace/vktrace_layer/vktrace_lib_trim.cpp
There's an error in trim saving data to staging buffer if the image is
a 3d image. It cause the trimmed trace file playback missing objects in
image. The change fix the problem.
XCAP-1019
Change-Id: I3f6bded038830aa890c2ac7ff8e248ebfb385130
=> vktrace: Fix error in trim 3d image handling

vktrace/vktrace_layer/vktrace_lib_helpers.h
Also fix vktrace header to take into account that vk_layer.h
no longer includes vk_layer_dispatch_table.h.
This change required coordination between Vulkan-Loader and
Vulkan-ValidationLayers, and so the V-VL submodule needed updating.
=> build: Update V-VL submodule

vktrace/vktrace_common/vktrace_platform.c
The existing AndroidSetEnv() is not able to clean up an env when the val
parameter of AndroidSetEnv() is set to "" which makes len_val to be 0.
This change fixes this issue by always add quotes around val parameter.
e.g. For a call like AndroidSetEnv("key", "") trying to clean up "key"
environment variable, it will execute command 'setprop key ""' which
works as expected instead of 'setprop key'.
=> vktrace: Fix env clean up issue in AndroidSetEnv

layersvt/screenshot.cpp
This change drops the earlier swapchain info from swapchain map when
there's a new swapchain being created with the same handle.
It makes screenshot has correct resolution in following condition:
* Swapchain#1 is created with Handle#1 and Resolution#1
* Swapchain#1 is destroyed
* Swapchain#2 is created with Handle#1 (reused handle) and Resolution#2
* Screenshot#1 is taken.
Screenshot#1 will have Resolution#1 without this fix and it will have
the expected Resolution#2 with this fix.
=> layersvt: Fix incorrect resolution in screenshot

scripts/vktrace_file_generator.py, vktrace/vktrace_replay/vkreplay_vkreplay.cpp
Some API calls introduced in Vulkan 1.1 did not modify the pNext
field in some structures when tracing, and did not translate the
pNext field when replaying.
=> vktrace: Add pNext processing to some api calls

vktrace/vktrace_layer/vktrace_lib_trace.cpp
Some title hang randomly when capture with trim, the reason
is no lock/unlock protection for trim transition map access
in image and buffer handling of vkQueueSubmit, the change
fix the problem.
XCAP-952
Change-Id: If24750e5eb562503a24985cade531a9804cd1335
=> vktrace: add lock/unlock to trim transition handling

vktrace/vktrace_replay/CMakeLists.txt, vktrace/vktrace_replay/vkreplay_vkdisplay_wayland.cpp, vktrace/vktrace_replay/vkreplay_vkdisplay_xcb.cpp, vktrace/vktrace_viewer/main.cpp, vktrace/vktrace_viewer/vktraceviewer.cpp, vktrace/vktrace_viewer/vktraceviewer.h, vktrace/vktrace_viewer/vktraceviewer_QReplayWidget.h, vktrace/vktrace_viewer/vktraceviewer_QReplayWorker.cpp, vktrace/vktrace_viewer/vktraceviewer_QReplayWorker.h
Fixed incompatibilities between XLib and QT for vktraceviewer, now that all WSIs are included in the build.
Added headers to new cpp files and cleaned up CMake.
=> Fix compiler errors with vktraceviewer and new WSI selection

vktrace/vktrace_replay/vkreplay_vkdisplay_xcb.cpp
If vkreplay fails to establish a connection to the X server for whatever reason it will currently crash with a segmentation fault without providing the user with any indication as to the cause. With this change, it will check immediately whether the connection was established successfully and if not, terminate with a more informative error message.
=> vkreplay: terminate early if xcb_connect fails

vktrace/vktrace_replay/vkreplay_vkdisplay_xcb.cpp
A commit modifying xcb was reverted in trunk but was not
succesfully merged into the WSI overhaul.
Change-Id: I68879abd75c1cdeabebe0123664dd20e36e4ae35
Not having this change reverted was causing more "bad window size, aborting" errors
=> vktrace: Fix bad merge of e110564 revert commit

vktrace/vktrace_replay/vkreplay_vkreplay.cpp
A cpp directive to not compile wsi selection code on Windows
was missing.
=> vkreplay: fix crash in vkreplay startup on Windows

vktrace/vktrace_layer/vktrace_lib_trim.cpp, vktrace/vktrace_layer/vktrace_lib_trim_generate.cpp
This is a follow up of #497
Whenever ROUNDUP_TO_4 is used, need to make sure that it is used to
round up the size of packet elements.
Issue:
Currently trimmed trace file has vkMapMemory being recorded with
memory size ROUNDUP_TO_4 which may cause "mapped memory size +
mapped memory offset" greater than "allocated memory size".
Fix:
This change removes ROUNDUP_TO_4 from memory size in vkMapMemory.
=> vktrace: Fix mapped memory size incorrect issue in trim

vktrace/vktrace_layer/vktrace_lib_trace.cpp
when starting to trim, trim may need to copy the image out to write its
data to trimmed trace file. By doc, image for which we can copy out must
have been created with VK_IMAGE_USAGE_TRANSFER_SRC_BIT usage flag. The
change add the flag to image.
XCAP-952
Change-Id: I332b0315a581d2765bd8ba8756e6536ba8e0b7db
=> vktrace: add TRANSFER_SRC usage for trim when create image

scripts/vktrace_file_generator.py
Two functions missing support in the process of tracking image memory
requirement in trim: vkGetImageMemoryRequirements2 and
vkGetImageMemoryRequirements2KHR, the change fix the error.
XCAP-952
Change-Id: Iedf59084a06f22588fda91d90a1c79cfd6e754a5
=> vktrace: fix error for tracking image memory requirement in trim

layersvt/screenshot.cpp
This change calls writePPM before the real vkQueuePresentKHR being
called.  Because the swapchain image (after vkQueuePresentKHR is
called) is owned at some point in time by the presentation engine which
might do things to the image like zapping memory away.
This change also makes sure everything which could affect the swapchain
image being captured has has completed before capturing it using
VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT in pipeline barrier for the
swapchain image's image layout transition.
So now the process of taking screenshot is:
1. Wait on bottom_of_pipe to complete
2. Transition the image from present_src into transfer_src
3. Copy/dump the content out
4. Transition the image back into present_src
5. Call vkQueuePresentKHR as intended/intercepted
=> layersvt: Fix incorrect process of taking screenshots

tests/vktracereplay.py
Subprocess executions that returned a nonzero exit status
were throwing exceptions, handle these to print readable
error messages.
Change-Id: I165eb84ccf8c2b0b6274d31637c7de1fd4ba57c5
=> tests: vktracereplay.py handle nonzero exits

tests/trace_positive_validation.ps1
With Vulkan-ValidationLayers no longer a submodule, this path needs to change
=> tests: Fix path to validation layer test

tests/trace_positive_validation.ps1
Tests are failing trace / replay.  ExternalSemaphore is pretty much expected to fail, but some clever code could probably fix CreateGraphicsPipelineWithIgnoredPointers - issue submitted
=> tests: Add more tests to positive_validation black list

BUILD.md
Package libxcb-randr0-dev was required to build VulkanTools on my Ubuntu 18.04 machine.
=> Add libxcb-randr0-dev dependency to BUILD.md

vktrace/vktrace_replay/vkreplay_main.cpp
This change fixes FPS calculation when loop start frame "-lsf" is
greater than 0.
Issue:
The current printed FPS and time consuming info are calculated from
frame 0 which is inconsistent with the printed frame count and frame
range info when loops start frame is greater than 0.
e.g. X fps, Y seconds, 9 frames, 1 loop, framerange 2-10
X fps and Y seconds are caclulated from frame 0 to 10 (11 frames)
instead of frame 2 to 10 (9 frames)
Fix:
Reset start_time in the loopStartFrame in the first loop when
loopStartFrame is not 0.
=> vkreplay: Fix FPS calculation

vktrace/vktrace_common/vktrace_trace_packet_utils.c
This change adds VK_STRUCTURE_TYPE_PRESENT_TIMES_INFO_GOOGLE
to vktrace_add_pnext_structs_to_trace_packet() and
vktrace_interpret_pnext_pointers() to make vktrace and vkreplay support
VkPresentTimesInfoGOOGLE struct being pointed by pPresentInfo->pNext in
vkQueuePresentKHR().
=> vktrace: Support VkPresentTimesInfoGOOGLE in pNext

build-android/android-generate.sh
This change fixes an error when copying files from generate/include to
Vulkan Validation Layer directory.  Because ${LVL_BASE} is absolute
path.
=> vktrace: Fix a typo in android-generate.sh

layersvt/screenshot.cpp
This change fixes two access mask issues in screenshot layer:
1. The pipeline barrier which used to transition from present layout
for swapchain image should use VK_ACCESS_MEMORY_WRITE_BIT as
srcAccessMask to make sure all writes that are performed by entities
known to the Vulkan device are made available before read happens.
2. The pipeline barrier which used to transition a dest layout to
general layout should have dstAccessMask for CPU to read memory.
=> layersvt: Fix access mask in screenshot layer

vktrace/vktrace_layer/vktrace_lib_trace.cpp, vktrace/vktrace_layer/vktrace_lib_trim.cpp, vktrace/vktrace_layer/vktrace_lib_trim_statetracker.h
Add ImageType to track info, use this info when copying
1D/2D image in trim to fix an error which may cause depth
or height be wrongly set to zero.
XCAP-1019
Change-Id: I0034f5e0cf77668c3f74d0f11ec5f743f1976603
=> vktrace: fix error in copying 1D/2D image

vktrace/vktrace_layer/vktrace_lib_trace.cpp, vktrace/vktrace_layer/vktrace_lib_trim.cpp
The vktrace layer can sometimes create new dispatchable
vulkan objects, specifically VkCommandBuffers and VkQueues.
As per the loader's documentation, if this is done within a
layer it is the layer's responsibility to assign the
dispatch table for the object as this is normally done in
the top level trampoline function which is bypassed in this
case.
However, the vktrace layer currently does not do so. This can
result in problems if it is used on top of other layers. For
example, if the validation layers are enabled and an application
is traced with the trim option it causes a segmentation fault.
Hence, this change ensures the dispatch table is correctly
assigned for these objects.
=> vktrace: assign dispatch table for created objects

via/CMakeLists.txt, via/via_system.cpp, via/via_system_linux.cpp
Update the warning level on the build of VIA to match that of the
SDK and then fix the warnings that appeared.
=> via: Fix gcc 8 warnings

scripts/vktrace_file_generator.py, vktrace/vktrace_layer/vktrace_lib_trace.cpp, vktrace/vktrace_layer/vktrace_lib_trim.cpp, vktrace/vktrace_layer/vktrace_lib_trim.h
trim need vkGetImageSubresourceLayout when copy image to staging buffer,
but it's not valid usage if the image created without linear tiling mode.
it cause image difference when playback trimmed trace file for some title.
The change fix the problem.
VKTRACE-13
Change-Id: I52cbc7cb1503aa0258097873afcd2238adea4ba9
=> vktrace: fix trim copy image error for optimal tiling mode

vktrace/vktrace_layer/vktrace_lib_trace.cpp, vktrace/vktrace_layer/vktrace_lib_trim.cpp, vktrace/vktrace_layer/vktrace_lib_trim.h, vktrace/vktrace_layer/vktrace_lib_trim_statetracker.cpp, vktrace/vktrace_layer/vktrace_lib_trim_statetracker.h
Adding track info and corresponding handling for DescriptorUpdateTemplate,
the change fix command queue submission fail for some title.
VKTRACE-13
Change-Id: I1a0d6453f53abb39ecda6b066744a99c1f871009
=> vktrace: add support in trim for create and destroy DescriptorUpdateTemplate

vktrace/vktrace_replay/vkreplay_vkreplay.cpp
This change fixes:
1. allocateInfo is constructed but not used in
manually_replay_vkAllocateDescriptorSets().
2. memory allocation is needed to store the retrieved descriptor sets.
=> vkreplay: Fix a typo in vkAllocateDescriptorSets

vktrace/vktrace_layer/vktrace_lib_trace.cpp
Currently, the trace packet size for vkGetPhysicalDeviceQueueFamilyProperties2KHR
only includes the size of a single result structure, however the function can
return an array of multiple structures. This results in a potentially corrupted
trace file. The packet size needs to be computed to accommodate the full array of
structures.
=> vktrace: compute correct packet size for vkGetPhysicalDeviceQueueFamilyProperties2KHR

via/via_system.cpp
The disable variable relied on an uninitiailized variable which
should have been removed.
=> via: #650 - Fix layer disable var

scripts/api_dump_generator.py, scripts/tool_helper_file_generator.py, scripts/vktrace_file_generator.py
The 1.1.90 header introduced the use of "\textrm" in `vk.xml`, requiring
changes to:
- scripts/api_dump_generator.py
- scripts/tool_helper_file_generator.py
- scripts/vktrace_file_generator.py
=> scripts: Extend scope of LaTeX handling

vktrace/vktrace_replay/vkreplay_vkreplay.cpp
This change resets pImageIndex in vkCreateSwapchainKHR to make replay work
when there are multiple vkCreateSwapchainKHR API calls being replayed.
=> vkreplay: Handle muliple swapchains in trace file

vktrace/vktrace_layer/vktrace_lib_trim.cpp, vktrace/vktrace_layer/vktrace_lib_trim_statetracker.cpp, vktrace/vktrace_layer/vktrace_lib_trim_statetracker.h
This change records and keeps the creation order of instances and
swapchains in trim to make the trimmed trace file work when there are
multiple instances and swapchains.
It solves remap failures which are caused by the incorrect order of
instance creation or swapchain creation when replaying a trimmed trace
file.
=> vktrace: Keep the order of instance and swapchain creation in trim

scripts/vktrace_file_generator.py, vktrace/vktrace_replay/vkreplay_vkreplay.cpp
The prior commit, ad30962a4b4dad044adfce38643f14ff4a797aad, caused
a failure in LunarG's internal CI tests on Windows.
The failure was in a replay/trace/replay of Dota2, and in a replay
of an older trace of vkQuake.
The errors introduced by the previous commit are:
vkreplay error: Return value VK_ERROR_OUT_OF_HOST_MEMORY from API call (vkQueuePresentKHR) does not match return value from trace file VK_SUCCESS.
vkreplay error: Failed to replay packet_id 165, with global_packet_index 2686.
vkreplay error: Return value VK_ERROR_VALIDATION_FAILED_EXT from API call (vkAcquireNextImageKHR) does not match return value from trace file VK_SUCCESS.
vkreplay error: Failed to replay packet_id 164, with global_packet_index 2689.
vkreplay error: API call vkQueueSubmit returned VK_ERROR_DEVICE_LOST. …
=> vkreplay: back out previous commit

via/CMakeLists-SDK.txt, via/CMakeLists.txt, via/README.md
Rename the VIA executable from "via" to "vkvia" since we're going
to be installing this globally on Linux systems.
=> via: Rename executable/html to vkvia

vktrace/vktrace_replay/vkreplay_main.cpp, vktrace/vktrace_replay/vkreplay_main.h, vktrace/vktrace_replay/vkreplay_vkreplay.cpp
This change preloads portability table before replaying to eliminate
the performance noise caused by file I/O (fseek/fread in
vkAllocateMemory when using portability table) when calculating FPS.
=> vkreplay: Preload portability table

vktrace/vktrace_replay/vkreplay_vkreplay.cpp
This change adds the missing VKTRACE_DELETE to the memory allocated
using VKTRACE_NEW_ARRAY.
It also adds the returned VkDisplayKHR to VkDisplayKHR map.
=> vkreplay: Fix vkGetDisplayPlaneSupportedDisplaysKHR

layersvt/device_simulation.cpp
Latest clang fires an error on this.
=> Remove unused variable from device_simulation layer

vktrace/vktrace_layer/vktrace_lib_trace.cpp
This change replaces %d with PRIu64 to print uint64_t variable's value
correctly on 32-bit system.
=> vktrace: Fix print in trim for uint64_t variables

scripts/vktrace_file_generator.py
This change adds rm_from_*_map calls to auto generated vkreplay code.  Previously only rm_from_devices_map and rm_from_swapchainkhrs_map were added to the auto generated code of vkreplay.
=> vkreplay: Remove deleted object from obj mapper

layersvt/device_simulation.md, via/README.md, vktrace/vktrace.md
device_simulation.md:
- fully-automated => fully automated
- records should be reviewed to determine that its capabilities => records should be reviewed to determine that their capabilities
README.md:
- setup => set up (when used as a verb)
- Dialog box pop's up => Dialog box pops up
vktrace.md:
- post processing => post-processing
=> Minor grammar and consistency improvements

scripts/vktrace_file_generator.py, vktrace/vktrace_replay/vkreplay_vkreplay.cpp, vktrace/vktrace_replay/vkreplay_vkreplay.h
When replaying a vkCreateSampler api call, traverse the pNext list
in pCreateInfo, looking for VkSamplerYcbcrConversionInfo structs
and remapping the pYcbcrConversion handles.
Change-Id: I9c8a3c505119d140ca568b9a52a793174d7ec536
=> vkreplay: Add processing of pNext structs to vkCreateSampler

vktrace/vktrace_replay/vkreplay_vkreplay.cpp
This change adds search for device local memory type in getMemoryTypeIdx().
The search for device local memory type is needed because it is possible to have VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT bit set in a memory type according to the description for vkGetPhysicalDeviceMemoryProperties in Vulkan Spec 1.1.73:
> There must be at least one memory type with both the VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT and
> VK_MEMORY_PROPERTY_HOST_COHERENT_BIT bits set in its propertyFlags. There must be at least one
> memory type with the VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT bit set in its propertyFlags.
=> vkreplay: Add device local memory type in getMemoryTypeIdx

vktrace/vktrace_replay/vkreplay_vkreplay.cpp, vktrace/vktrace_replay/vkreplay_vkreplay.h
This change makes vkreplay have better compatibility when the replay
platform has different memory requirement for optimal tiling image
than the trace platform which cannot be calculated using alignment.
vkreplay will skip vkAllocateMemory if the memory allocation is only
for optimal tiling image(s) and do memory allocation in
vkBindImageMemory (and memory free in vkDestroyImage) when
CompatibilityMode is enabled.
=> vkreplay: Optimal image memory allocation enhancement in compatibility mode

layersvt/api_dump.h, scripts/api_dump_generator.py
This change makes api_dump layer to dump shader in hex format which is
compatible with xxd.
With this change, user is able to copy out the shader hex data to a
file <shader_hex_file> and convert it back to binary using:
xxd -r -p <shader_hex_file>
=> layersvt: Shader dump in hex format

scripts/vktrace_file_generator.py, vktrace/vktrace_replay/vkreplay_vkreplay.cpp, vktrace/vktrace_replay/vkreplay_vkreplay.h
This change releases (not freed) allocated memories and (not destroyed)
vulkan objects before quit replay.
This will help to make valgrind happy when using vkreplay on a debug version GPU driver.
=> vkreplay: Release vulkan objects before quit replay

vktrace/vktrace_replay/vkreplay_main.cpp
This change adds the missing vktrace_free(pFileHeader) calls in vkreplay_main().
=> vkreplay: Add missing free for pFileHeader in vkreplay_main()

via/via_system_linux.cpp
We failed to set the 'found' variable resulting in an incorrect
statement that no runtimes were found even though we had just
printed a statement indicating we found a runtime.
Change-Id: Id75d39df6c7a40ce44929f14a46f4961a6b17ea6
=> via: Fix runtime output on Linux

vktrace/vktrace_replay/vkreplay_vkreplay.cpp
This change makes vkreplay always use playable device features in
compatibility mode.
=> vkreplay: Always use playable device features

scripts/vktrace_file_generator.py, vktrace/vktrace_replay/vkreplay_vkreplay.h
This change makes vkreplay to skip replaying the API calls with failed
results recorded in trace file.  The expected to fail API calls in
trace file will not be replayed in case those API calls may success on
replay platform.
=> vkreplay: Skip replaying failed api calls in trace

vktrace/vktrace.md, vktrace/vktrace_common/vktrace_common.h, vktrace/vktrace_layer/vktrace_lib_trim.cpp, vktrace/vktrace_trace/vktrace.cpp, vktrace/vktrace_trace/vktrace.h
Changes include:
- splitting write_all_referenced_object_calls()
functions into multiple smaller functions based on the
recreated objects.
- change staging buffers creation in the snapshot_state_tracker()
function to create images and buffers in batch in order to have
unique buffer and memory handles which will be reused in recreate
images and buffers  in the  write_all_referenced_object_calls()
function.
- batch vkCmd into command buffers when recrete images and
buffers resources. The batch number count (g_trimMaxBatchCmdCount)
is limited by the device memory allocation count limit.
VKTRACE-83
Change-Id: Ibd779a3baa534f31729467c25aa0ac2aefab2217
=> vktrace: Optimization vktrace by reducing the number of command buffers execution in the trim

scripts/vktrace_file_generator.py, vktrace/vktrace.md, vktrace/vktrace_common/vktrace_common.h, vktrace/vktrace_layer/vktrace_lib_trace.cpp, vktrace/vktrace_layer/vktrace_lib_trim.cpp, vktrace/vktrace_layer/vktrace_lib_trim.h, vktrace/vktrace_trace/vktrace.cpp, vktrace/vktrace_trace/vktrace.h
This changes add locking of API calls during trace. 'tl' , 'TraceLock' option is added to always turn on/off the locking of API calls. This avoids race conditions and remaps error during trim playback, with slight performance loss. By default, locking is enabled when trim enabled.
It is respond to pull request [#675](https://github.com/LunarG/VulkanTools/pull/675)
=> vktrace: Add mutex lock for all manual and autogenerated hooked API

tests/vktracereplay.py
glslang and vkcube are no longer built as part of the VulkanTools tests since
commit b270c0024bafbc91e47d81b4bde2ddc38f391ea5.  This removes the explicit
vkcube testing because vkcube isn't present.  Trace testing still occurs.
=> vktracereplay: eliminate vkcube testing by default

.appveyor.yml
This will allow us to check our build logs to determine the exact
CMake version used with that build.
=> add cmake version reporting to appveyor build

tests/apidump_test.sh
Modifid apidump test.sh so that it expects a smaller number
of lines containing VK_FEATURE_COUNT when doing an apidump
of vulkaninfo. vulkaninfo was recently modified to only
query supported formats, causing this test to fail
because much fewer lines containing VK_FEATURE_COUNT
were output by vulkaninfo/apidump.
Change-Id: Ib34a9331632cdb952cfecf9616785393e4d2f36a
=> tests: reduce expected count of vk_format_feature

layersvt/screenshot_layer.md
There was a paragraph starting with "Checks include:" that has
nothing to do with screenshots - it looks like it was left over
from validation layer documentation.
=> screenshot documentation fix

tests/devsim_layer_test.sh
Doing this temporarily, until either golden image can be updated or
vulkaninfo is added to VulkanTools/tests so as to avoid changes to
Vulkan-Tools/vulkaninfo affecting VulkanTools tests.
Change-Id: Ic46e7909e729afc071d4730b3dfa704a7f756eae
=> tests: disable devsim test that depends on vulkaninfo output

vktrace/vktrace.md, vktrace/vktrace_dump/vktracedump.md
Removed vktracedump documentation from vktrace.md because vktrace.md
is included in the Vulkan SDK, but vktracedump is not in the SDK.
Moved the vktracedump documentation to vktrace/vktrace_dump/vktracedump.md
Change-Id: I892bf2cf39ca3d278bfeff393f0d2880ded50921
=> vktrace doc: remove vktracedump from vktrace.md

vktrace/vktrace_replay/vkreplay_main.cpp
Change-Id: I1d735aa33ef5a3bfd119513fa08a7b71719c631e
=> vkreplay: remove print of framerange when trace has 0 frames

layersvt/api_dump.h, layersvt/api_dump_layer.md
Sometimes, it's easier to modify settings using
environment variables instead of using the settings
file.  So, add support for some of the primary
API Dump layer settings using environment variables.
Those settings environment variables are:
* APIDUMP_LOG_FILENAME  - Set the output filename.  If set, also
automatically retargets the output to this
file.
* APIDUMP_OUTPUT_FORMAT - Set the output format to either "html" or
"text".
* APIDUMP_DETAILED      - Boolean to enable the detailed output
* APIDUMP_FLUSH         - Boolean to disable flushing after every write
* APIDUMP_NO_ADDR       - Boolean to disable address outputs in the
API Dump output file.
Change-Id: I110609c48fb615d0eeae623c7de3176c65bd935d
=> api_dump: Add Environment variable support

.travis.yml
This makes it easier to track cmake versions should Travis change suddenly
=> add reporting of cmake version to travis build

vktrace/vktrace_replay/CMakeLists.txt, vktrace/vktrace_replay/vkreplay_vkdisplay.cpp
Most of the changes are in the `CMakeFiles.txt` file. One change is in `vkreplay_vkdisplay.cpp` where the behavior is the following: if the user passes "wayland" as the "ds" argument, the following error message is emitted: "vktrace not built with wayland support".
I have not changed the help text in `vkreplay_main.cpp` nor the logic for picking the
default server if it is not set by the user. Therefore if wayland is detected at runtime but VulkanTools was built with `-DBUILD_WSI_WAYLAND_SUPPORT=OFF`, there will be the following error message "vkreplay error: vktrace not built with wayland support."
I tested it with:
`vktrace -o /tmp/mytracefile -p vkcubepp`
followed by:
`vkreplay -o /tmp/mytracefile -ds wayland`
`vkreplay error: vktrace not built with wayland support.`
`vkreplay -o …
=> Fixed missing guards when -DBUILD_WSI_WAYLAND_SUPPORT=OFF

layersvt/device_simulation.cpp, vktrace/vktrace_common/CMakeLists.txt
On CentOS6.8 with a local build of g++ 6.4.0 (the default g++ version on CentOS6.8 is 4.4.7), the build fails with undefined symbol PRIu64 and PRIu32 at compile time and undefined reference to 'clock_gettime' at link time.
Fixed undefined symbols PRIu64/PRIu32 by including `<cinttypes>` instead of
`<inttypes.h>`. (a less elegant solution would be to add `#define __STDC_FORMAT_MACROS` prior to include `<inttypes.h>`). `layersvt/device_simulation.cpp` is a C++ file and as such should include C header files that way anyway (note that this file includes other C header files the wrong way: `<stdarg.h>`, `<stdio.h>`, `<stdlib.h>` and `<string.h>` instead of `<cstdarg>`, `<cstdio>`, `<cstdlib>` and `<cstring>` respectively. I have not fixed these inclusions in the current patch as I want to keep …
=> Fixed undefined symbols PRIu64/PRIu32 and reference to clock_gettime

scripts/common_codegen.py, scripts/layer_factory_generator.py
The addition of the `VK_EXT_metal_surface` extension required the
addition of "metal" to the platform dictionary. This extension also
introduced the `vkGetImageViewHandleNVX` function which has a return
type of `uint32_t`. This return type was not previously defined in
`layer_factory_generator.py`'s return map.
Modified:
- `scripts/common_codegen.py`
- `scripts/layer_factory_generator.py`
=> scripts: Modify scripts for 102 header update

vktrace/vktrace_common/vktrace_process.c
Kill all processes in the process group when the program
specified by the -p option cannot be executed. This prevents
the vktrace command from simply hanging when the program file
doesn't exist.
Change-Id: Iffc5cd7f864c5577b97e856d75dddc4a274077ba
=> vktrace: handle error when exec of program fails

vktrace/vktrace_common/vktrace_trace_packet_utils.c, vktrace/vktrace_common/vktrace_trace_packet_utils.h, vktrace/vktrace_replay/vkreplay_main.cpp, vktrace/vktrace_replay/vkreplay_vkreplay.cpp
Code was already in place to enforce this, but the recently
added code to pre-read portability packets crashes when
cross-playing, so the code to enforce it was not executed.
Moved the code to check for 32/64 to earlier in the replay.
Also added enforcing of not allowing replay if the Endianess of
the trace file and replay system do not match.
Change-Id: I018a806ac9cea68ba35c572e4a4177170cf4a73b
=> vkreplay: don't allow 32-bit trace replay on 64-bit replayer

layersvt/api_dump.h, layersvt/api_dump_layer.md
The Android property names used by the api_dump layer have lengths that exceed the 32 character limit present with Android N. This change reduces the length of the property name by removing the 'vulkan.layer_opts' portion of the property name, such that:
>debug.vulkan.layer_opts.apidump_log_filename
becomes:
>debug.apidump_log_filename
=> api_dump: Shorten Android Property Names

scripts/vktrace_file_generator.py
which is caused by infinite loop condition of
vkGetQueryPoolResults, the non-error return code
include VK_NOT_READY, so this change add VK_NOT_READY
to the loop condition to prevent the hang.
Also, add parentheses around the conditions for clear
logic.
Change-Id: Id311ab97c051a29f4da501d48c72a36cb135b164
=> vkreplay: Some title hang during trim playback

layer_factory/CMakeLists.txt
build/layers/staging-json dir was not previously created, resulting
in build failure.  Not sure why sometimes it used to work.
Change-Id: I8712d1e29d4ca14e46cdfab6cc42389c9420ea68
=> cmake: Add cmd to create layers/staging-json dir

vktrace/vktrace_common/vktrace_trace_packet_utils.c, vktrace/vktrace_common/vktrace_trace_packet_utils.h
get_endianess_string was declared as returning an uint64_t, but
it returns a pointer to a const char. Changed function definition
declaration to indicate it returns a const char *.
Also fixed the value returned when endianess is unknown - it was
misspelled.
Change-Id: Id27dc2da68660542073c36718c3b34c767b816e1
=> vkreplay: fix type returned by get_endianess_string

layersvt/api_dump.h
Causes the output threadID to be UINT64_MAX in some cases.
Change-Id: I9ab7397c7f1423c9ff8826ad7ee4543b075cb160
=> Fixed comparison of threadID against wrong initial value. UINT32 -> UINT64

layer_factory/CMakeLists.txt
The copy was redundant, and sometimes it would leave the wrong
version of the json in the destination.
Change-Id: I4602869eaa92762695d25074bf1349b7f65e43b2
=> layerfactory: remove copy of intermediate json to final dest

vktrace/vktrace_replay/vkreplay_vkreplay.cpp
pNext of VkSamplerCreateInfo may point to a struct of extension other
than sampler YCBCR conversion, it cause playback hang problem. The change
fix the issue.
VKTRACE-97
Change-Id: I603548bbaddcf42877c34a8a98f7d2dec7920e65
=> vkreplay: fix an error in pNext handling

scripts/vktrace_file_generator.py, vktrace/vktrace_common/vktrace_trace_packet_utils.c, vktrace/vktrace_common/vktrace_trace_packet_utils.h, vktrace/vktrace_replay/vkreplay_vkreplay.cpp
Added a front end function to vktrace_interpret_pnext_pointers.
Renamed vktrace_interpret_pnext_pointers to vkreplay_interpret_pnext_pointers.
This is in preparation for an upcoming commit to add more general remapping of
handles in pnext structures during replay.
Change-Id: Id461bbc73e6a8b410771a22d1179fff39f36c7c2
=> vktrace: add front end to vktrace_interpret_pnext_pointers

vktrace/vktrace_layer/vktrace_lib_pageguard.cpp
Add process to make sure pageguard is cleared because in multi-thread
environment there's possibility that pageguard be re-armed during
pageguard be triggered this time to current location. If pageguard be
rearmed, the following sync between real mapped memory and shadow mapped
memory will cause deadlock.
VKTRACE-97
Change-Id: If886592ee1200d4f5d1bb2b9cda4f38fa4fd4631
=> vktrace: make page guard be cleared during exception handler

layersvt/device_simulation.cpp
This is not an error for the the main devsim customer (LVTs) but the informational message prints "ERROR" in the LVT logs, adding some unnecessary confusion.
=> Change devsim apiversion error msg to debug msg

vkconfig/active_layers_widget.cpp, vkconfig/active_layers_widget.h, vkconfig/override_settings.cpp, vkconfig/override_settings.h, vkconfig/vkconfig.cpp
This change goes with KhronosGroup/Vulkan-Loader#168. These two changes combine to make the override behavior more flexible. Now, users can enable, disable, or leave individual layers alone. This is reflected with another list in vkconfig, where a user can add disabled layers.
=> Update vkconfig to use a whitelist and blacklist for enabling layers

layersvt/api_dump.h, scripts/api_dump_generator.py, scripts/common_codegen.py, scripts/layer_factory_generator.py, scripts/tool_helper_file_generator.py, scripts/vktrace_file_generator.py, scripts/vt_genvk.py, vktrace/vktrace_common/vktrace_multiplatform.h
Changes:
- Integrate upstream script changes: We have to plumb-through the new
conventions object to continue using the makeCParamDecl utility function
- Add GGP to available platforms
- Workarounds for missing platform guards
Note: Vulkan-ValidationLayers 106 known-good update requires the
script changes in this commit to build successfully
Modified:
- `layersvt/api_dump.h`
- `scripts/api_dump_generator.py`
- `scripts/common_codegen.py`
- `scripts/layer_factory_generator.py`
- `scripts/tool_helper_file_generator.py`
- `scripts/vktrace_file_generator.py`
- `scripts/vt_genvk.py`
- `vktrace/vktrace_common/vktrace_multiplatform.h`
Change-Id: Ib653c9fc3e804a02897917596914490ab843dc5b
=> scripts: Script modifications for 106 hdr

vktrace/vktrace_layer/vktrace_lib_trace.cpp
The sync operation in vkWaitForFences handling is only needed by Linux
platform, Windows side has similiar process in pageguard exception
handler and doesn't need the process. The change make related code
Linux only to avoid performance drop when capturing some title.
VKTRACE-97
Change-Id: I7b6ca6215917686c790dc515f912ba70b821aa9e
=> vktrace: remove vkWaitForFences sync for Windows platform

build-android/vktracereplay.sh
We found by accident that Android devices were often failing
trace testing, but the failure indication was not getting
back to the main script, so success was always reported on
Android.  This was only on 32-bit Android builds, because
extensive trace testing is only done on 32-bit builds (because
we have no 64-bit traces).
The tests were failing in one of several ways:
- Some traces simply did not replay on some devices, and produced
no image at all.
- Sometimes (sporadically) a screenshot image failed comparison
testing (because the image was imperceptibly different, but was
only being checked for being identical).
These changes have been made to both improve the testing and
to make it easier to triage failures:
- the script properly exits with a failure return code if the
test has …
=> android: improve trace testing

layersvt/screenshot.cpp
by not including inttypes.h in screenshot.cpp
I discovered this while trying to build the Vulkan SDK 1.1.106.0 on CentOS6. The following error was emitted:
In file included from .../include/vk_layer_utils.h:32:0,
from .../VulkanTools/layersvt/vk_layer_table.h:25,
from .../VulkanTools/layersvt/screenshot.cpp:42:
.../include/vk_layer_logging.h: In member function ‘std::string _debug_report_data::FormatHandle(uint64_t) const’:
.../include/vk_layer_logging.h:191:38: error: expected ‘)’ before ‘PRIxLEAST64’
sprintf(uint64_string, "0x%" PRIxLEAST64, h);
^~~~~~~~~~~
make[2]: *** [layersvt/CMakeFiles/VkLayer_screenshot.dir/screenshot.cpp.o] Error 1
There are 2 ways to fix this:
1. define macro __STDC_FORMAT_MACROS before including inttypes.h
2. just include cinttypes
What happen here is that …
=> Fix undefined PRIxLEAST64 on CentOS6 in vk_layer_logging.h

layersvt/screenshot.cpp
Fixes problem with gfxrecon replay of a Dawn Of War 3 trace.
The dispatch table being used was being keyed off of the queue
handle passed in to vkQueuePresentKHR. It would work because
the queue handle was the same as the device handle for a previously
destroyed device.
Changed code to figure the device associated with the passed in
queue handle and to then use that device's displatch table.
Change-Id: Id5be18f67c48a785623c266ed884af742c378aeb
=> screenshot: Use device to access correct dispatch table

scripts/vktrace_file_generator.py, vktrace/vktrace_layer/vktrace_lib_helpers.h, vktrace/vktrace_layer/vktrace_lib_pageguard.cpp, vktrace/vktrace_layer/vktrace_lib_trace.cpp, vktrace/vktrace_replay/vkreplay_vkreplay.cpp
1. Sometimes the memory is flushed with several ranges in one call, but
the pageguard data only need be copied once time.
2. Only the coherent memory need not be flushed in the special flush
memory call.
=> vktrace: Fix trace/replay issues for some unity-based games

build-android/vktracereplay.sh
Android tests are showing unreliable behavior when replaying
many vktrace traces; it seems the device doesn't always recognize
when an action has started.
I've added a couple of pauses as an experiment to try to get
the test to behave more like it were being driven by a human.
This seems to make at least some of the traces more reliable.
In addition, Android log files from the execution are now
saved for later examination in case of failure (or to ensure
that the device behaved as expected).
=> android: interactive pauses, save logs

scripts/vktrace_file_generator.py
Dota2 failed with invalid
VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MEMORY_BUDGET_PROPERTIES_EXT
structure during playback. Update the generator script
to include check for '2' pointer type when generating
the packet interpretation code for replay. This update fixed the
invalid pNext issue in vkGetPhysicalDeviceMemoryProperties2KHR call.
VKTRACE-119
Change-Id: Idc95ef679610fc386b6ed9fe3075b30aef010250
=> vkreplay: update vktrace_file_generator.py for new ext

vkconfig/macOS/Info.plist
Set "NSPrincipalClass" key as string "NSApplication", as detailed
in https://doc.qt.io/qt-5/highdpi.html
Tested on 2018 MacBook Pro 13 with MoltenVK on hidpi builtin LCD and 1080p TV
=> fix blurriness on MacOS in vkconfig

layersvt/api_dump.h, scripts/api_dump_generator.py
Previously, `api_dump_generator.py` did not support commands with
multiple require blocks.
This change is required to update the Validation Layers known good for the 108 headers.
=> scripts: Add multiple-require support to api_dump

BUILD.md
- Corrected grammar in the jsoncpp reference
- Fixed the `git clone` to correctly manage the submodules
(without this fix the instructions don't work)
=> doc: improve wording in BUILD.md

scripts/api_dump_generator.py
Core spec enums didn't print elements that were added by an extension.
Change-Id: I4b2cb4f7eb0cc3f3805386cd23de38898967deaf
=> api_dump: Fixed core enums not dumping extension elements

vkconfig/active_layers_widget.cpp
Fix the case where previously-enabled layers aren't shown as enabled in
Layer Settings after re-running vkconfig
Add emission of signal enableLayersUpdated in
ActiveLayersWidget::setEnabledLayers().
ActiveLayersWidget::setEnabledLayers() is called at initialization
to set the previously-saved enabled and disabled layer
lists and should update the layer settings widget by calling
LayerSettingsWidget::updateAvailableLayers().
=> vkconfig: update layer settings if enabled layers are set

vktrace/vktrace_layer/vktrace_lib_trace.cpp
Game such as Strange Brigade cannot be trimmed because
the trim crashed in vktraceGetDeviceProcAddr function
call which has duplicate mutex tracelock when it calls
another function vkGetDeviceProcAddr. This change
removes the duplicate mutex lock and ensure only one
mutex lock enabled during trim.
VKTRACE-122
Change-Id: I4401b4f9575480f867d4a0a61f433d84dca800c9
=> vktrace: trim not working due to duplicate mutex lock

scripts/vktrace_file_generator.py, vktrace/vktrace_common/vktrace_trace_packet_utils.c, vktrace/vktrace_layer/vktrace_lib_helpers.h, vktrace/vktrace_layer/vktrace_lib_trim.cpp
Add VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_BINDING_FLAGS_CREATE_INFO_EXT for vkCreateDescriptorSetLayout pNext handling and add check for valid map size before accessing the map.
=> vktrace: add new structure type for vkCreateDescriptorSetLayout pNext handling and fix trim exception.

via/via_system_linux.cpp
add loop over SDK explicit layer path dirs in PrintSystemSdkInfo
add 1.1.108 explicit layer path dir so vkvia succeeds on 1.1.108
via: break if SDK path found
Change-Id: Ic378d7c1f04646b96a2733337dd96cc0851f5484
=> via: allow vkvia to find SDK in 1.1.108

scripts/vktrace_file_generator.py, vktrace/vktrace_replay/vkreplay_vkreplay.cpp
Remove extra pNext process call as the process pNext already handled in the vktrace_vk_vk_packets.h due to previous fix to the header file generation script.
=> vkreplay: fix playback crash due to extra pNext process call

scripts/vktrace_file_generator.py, vktrace/vktrace.md, vktrace/vktrace_common/vktrace_common.h, vktrace/vktrace_layer/vktrace_lib_pageguard.cpp, vktrace/vktrace_layer/vktrace_lib_pageguard.h, vktrace/vktrace_layer/vktrace_lib_pageguardcapture.cpp, vktrace/vktrace_layer/vktrace_lib_pageguardcapture.h, vktrace/vktrace_layer/vktrace_lib_pageguardmappedmemory.cpp, vktrace/vktrace_layer/vktrace_lib_pageguardmappedmemory.h, vktrace/vktrace_layer/vktrace_lib_pagestatusarray.cpp, vktrace/vktrace_layer/vktrace_lib_pagestatusarray.h, vktrace/vktrace_layer/vktrace_lib_trace.cpp
The method uses Vulkan host memory extension and memory write watch to capture PMB data on Windows platform. Usage:  set VKTRACE_PMB_ENABLE=2 to enable  PMB capture with write watch detection on target application's PMB allocated with host memory extension.
=> Capturing PMB by using external host memory extension

scripts/api_dump_generator.py
The memoryType and memoryHeap members of VkPhysicalDeviceMemoryProperties will now
only dump valid elements, up to memoryTypeCount and memoryHeapCount values respectively.
Similar change for VkPhysicalDeviceGroupProperties's physicalDevices & physicalDeviceCount.
Before it would dump 16/32 entries, of which often only a handful were valid and useful.
Opted to add special case instead of modifying code-gen due to limited instances of this issue.
=> api_dump: Removed unecessary memory info

scripts/api_dump_generator.py
Several Vulkan Bitmasks have values that cover a range are
being dumped alongside the unique values. This change checks
for such values and will only dump them if the exact value was
given.
=> apidump: Fix bitmasks dumping non-unique flags

vktrace/vktrace_layer/vktrace_lib_pageguard.cpp, vktrace/vktrace_replay/vkreplay_vkreplay.cpp
The change add missing init process for an allocated memory, it cause wrong
data pointer generated in trace packet and playback crash. The change fix
the problem.
VKTRACE-135
Change-Id: I258d4d5d5eff10798c4e97ba28f890511f7f44f5
=> vktrace: fix error of generating invalid data pointer in trace packet

layer_factory/assistant_layer/interceptor_objects.h, layer_factory/assistant_layer/skip_get_call_warning.cpp, layer_factory/assistant_layer/skip_get_call_warning.h
resolves issue within tracking issue KhronosGroup/Vulkan-ValidationLayers#24 that states "Warn for skipping Get calls -- GetBufferMemoryRequirements, GetImageMemoryRequirements, etc."
Note: I may have missed a few "get call" warnings so feel free to suggest anything missing. At the very least, the architecture is setup to easily add more warnings in the future.
=> Camden gh24 skip get call check

vktrace/vktrace_layer/vktrace_lib_pageguardcapture.cpp, vktrace/vktrace_layer/vktrace_lib_pageguardmappedmemory.cpp, vktrace/vktrace_layer/vktrace_lib_pageguardmappedmemory.h
Mapped shadow memory start from a system page starting address is a basic
assumption in PMB capture code, but for PMB host memory capture, it's not
true any more, it cause the changed page status doesn't match the changed
page index and cause wrong write/read in trace file packet and sometimes
crash in capture. The change fix the problem.
VKTRACE-135
Change-Id: I3353632160f064efd06c498f615562e3ef1b22a3
=> vktrace: Fix an issue of PMB host memory capture

scripts/vktrace_file_generator.py, vktrace/vktrace_replay/vkreplay_vkreplay.cpp, vktrace/vktrace_replay/vkreplay_vkreplay.h
The two functions all need some special handling which is not included in
auto generated code. The change add them to manually replay functions.
VKTRACE-135
Change-Id: Iffe692e0a205b4e6094612b4d2b4630d262959e8
=> vktrace: add vkBindBufferMemory2, BindImageMemory2 playback function

vktrace/vktrace_replay/CMakeLists.txt, vktrace/vktrace_viewer/CMakeLists.txt
The RPATH will not be stripped if `make install` is ran when setting RPATH with linker flags. 
Using CMAKE_BUILD_RPATH to set RPATH to $ORIGIN will have RPATH set to $ORIGIN in the build directory, and the RPATH will be stripped if `make install` is ran.
=> vkreplay: Use CMAKE_BUILD_RPATH instead of setting linker flags

vktrace/vktrace_common/vktrace_trace_packet_utils.c
"%u" is a format reference to a 32-bit unsigned integer.
We're passing a uint64_t for formatting, which is unlikely
to work correctly.
"%ju" is a conversion for an intmax_t on both Windows and
Linux.  Casting the corresponding argument to this type
ensures that the format string and argument are in sync
regardless of how uint64_t is defined.
Change-Id: I92381b3b20d1c356fcf7b2df23834f9aaec03b8e
=> vktrace: fix type mismatch on error message

via/via_system.cpp
The location of vkcube for the Linux Tar SDK has changed
=> via: change location of vkcube for linux tar SDK

layersvt/api_dump.h, layersvt/api_dump_layer.md, layersvt/vk_layer_settings.txt, scripts/api_dump_generator.py, vkconfig/layer_info.json
Range is given either by a list of comma separated values or a
frame start, count, and optional interval separated by dashes.
A count of 0 will keep outputting frames after the start frame
is encountered. Enables selective logging, useful to ignore
irrelevant data.
Modified:
- `layersvt/api_dump_layer.md`
- `layersvt/api_dump.h`
- `scripts/api_dump_generator.py`
- `vkconfig/layer_info.json`
Change-Id: Icd9f22644e6e880a600fea10e73ac89073729681
=> api_dump: Only output frames within a given range

scripts/api_dump_generator.py
apidump will now dump pNext chains in the vkCreateInstance
and vkCreateDevice functions, which were previously dropped
due to the loader adding pNext values at the front of the
chain.
files changed:
scripts/api_dump_generator.py
Change-Id: I43fa3bd5fb0f3db4a5481dcfd29c6460c1357a14
=> apidump: pNext chain dump in device create info

layersvt/api_dump.h, layersvt/api_dump_layer.md, layersvt/vk_layer_settings.txt, scripts/api_dump_generator.py, vkconfig/layer_info.json
apidump will now show the time a function was called since start
in microseconds. This is useful to determine which functions are
taking significant time to execute.
Added the VK_APIDUMP_TIMESTAMP environmental variable and the
lunarg_api_dump.show_timestamp setting to the api_dump settings file
changed files:
layersvt/api_dump.h
layersvt/api_dump_layer.md
layersvt/vk_layer_settings.txt
scripts/api_dump_generator.py
vkconfig/layer_info.json
Change-Id: Ie223747d947c803617018034b7c5f66d3a243d9b
=> apidump: Timestamps in dump output

scripts/api_dump_generator.py
Api dump is printing shader code for text and html outputs even when not requested.
This fix addresses the issue.
=> apidump: shader code fix for text/html

scripts/api_dump_generator.py, scripts/vktrace_file_generator.py
Functions without a result or a non-const pointer
parameter now will dump their values before calling
into the ICD. Calls that crash the driver can be
dumped before the crash happens, helping to diagnose
bad calls.
files modified:
scripts/api_dump_generator.py
Change-Id: I4b8ecbcb43875055f7a5cc6253316be00ba963c0
=> apidump: Dump functions before callind ICD

layer_factory/assistant_layer/interceptor_objects.h, layer_factory/assistant_layer/mem_bound_warning.cpp, layer_factory/assistant_layer/mem_bound_warning.h
Resolves issue tracked in KhronosGroup/Vulkan-ValidationLayers#24 which states "Warn if memory freed while still bound to other objects. See note in core_validation.cpp CoreChecks::PreCallRecordFreeMemory related to removing the INFORMATION_BIT message".
This specific issue is located at KhronosGroup/Vulkan-ValidationLayers#872
=> Memory Freed While Still Bound Warning

layersvt/device_simulation.cpp
Using `(sizeof(array) / sizeof(array[0])) to get the size of an array on a pointer
creates a new warning with gcc-8. Warning is -Wsizeof-pointer-div.
changes:
layersvt/device_simulation.cpp
Change-Id: I29b668c3f3e2e60739710b0ba9180933763866ab
=> devsim: Fixed new warning from gcc-8

scripts/api_dump_generator.py
Splitting the function dump function into two introduced a formatting error for functions that returned void. 
Change-Id: I43528703091f079c27cb1bb1beb7e686c43f4e24
=> apidump: fix text dump formatting for void functions

layersvt/screenshot.cpp, vkconfig/layer_info.json
Added support for vk_layer_settings.txt to
VK_LAYER_LUNARG_screenshot with the following options
equivalent to the following environment variable.
lunarg_screenshot.frames -> VK_SCREENSHOT_FRAMES
lunarg_screenshot.dir -> VK_SCREENSHOT_DIR
lunarg_screenshot.format -> VK_SCREENSHOT_FORMAT
Addresses issue #872
=> layers: Add settings file support to screenshot

layersvt/api_dump.h
Simple fix for inconsistently sized types by
using fixed size types (namely uint32_t)
files changed:
layersvt/api_dump.h
Change-Id: I6d2c69807d3a37cc7e7d47dc88d96625c4d74bb4
=> apidump: fix msvc conversion warnings

CMakeLists.txt, vktrace/CMakeLists.txt, vktrace/vktrace_dump/CMakeLists.txt
Add the python -B flag to CMake files, to prevent creation of the compiled __pycache__ directory in the installation directory.
Change-Id: I4dc4f6bda1354a08734c47e7d75f960744168097
=> build: Avoid creation of __pycache__ on install

via/via_system.cpp, via/via_system.hpp
Added command line option `--disable_cube_tests` to vkvia
to prevent cube from being run at the end of VIA tests.
=> vkvia: Add option to VIA to disable cube tests

vktrace/vktrace_common/vktrace_trace_packet_utils.c
There are two error on extension DESCRIPTOR_SET_VARIABLE_DESCRIPTOR_COUNT_ALLOCATE_INFO_EXT
capture handler and replay interpret handling, it cause terget title
playback failure, the change fix the two errors.
VKTRACE-143
Change-Id: Ib15ba639286055dce81b759b9d032f50702623da
=> vktrace: fix extension handling error

tests/apidump_test.ps1, tests/apidump_test.sh, tests/vlf_test.ps1, tests/vlf_test.sh
A recent change to vulkaninfo made the extensive format
listing optional (available via the "--show-formats" switch).
The demo layer tests happen to exercise the vulkaninfo
executable, looking for and counting the number of calls
to vkGetPhysicalDeviceFormatProperties; these tests started
failing with the new vulkaninfo because the number of format
queries went from over 200 to 16.
These changes to the test scripts pass the "--show-formats"
switch to vulkaninfo, which restores the original behavior.
Change-Id: I6076c3b573751a4bfcacd552b8f6a021ec7743fd
=> tests: Restore original vulkaninfo behvavior

vktrace/vktrace_replay/vkreplay_vkreplay.cpp, vktrace/vktrace_replay/vkreplay_vkreplay.h
Changed algorithm when searching for a replay device queue family index
when in portability mode. The search starts with the queue family index
in the trace file so as to increase the probablily that the queue
family index selected will work.
Also changed the name of the method getQueueFamilyIdx to getReplayQueueFamilyIdx,
changed it to have no return value, and removed one arg. This simplified code
that calls getReplayQueueFamilyIdx.
Change-Id: Ic09ac4bff3bfff7330c229c3279ac3cbdb65e87b
=> vkreplay: Change algorithm when searching for queue family index

vkconfig/layer_info.json
Changed "Disable stateless parameter Checks" to
"Disable stateless parameter checks" in vkconfig.
=> vkconfig: Fix inconsistant capitalization

via/via_system_windows.cpp, via/via_system_windows.hpp
Fixes via32 displaying the wrong Vulkan runtime on
Windows.
Resolves issue #861
=> vkvia: Fix issue 861

layersvt/api_dump.h, scripts/api_dump_generator.py
Previously, api_dump would release the output lock when finished printing
the head of a call and reaquiring it when printing the body. This enabled
multi threaded applications to interleave output resulting in garbled output.
This commit fixed that by keeping the output lock held for the duration of
the call, at the cost of serializing any calls that are made to vulkan.
This commit also switched api_dump to std::mutex & std::thread::id instead of using
vk_loader_platform.h for the threading primitives.
Changes:
modified:   layersvt/api_dump.h
modified:   scripts/api_dump_generator.py
Change-Id: Ia4b0cabc839c93798eeeb811d6cb322b5b197194
=> api_dump: keep lock held between printing head and body

BUILD.md, vkconfig/vkconfig.cpp, vkconfig/vkconfig.md
During testing it was found a recent vkconfig change requires
Qt version 5.6, which Ubuntu 16.04 ships with version 5.5. Since
the change only affected Windows, the offending code was put behind
and if-def.
Changes to be committed:
modified:   BUILD.md
modified:   vkconfig/vkconfig.cpp
modified:   vkconfig/vkconfig.md
Change-Id: Id81dc5e287b983f9638b314c2892e8cca2e2c915
=> vkconfig: Specify minimum vkconfig versions

layersvt/VkLayer_api_dump.json.in, layersvt/VkLayer_device_simulation.json.in, layersvt/VkLayer_monitor.json.in, layersvt/VkLayer_screenshot.json.in, layersvt/device_simulation.cpp, layersvt/monitor.cpp, layersvt/screenshot.cpp, scripts/api_dump_generator.py
Added support for VK_EXT_tooling_info for the following layers:
`VK_LAYER_LUNARG_screenshot`
`VK_LAYER_LUNARG_monitor`
`VK_LAYER_LUNARG_device_simulation`
`VK_LAYER_LUNARG_api_dump`
=> layers: Add tooling info support

vktrace/vktrace.md
Fix a broken link to the layer configuration overview doc in the vktrace markdown
=> vktrace readme: fix broken link to layer configuration overview doc

scripts/api_dump_generator.py
Changes "value": "0 " to "value" : "0"
Change-Id: Ida26a4d56ce702cca44ad96c2df854eb1ced29b5
=> apidump: Remove extra space in 0-valued flags in json output

build-android/android-generate.bat, build-android/android-generate.sh, build-android/jni/Android.mk, scripts/vlf_makefile_generator.py
This change address VulkanTools issue #968.
A few months ago, the Vulkan-ValidationLayers build switched to
using pre-generated source files. (It used to generate some of
the source files during the build.) This broke the VulkanTools
Android build. The problem was fixed for the Linux Androld build
(but the fix was not completely correct). This  commit fixes the
Android build on Windows, and correctly fixes the Android build
for Linux.
Change-Id: Ie2051bd0229ce305bc6027ee46fdac317c141000
=> VulkanTools: Fix broken Windows Android build.

layersvt/api_dump.h, scripts/api_dump_generator.py
Addresses of structure members, arrays, and pNext
structs were sometimes all wrong.
Change-Id: I8fc9ed54866000b9ee1494327182006cab7b6f81
=> api_dump: Fix output of addresses.

scripts/api_dump_generator.py
The call to next frame has to do setup, of which requires printing to
the output. The issue was this call happened outside of the lock,
causing corrupt output. This commit fixes it by keeping the lock while
the output occurs.
Fixes #962 
Change-Id: I6b05e53b9587f91bf7d85cee7399ca1b16d500fa
=> apidump: Fix json output in multithreaded apps

cmake/FindVulkanHeaders.cmake
Bring over the commit from Vulkan-Loader repo:
https://github.com/KhronosGroup/Vulkan-Loader/commit/63db609ca1c040bacc25c11fdea7571d1dd86b1f
With the recent addition of VK_HEADER_VERSION_COMPLETE, the regex code in CMakeLists was extracting the wrong value.
Internal and external CI in-process
Change-Id: I1ba9d5b4b986ed2c1904c53ada011989a8a4f1dc
=> FindVulkanHeaders: Match header lines more precisely

scripts/api_dump_generator.py
The VkSurfaceFullScreenExclusiveWin32InfoEXT was special cased in the
autogen, but shows no reason to be so. This commit reverts it back to
just anothe plain old struct to be processed and printed.
Change-Id: Ib53adcf10a37d9c4603da4bfee1a1efd761b3420
=> apidump: remove special case from autogen

layersvt/screenshot.cpp
Keep a list of all queues in the device map structure so as to be
able to use an appropriate queue when taking a screenshot. (The queue
passed in to vkQueuePresent may not have the VK_QUEUE_GRAPHICS
capability set, so it can't be used for doing a blit.) The list
of available queues is searched for a queue that is graphics
and present capable, and that is the queue that is used for
getting the screenshot.
Since a queue is a dispatchable object, added code to
create a dispatch table each queue.
Change-Id: I18c2767811a37e4c3ce59ddda98201631cbde875
=> screenshot: Select a queue with both present and graphics capabilities

layersvt/api_dump.h, layersvt/api_dump_layer.md, scripts/api_dump_generator.py, vkconfig/layer_info.json
This change makes the thread and frame header before each printed
function optional. By default, the output does not change, and it is an
'opt-in' only feature which requires setting the 
`lunarg_apidump.show_thread_and_frame` setting to FALSE. The default
value for the setting is TRUE, which is the current behavior
Change-Id: I5cecee34ada31f417bb7dc8a2c394498c2a19831
=> apidump: optional frame and thread header

via/via_system_linux.cpp
The "lunarg-vulkan-sdk" package has been out of commission for some time now. I think this package is from the old .run days.
Here is link to the arch 1.0.3 package that is marked as out-of-date in arch: https://aur.archlinux.org/packages/lunarg-vulkan-sdk/. When a user runs vkvia an error is thrown to the console that the package was not found, this has led to some confusion for some users.
Anyway, this change only searches Debian systems (the only package LunarG provides for) and has been fixed to look for the correct "vulkan-sdk" package.
=> vkvia: update search for installed SDK packages

vkconfig/configurator.cpp, vkconfig/configurator.h, vkconfig/dlgcustompaths.cpp, vkconfig/dlgprofileeditor.cpp, vkconfig/dlgvulkaninfo.cpp, vkconfig/layerfile.cpp, vkconfig/main.cpp, vkconfig/mainwindow.cpp
This addresses the remaining issues discussed here:
https://github.com/LunarG/Projects/issues/378
Layer discovery from vkconfig is as follows:
VK_LAYER_PATH (if it is present)
User defined layer search paths
Standard Layer Paths for the given OS
VULKAN_SDK path if present
No two layers with the same name may be used with vkconfig. So if there are duplicates, the above order is used as precedence for which one's are used. The specific path for each layer is displayed in layer editor dialog (select which layers to override).
Also, a visual indicator on the main screen is shown if the VK_LAYER_PATH environment variable is detected.
=> Richard vkconfig layer discovery rebase

vkconfig/mainwindow.cpp
Change-Id: I067f94aac44519b6ab28488d75ee91fa457e93f9
Simple fix to prevent log window from overflowing when too much log text is added.
=> vkconfig: Fixed log window overflow issue

vkconfig/configuration.h, vkconfig/configurator.cpp, vkconfig/resourcefiles/Validation - Best Practices.json, vkconfig/resourcefiles/Validation - GPU-Assisted.json, vkconfig/resourcefiles/Validation - Reduced-Overhead.json, vkconfig/resourcefiles/Validation - Shader Printf.json, vkconfig/resourcefiles/Validation - Standard.json, vkconfig/resourcefiles/Validation - Synchronization (Alpha).json, vkconfig/resources.qrc
- Add Synchronization Validation default configuration
- Add Synchronization preset
- Show that synchronization validation is Alpha
- Remove threading checks from standard validation configuration
- Fix default layout of validation configurations settings
Replace #1019 PR
=> vkconfig2: Enable Synchronization validation default configuration

vkconfig/macOS/vkconfig.cmake
Change-Id: I4f5f42f9d5d79b0075516533bf15282ccff54020
Fixed regression for cmake on macOS.
=> vkconfig: Fix cmake regression for macOS builds

vkconfig/configurator.cpp
Change-Id: I01168d451d60245f5753470c5dbcfe579096ad48
If a configuration uses a layer that is missing, it is disabled. The same goes if a configuration has no layers at all. However, a valid use case is to have no layers listed, but to have some layers blacklisted (in other words, a configuration that explicitly turns off a validation layer).
As of this PR, this is now allowed/accounted for.
=> vkconfig: Fix for issue 421

vkconfig/mainwindow.cpp, vkconfig/mainwindow.h, vkconfig/mutemessagewidget.cpp, vkconfig/mutemessagewidget.h, vkconfig/settingstreemanager.cpp, vkconfig/settingstreemanager.h, vkconfig/vuidsearchwidget.cpp, vkconfig/vuidsearchwidget.h
Change-Id: I8d232375806d13739184e2f144afa2fd73d34cb5
This build fixes a situation where changing the log file may not be taken into account.
You can press the enter key in the VUID editor to add a selected message, and the edit field is cleared.
WIP: Removing messages that have been added and re-adding when removed.
=> vkconfig: Fixes for issue 413

vkconfig/CMakeLists.txt
A regression occurred when the CMakeLists.txt file was updated to include the network modules (now needed for the single instance feature). This corrects the erroneous error message that "QT could not be found"
=> CMake regression fix for Qt libraries.

vkconfig/macOS/vkconfig.cmake
Added Qt::Network library to `vkconfig.cmake`
=> vkconfig: Fix CMake Link Errors macOS

vkconfig/configurator.cpp, vkconfig/macOS/vkconfig.cmake, vkconfig/macOS/vkconfig.sh, vkconfig/settingstreemanager.cpp
Change-Id: Iaec0274a8209da495654305566fee30d0ebf77e0
Corrections to locate loader on macOS.
Removed vkconfig.sh as it's no longer needed or used.
Corrected failed flush notification to write config when filenames edited in settings.
=> vkconfig: Mostly mac fixes, one log file issue

vkconfig/configurator.cpp, vkconfig/settingstreemanager.cpp, vkconfig/vuidsearchwidget.cpp, vkconfig/vuidsearchwidget.h
Change-Id: I27693c5163fb328ac8dd4911583f23d47db771e9
Fixed a validation error with vkCreateInstance.
VUID completer now removes items once added to the list, re-adds them when removed from the list, and on startup removes items that are already in the filter list.
Added "User Defined" text for non-existent preset for Khronos Validation layer.
=> vkconfig: VUID enhancements and other fixes

vkconfig/configurator.cpp, vkconfig/dlgcustompaths.cpp, vkconfig/dlgprofileeditor.cpp, vkconfig/dlgprofileeditor.ui, vkconfig/mainwindow.cpp, vkconfig/mainwindow.ui
- Fix link to online documentation
- Layer property text is no longer cropped
- Delete debug code left over
- Fix remove custom path assert
- Clean up context menu
- Add VK_LAYER_PATH to the Vulkan status on start
- More consistent custom path behavior: no message box to remove
- More consistent naming accross the tool
Change-Id: I81fba4a45663345538eeb2d898039f9fb709a332
=> vkconfig: Final touches for SDK release

vkconfig/mainwindow.cpp
Change-Id: I762ce30882f5fb33747d804b67813faf89cdf65c
The settings tree at right is cleared out when the custom layer paths dialog is displayed. This fix corrects that, and the tree is only cleared out if upon returning the currently selected configuration is no longer valid.
Also fixed where a caption was being set for no configuration on a configuration export, but that is no longer the case.
=> vkconfig: Save tree state w/custom layers

vkconfig/main.cpp, vkconfig/mainwindow.ui
This should address issues when HDPI screens have various scaling factors applied.
This was also previously removed for Linux, but on testing is needed. Now, the build tests for Qt versions 5.6 and greater and enables the feature if the Qt version is new enough to do so.
The UI changes are misleading, because I moved two of the checkboxes out of the layouts so they could be indented.
=> Vkconfig last minute scaling fixes

vkconfig/appsingleton.cpp, vkconfig/appsingleton.h, vkconfig/configurator.cpp, vkconfig/dlgvulkananalysis.ui, vkconfig/main.cpp, vkconfig/mainwindow.ui
Change-Id: I960be1345af8562be34a881238dba897bef17737
Spelling errors, etc. Biggest change is to the app singleton feature.
Also, checked for file not existing, as failure was not as silent as thought; prevents warning output to console.
Less "scary" text when $VULKAN_SDK is not set.
=> vkconfig: Warnings, misspellings, singleton fix

vkconfig/mainwindow.cpp, vkconfig/resourcefiles/API dump.json, vkconfig/vkconfig.md
Change-Id: I0ecda5c374a7a21b41a1ef936dd2bfdfb55442ef
API Dump is the default layer configuration
Log file browser no longer blanks edit control on cancel.
Changed description of the AP dump configuration.
=> vkconfig: API Dump is now the default configuration

vkconfig/configurator.h, vkconfig/main.cpp, vkconfig/mainwindow.cpp, vkconfig/resourcefiles/Frame Capture - First two frames.json, vkconfig/resourcefiles/Frame Capture - Range (F10 to start and to stop).json, vkconfig/resourcefiles/Validation - Best Practices.json, vkconfig/resourcefiles/Validation - GPU-Assisted.json, vkconfig/resourcefiles/Validation - Reduced-Overhead.json, vkconfig/resourcefiles/Validation - Shader Printf.json, vkconfig/resourcefiles/Validation - Standard.json, vkconfig/resourcefiles/Validation - Synchronization (Alpha).json, vkconfig/resourcefiles/layer_info.json
Corrected spacing issue described here:
https://github.com/LunarG/Projects/issues/448
This required changing the two column approach in the main config tree to a one column approach. Better spacing behavior on all platforms.
Debug-printf configuration was actually identical to GPU-Assisted. Changed default to use debug-printf instead for this config.
Fixed issue where a MessageBox was stalling code flow when a log file could not be opened. Meanwhile, log messages came through in the background and tried writing to the unopened log file.
This PR additionally removes the editor state field from the .json's which should not have been in the template in the first place.
A message box that warns the user is displayed if this is the first post 1.2.148 install that the default configurations …
=> vkconfig post sdk fixes

vkconfig/configurator.cpp, vkconfig/mainwindow.cpp, vkconfig/resourcefiles/Frame Capture - First two frames.json, vkconfig/resourcefiles/Frame Capture - Range (F10 to start and to stop).json, vkconfig/resourcefiles/Validation - Best Practices.json, vkconfig/resourcefiles/Validation - GPU-Assisted.json, vkconfig/resourcefiles/Validation - Reduced-Overhead.json, vkconfig/resourcefiles/Validation - Shader Printf.json, vkconfig/resourcefiles/Validation - Standard.json, vkconfig/resourcefiles/Validation - Synchronization (Alpha).json, vkconfig/vkconfig.md
- Bring back "Validation - Standard" as the default configuration
=> This is done by enabling "Info" messages to systematically getting something out of the validation layers
- Bring back editor settings states presets
=> This is to make sure that the users are exposed first to the most important settings: Presets, message filtering.
=> Vulkan Configurator: Default settings

layersvt/api_dump.h
Options previously would only work if they were capitalized,
causing confusion when it wasn't obvious this was required. This
commit relaxes that constraint to allow mixed case and lower case
text options, notably bool and file output type.
Fixes #1075 
Change-Id: I984408469e84f5773266cabc8bd08d4fb915a72b
=> apidump: Make options case-insensitive

vkconfig/configurator.cpp, vkconfig/mainwindow.cpp, vkconfig/mainwindow.h
Change-Id: Id773980a454f723163a21ef0d0386b2ce22acd1b
Address issues #1087 and #1090 
You can now browse for a working folder from the app launcher.
Policy change. Now by default the log file is put in the users home folder on all operating systems. During testing, not doing so has created issues on all three OS's (Windows, macOS, and Linux). The users home folder is the only folder we can really assume the user has write permissions.
=> vkconfig: Log file location/working folder browser

vkconfig/configurator.cpp, vkconfig/dlgcustompaths.cpp, vkconfig/dlgprofileeditor.cpp, vkconfig/dlgvulkananalysis.cpp, vkconfig/dlgvulkaninfo.cpp, vkconfig/layerfile.cpp, vkconfig/layerfile.h, vkconfig/mainwindow.cpp
Fixed an unreported regression that made it impossible to remove a custom layer path.
Added the ability to see files in a folder when browsing for custom layer paths. This uses a non-OS supplied file browser dialog. (See issue #1098 )
WIP, possibly done: The appearance of the radio buttons for the configuration listing (radio button selects the configuration as the active one). It turns out the visual anomalies originally worked around originated on the Mac. We've gone back and forth a few times, but it seems the Mac fix was the actual problem, and then we fixed the fix... so to speak. No additional spacing seems to be required on Window, Ubuntu OR Fedora... only on macOS. The original macOS work around seems to really wreak havok on Fedora, but not having the work around actually looks …
=> vkconfig gui fixes and updates

vkconfig/dlgprofileeditor.cpp, vkconfig/dlgprofileeditor.ui, vkconfig/vkconfig.pro
Change-Id: I4a32b7fd8998a69225324057442ce8e30f089097
This addresses the issue #1091 and fixes a regression in the .pro file (CI builds with cmake, and the .pro file was broken for QtCreator builds.
Basic description editing was added to the layer editor dialog, as this was where it was originally. This can be iterated and/moved if needed, but seemed a good place to put this to me.
=> vkconfig: .pro file fix and description editiong

.gitignore, vkconfig/configurator.cpp, vkconfig/configurator.h, vkconfig/dlgcreateassociation.cpp, vkconfig/dlgcustompaths.cpp, vkconfig/dlgprofileeditor.cpp, vkconfig/dlgvulkaninfo.cpp, vkconfig/main.cpp, vkconfig/mainwindow.cpp, vkconfig/vkconfig.pro, vkconfig_core/command_line.h, vkconfig_core/path_manager.cpp, vkconfig_core/path_manager.h, vkconfig_core/test/CMakeLists.txt, vkconfig_core/test/test_command_line.cpp, vkconfig_core/test/test_configuration_manager.cpp, vkconfig_core/test/test_layer_manager.cpp, vkconfig_core/test/test_path_manager.cpp, vkconfig_core/util.h
- Added path manager with unit tests
- Removed VulkanLayerManager temp directory
- Added cache of browsed paths
- Fixed display of path not necessarily using the system separator (using the path_manager)
- Updated .gitignore
- Fixed popup error window on unsupported Json files
Change-Id: I6d274b75a2b2cedf54c01db2058e727b533ea8b4
=> vkconfig: added path manager with tests

vkconfig/configurator.cpp, vkconfig/configurator.h, vkconfig/dlgcreateassociation.cpp, vkconfig/dlgcreateassociation.ui, vkconfig/mainwindow.cpp, vkconfig_core/layer_type.cpp
- If the executable doesn't exist, try to replace it.
- Handle the case where the user could include multiple versions of vkcube.
- First use the relative path to vkconfig to use the one from the SDK.
- Add vkcubepp.
- When the list is empty, add default applications.
=> vkconfig: Improve default applications handling 

vkconfig/configurator.cpp, vkconfig/dlgvulkananalysis.cpp, vkconfig/dlgvulkaninfo.cpp, vkconfig/mainwindow.cpp, vkconfig_core/layer.cpp, vkconfig_core/path_manager.cpp, vkconfig_core/platform.h
Also add vkconfig dedicated PLATFORM_ define to allow using them within C++ expression to catch more build errors on all platforms.
Change-Id: I56bbaf013e69675f5284d59aed1e0c4645539e1e
=> vkconfig: Filter out VK_DBG_LAYER_ACTION_DEBUG_OUTPUT on Linux and macOS #1086

.appveyor.yml, vkconfig/configurator.cpp, vkconfig/configurator.h, vkconfig/dlgprofileeditor.cpp, vkconfig/dlgprofileeditor.h, vkconfig/dlgprofileeditor.ui, vkconfig/mainwindow.cpp, vkconfig/mainwindow.h, vkconfig/preferences.cpp, vkconfig/preferences.h, vkconfig/resourcefiles/layer_info.json, vkconfig/settingstreemanager.cpp, vkconfig/settingstreemanager.h, vkconfig/vkconfig.pro, vkconfig_core/configuration.cpp, vkconfig_core/configuration.h
- A new configuration with no layers is not an invalid configuration anymore.
- Fix naming of new configurations
- Fix naming of configurations when layers are missing
- Fix QtCreator build
=> vkconfig: new config naming

vkconfig/alert.cpp, vkconfig/alert.h, vkconfig/dlgprofileeditor.cpp, vkconfig/mainwindow.cpp, vkconfig/vkconfig.pro
- Fix issue #1144 
- Fix configuration setting area not updated correctly when failing to rename a configuration
- Fix configuration renaming on main window with an empty name assert 
- Factorize the same message box at a single code location
Change-Id: Icb210fde1e04372e28c48cd12a87e26de15cbc2c
=> vkconfig: Fix configuration renaming #1144

vkconfig/configurator.cpp, vkconfig/configurator.h, vkconfig/dlgprofileeditor.cpp, vkconfig_core/configuration.cpp
- The settings are stored when switching to excluding the layer
- The settings are restored to the user selection when switching from exclude
to override
- When creating a new configuration with the validation layer the preset shows
'Standard' instead of 'User Defined'
- Fix a memory leak of default settings
Now fixed:
Previously broken (and they were no way to restore the settings hence the P0):
Change-Id: I429ba4f4b47917b5284ba69998425cd63a18a93f
=> vkconfig: Fix no setting when switch between exclude and override #1150

vkconfig/dlgprofileeditor.cpp
Change-Id: I4ae82837c694f27f47edd15fab057ae57b07863d
Minor refresh issue that was only observed on macOS (others may exist).
Calling repaint() for force the update of the parent tree widget forced the update to occur (previously, resizing the window would do it). This is likely a Qt bug, but the repaint() work around causes no harm on Windows or Linux.
=> Fix gui update issue on macOS

vkconfig/configurator.cpp, vkconfig/configurator.h, vkconfig/dlgprofileeditor.cpp, vkconfig/mainwindow.cpp, vkconfig/resourcefiles/layer_info.json, vkconfig/settingstreemanager.cpp, vkconfig/settingstreemanager.h, vkconfig/vulkan.cpp, vkconfig_core/configuration.cpp, vkconfig_core/configuration.h, vkconfig_core/layer.h, vkconfig_core/layer_setting.cpp, vkconfig_core/layer_setting.h
- Add a setting to be able to enable VK_KHR_portability_subset emulation with devsim
- Sort the layers in a matter that reflect the layer properties. devsim layer will always be ordered last, close to the device.
- This PR resolved at least partially #1160
TODO:
- Check the version of devsim layer before displaying VK_KHR_portability_subset emulation setting.
=> vkconfig: Add support for VK_KHR_portability_subset to devsim

vkconfig/dlgcreateassociation.cpp, vkconfig/dlgvulkananalysis.cpp
Change-Id: I12ec39af1e8dca322ec2c8486223325393b3d7d9
A couple more macOS specific fixes. One work around requires a slight default behavior change that I think is okay, pertaining to the application list dialog. Details in the comments.
=> vkconfig: Mac regression fixes

layersvt/VkLayer_device_simulation.json.in, layersvt/device_simulation.cpp, layersvt/device_simulation.md, layersvt/device_simulation_examples/portability_test.json
Added emulation for VK_KHR_portability_subset to the Device Simulation
layer.
Also added the ability to override values in the
VK_KHR_portability_subset data structures with JSON config files.
This change requires a header update before it can be merged.
=> devsim: Add emulation for portability extension

layersvt/VkLayer_device_simulation.json.in
Small change to the VK_LAYER_LUNARG_device_simulation manifest JSON file
to fix behaviour with VkConfig.
With the addition of the portability emulation feature, the
layer sometimes implements the VK_KHR_portability_subset extension and
sometimes doesn't.  Because of this, we want more control over how the
layer reports the implementation of VK_KHR_portability_subset.
This requires removal of the extension entry in the layer manifest JSON
file.
Change-Id: Iebb2f68317bc4d73ccba940d224506c8b492d664
=> devsim: Fix manifest JSON file

vkconfig/macOS/vkconfig.cmake, vkconfig/vkconfig.pro, vkconfig_core/CMakeLists.txt
Change-Id: I720dd07676ee57dbcc0be122e3ae10d7cbdc3d3f
This commit will be needed for macOS SDK builds.
Recent refactoring has broken macOS builds when using cmake.
In addition, the version of Qt used on macOS for SDK builds is less tolerant of forward slash/backslash issues, so it is corrected here as well.
=> macOS fixes for cmake builds

layersvt/device_simulation.cpp
Fixed warnings in Device Simulation Layer about
conversion between 'size_t' and 'const uint32_t'.
Partially fixes issue #1178
=> devsim: Fix conversion warnings

vkconfig/configurator.cpp, vkconfig/configurator.h, vkconfig/mainwindow.cpp, vkconfig_core/configuration.cpp, vkconfig_core/path_manager.cpp, vkconfig_core/path_manager.h
- When no configuration could be found on start up, the tool ask the user if the user want to restore the default configuration
- When the Vulkan Configurator home directories are deleted, the directories are recreated and all the user/current configurations restored on Vulkan Configurator exist 
Change-Id: Ia1cb480821f9b37986b7469ff9581800a742619b
=> vkconfig: Improve the management of tool home directories

vkconfig_core/environment.cpp
Change-Id: I3d5e1944600bfcc0cc09aa7b0e7a248d4a1afdf9
Fixed regressions for not being able to find vkcube on initial startup, and proper paths for the launcher feature.
=> vkconfig: Fixed macOS regression for vkcube search

layersvt/device_simulation.cpp
Change the API version check used by the dev-sim layer to determine if vkGetPhysicalDeviceProperties2 is available from a comparison between the API version retrieved from vkGetPhysicalDeviceProperties and VK_VERSION_1_0, which is now defined as 1, to a comparison between the minor API version that the application specified through VkApplicationInfo and 0.
=> devsim: Update API version check

layersvt/VkLayer_device_simulation.json.in, layersvt/device_simulation.cpp, layersvt/device_simulation.md
Added back in code to override the list of device extensions.
Addresses issue #985
=> devsim: Reactivate ArrayOfExtensionProperties

layersvt/device_simulation.cpp
Ensure EnumerateDeviceExtensionProperties only increases the returned
query count once.
Change-Id: Ib54ae43d536fb7684fb14a50bc54d8db9e0abaad
=> devsim: Conditionally increase query count

vkconfig/CHANGELOG.md, vkconfig/configurator.cpp, vkconfig/configurator.h, vkconfig/mainwindow.cpp, vkconfig/settingstreemanager.cpp
- Fix assert when a configuration doesn't exist anymore but is active
- Factorize configuration refresh
- Remove layers override instantly when using fully app control
- Immediately override and surrender layers when changing layers management option
Change-Id: Iadbc962b918f0807c07d0c455bf21696046438c1
=> vkconfig: Fix layers override update when changing layers management options

cmake/FindVulkanHeaders.cmake, cmake/FindXCB.cmake
Silences two cmake verbose warnings as reproduced with `cmake-3.18.4`.
```
CMake Warning (dev) at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
The package name passed to `find_package_handle_standard_args` (xcb) does
not match the name of the calling package (XCB).  This can lead to problems
in calling code that expects `find_package` result variables (e.g.,
`_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
cmake/FindXCB.cmake:39 (find_package_handle_standard_args)
CMakeLists.txt:111 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
```
```
CMake Warning (dev) at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
The package name passed to …
```
=> cmake: Silence warnings.

.appveyor.yml, vkconfig/CHANGELOG.md, vkconfig/main_layers.cpp, vkconfig/mainwindow.cpp, vkconfig/vkconfig.pro, vkconfig_core/environment.cpp
- Build with VS2015, VS2017 and VS2019
- Build with Qt 5.9 and Qt 5.15
- Build Vulkan Configurator with QMake
- Failing tests build doesn't result in green run anymore...
- Fix build warnings
- Fix Vulkan Configurator empty application list case
Change-Id: Icc0fae3614b3acb82d2fb73b2f67595f855e4aff
=> C.I.: Improve build platform coverage

.appveyor.yml
- Using QMake when building with VS2015 to test the QtCreator project only
- Using CMake when building with VS2017 and VS2019 project only
- Overall reduce build time.
With multiple threads CMake XOR NMake (this PR):
Image: Visual Studio 2015; Configuration: Debug; Platform: Win32: 4 min 29 sec
Image: Visual Studio 2017; Configuration: Release; Platform: x64: 8 min 29 sec
Image: Visual Studio 2019; Configuration: Debug; Platform: x64: 8 min 27 sec
With multiple threads CMake and NMake:
Image: Visual Studio 2015; Configuration: Debug; Platform: Win32: 7 min 39 sec
Image: Visual Studio 2017; Configuration: Release; Platform: x64: 8 min 53 sec
Image: Visual Studio 2019; Configuration: Debug; Platform: x64: 9 min 40 sec
With CMake and NMake on all compiler versions:
Image: Visual Studio 2015; …
=> C.I.: Only build with CMake XOR QMake

vkconfig/CHANGELOG.md, vkconfig/dialog_applications.cpp, vkconfig/dialog_applications.h, vkconfig/vkconfig.pro, vkconfig_core/environment.cpp, vkconfig_core/environment.h, vkconfig_core/override.cpp
Fixed a couple of regressions, one not Mac related at all. Code to extract an executable from app bundles was not being called for the default applications vkcube and vkcubepp on setup for macOS.
Paths to these applications in the override json file had an extra forward slash after Applications in the path (as in Applications//vkcube.app)
On all platforms, the list of applications was always added to the override json file, even when "Apply only to the selected list of Vulkan applications" was unchecked.
=> vkconfig: Fix initialization of added applications on macOS

vkconfig_core/test/test_command_line.cpp
Change-Id: Ic3394043275de8d00fdf9ce0594dceea4e2ff491
=> vkconfig: Disable convenient test code only warning

vkconfig/CHANGELOG.md, vkconfig/main.cpp, vkconfig/main_signal.cpp, vkconfig/main_signal.h, vkconfig/vkconfig.pro
- If the user interupt Vulkan Configurator (^C) or Vulkan Configurator crash
surrender the layers to avoid the layers override to remain without the user
knowning it.
PS: This is not working with Visual Studio (SHIFT F5/stop debugging)
=> vkconfig: Surrender layers on crash

layersvt/VkLayer_device_simulation.def, layersvt/device_simulation.cpp
Ensure that PhysicalDeviceData is only populated from calls
requiring VK_KHR_get_physical_device_properties2 after vkCreateInstance
has completely finished.
NOT COMPLETE
This change "works" to get vkcube running with VVL enabled. See `HACK!!`
comments for details.
=> devsim: populate PDD after CreateInstance

vkconfig_core/configuration.cpp
Change-Id: If281ac05baab04254714de0af592254f29485510
=> vkconfig: fix configuration reset when a layer is missing

vkconfig/CHANGELOG.md, vkconfig/configurator.cpp, vkconfig/main_layers.cpp, vkconfig/main_signal.cpp, vkconfig/settings_tree.cpp, vkconfig_core/configuration.cpp, vkconfig_core/configuration.h, vkconfig_core/configuration_manager.cpp, vkconfig_core/layer.cpp, vkconfig_core/layer_manager.cpp, vkconfig_core/layer_manager.h, vkconfig_core/override.cpp, vkconfig_core/override.h, vkconfig_core/path_manager.cpp, vkconfig_core/test/Configuration 2.2.0 - Layer 1.4.0.json, vkconfig_core/test/Layer 1.3.0.json, vkconfig_core/test/Layer 1.4.0 - presets.json, vkconfig_core/test/Layer 1.4.0 - setting platforms.json, vkconfig_core/test/Layer 1.4.0 - setting types.json, vkconfig_core/test/override_layers_1_4_0.json, vkconfig_core/test/override_settings_1_4_0.txt, vkconfig_core/test/resources.qrc, vkconfig_core/test/test_layer.cpp, vkconfig_core/test/test_layer_manager.cpp, vkconfig_core/test/test_override.cpp
- Test generated layers and setting overrides files
- Fix export and import path truncated
- Fix crash when loading a JSON file as if it's a JSON layer file but it's not
=> vkconfig: Test generated layers and setting overrides files

vkconfig/CHANGELOG.md, vkconfig/settings_tree.cpp, vkconfig/settings_validation_areas.cpp, vkconfig/settings_validation_areas.h, vkconfig_core/layers/162/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layers/latest/VK_LAYER_KHRONOS_validation.json
Validation layer `printf buffer size' setting should be exposed as a int instead of a bool in the UI #1338
=> vkconfig: Fix `printf buffer size' setting exposed a `bool`

vkconfig/configurator.cpp, vkconfig_core/configuration_manager.cpp, vkconfig_core/configuration_manager.h, vkconfig_core/environment.cpp, vkconfig_core/environment.h
Add new default configurations to the list (here we are interested in Synchronization configuration) if it was never added.
Change-Id: I8cc2363f89053244eff3c33fcf4c56c7922f3581
=> vkconfig: add default configuration for the first time

vkconfig/CHANGELOG.md, vkconfig/settings_validation_areas.cpp, vkconfig_core/layer.cpp
Change-Id: I3cb5fc70940acfbee01a7d76139edde5ea61f57c
=> vkconfig: Fix crash when using older 'VK_LAYER_KHRONOS_validation' versions

layersvt/device_simulation.cpp, vkconfig_core/layers/latest/VK_LAYER_LUNARG_device_simulation.json, vkconfig_core/setting_set.h
Support this:
```
lunarg_device_simulation.filename = C:\VulkanSDK\1.2.169.0\Config\VK_LAYER_LUNARG_device_simulation\macOS_gpu_family_1_portability.json
lunarg_device_simulation.debug_enable = TRUE
lunarg_device_simulation.emulate_portability = TRUE
lunarg_device_simulation.exit_on_error = FALSE
lunarg_device_simulation.modify_extension_list = FALSE
```
Keep this for compatbility:
```
lunarg_device_simulation.filename = C:\VulkanSDK\1.2.169.0\Config\VK_LAYER_LUNARG_device_simulation\macOS_gpu_family_1_portability.json
lunarg_device_simulation.debug_enable = 1
lunarg_device_simulation.emulate_portability = 1
lunarg_device_simulation.exit_on_error = 0
lunarg_device_simulation.modify_extension_list = 0
```
=> devsim: bool layer settings can be strings

layersvt/VkLayer_device_simulation.json.in, layersvt/device_simulation.cpp, layersvt/device_simulation.md
Added a new option `VK_DEVSIM_MODIFY_MEMORY_FLAGS` to allow users to
enable/disable devsim's ability to modify memory heap flags and memory
type flags.  Disabled by default.
Devsim's ability to modify memory heap size and count are not affected
by this change.
Fixes issue #1320
=> devsim: Add option to enable/disable memory sim

vkconfig/dialog_vulkan_info.cpp
This improve readability by not having all the version info in the same line
as the name of the layer & its description
Fixes #1376 
Change-Id: I34fbac08496b08470b30f52d39023f9734fc1ccf
=> vkconfig: Make vulkaninfo layer info subobjects of the layer

layersvt/VkLayer_device_simulation.json.in, layersvt/device_simulation.cpp, layersvt/device_simulation.md
Updated Devsim to modify structs provided by extensions made core in Vulkan 1.1.
The following extensions are included:
- `VK_KHR_16bit_storage`
- `VK_KHR_get_physical_device_properties2`
- `VK_KHR_maintenance2`
- `VK_KHR_maintenance3`
- `VK_KHR_multiview`
- `VK_KHR_sampler_ycbcr_conversion`
- `VK_KHR_variable_pointers`
The following structs are now modified by the Devsim layer:
- `VkPhysicalDeviceProperties2`
- `VkPhysicalDeviceMaintenance3Properties`
- `VkPhysicalDeviceMultiviewProperties`
- `VkPhysicalDevicePointClippingProperties`
- `VkPhysicalDeviceFeatures2`
- `VkPhysicalDevice16BitStorageFeatures`
- `VkPhysicalDeviceMultiviewFeatures`
- `VkPhysicalDeviceSamplerYcbcrConversionFeatures`
- `VkPhysicalDeviceVariablePointersFeatures`
- `VkPhysicalDeviceMemoryProperties2`
- …
=> devsim: Update to Vulkan 1.1

layersvt/device_simulation.cpp
Updated the error Devsim throws when an application is trying to use an
API version greater than what Devsim supports to include Vulkan v1.1 as
a support Vulkan API version.
=> devsim: Update Devsim supported version error

vkconfig/CHANGELOG.md, vkconfig/settings_tree.cpp, vkconfig/settings_validation_areas.cpp, vkconfig/settings_validation_areas.h, vkconfig/widget_setting_enum.cpp, vkconfig_core/configuration.cpp, vkconfig_core/header.h, vkconfig_core/layer.cpp, vkconfig_core/layers/130/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layers/135/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layers/141/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layers/148/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layers/154/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layers/162/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layers/170/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layers/latest/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layers/layers_schema.json, vkconfig_core/setting_meta.cpp, vkconfig_core/setting_type.cpp, vkconfig_core/setting_type.h, vkconfig_core/test/Layer 1.4.0 - setting types.json, vkconfig_core/test/test_layer.cpp, vkconfig_core/test/test_setting_type.cpp
- 'view' property to hide settings
- Use 'view' property to hide validation layer VK_DBG_LAYER_ACTION_CALLBACK
- Set 'duplicate_message_limit' default to 0
=> vkconfig: add 'view' property to settings and enum values

layersvt/device_simulation.cpp, layersvt/device_simulation.md
Updated Devsim to modify structs provided by the following extensions:
- `VK_KHR_8bit_storage`
- `VK_KHR_buffer_device_address`
- `VK_KHR_depth_stencil_resolve`
- `VK_KHR_imageless_framebuffer`
- `VK_KHR_separate_depth_stencil_layouts`
- `VK_KHR_shader_atomic_int64`
- `VK_KHR_shader_float16_int8`
- `VK_KHR_shader_float_controls`
- `VK_KHR_shader_subgroup_extended_types`
- `VK_KHR_timeline_semaphore`
- `VK_KHR_uniform_buffer_standard_layout`
- `VK_KHR_vulkan_memory_model`
- `VK_EXT_descriptor_indexing`
- `VK_EXT_host_query_reset`
- `VK_EXT_sampler_filter_minmax`
- `VK_EXT_scalar_block_layout`
The following structs are now modified by the Devsim layer:
- `VkPhysicalDevice8BitStorageFeatures`
- `VkPhysicalDeviceBufferDeviceAddressFeatures`
- `VkPhysicalDeviceDepthStencilResolveProperties`
- …
=> devsim: Update to Vulkan 1.2

layersvt/monitor.cpp, layersvt/monitor_layer.md
The layer was calling into xcb even if it didn't have a valid connection
from vkCreateXcbSurfaceKHR. This change intializes the connection to
null and then checks that it was retrieved before using it.
Fixes #1409
=> monitor: Fix crash on Wayland

layersvt/VkLayer_device_simulation.json.in, vkconfig/settings_validation_areas.cpp, vkconfig/widget_setting_list.cpp, vkconfig_core/layers/162/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layers/170/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layers/latest/VK_LAYER_KHRONOS_validation.json, vkconfig_core/setting_meta.cpp
Surrender devsim layer settings to devsim developers.
Vulkan Configurator will use these settings when loading devsim layer.
=> devsim: add settings to layer manifest

layersvt/VkLayer_api_dump.json.in, vkconfig_core/layers/130/VK_LAYER_LUNARG_api_dump.json, vkconfig_core/layers/135/VK_LAYER_LUNARG_api_dump.json, vkconfig_core/layers/141/VK_LAYER_LUNARG_api_dump.json, vkconfig_core/layers/148/VK_LAYER_LUNARG_api_dump.json, vkconfig_core/layers/154/VK_LAYER_LUNARG_api_dump.json, vkconfig_core/layers/162/VK_LAYER_LUNARG_api_dump.json, vkconfig_core/layers/170/VK_LAYER_LUNARG_api_dump.json, vkconfig_core/layers/latest/VK_LAYER_LUNARG_api_dump.json
Surrender API-dump layer settings to API-dump developers.
Vulkan Configurator will use these settings when loading API dump layer.
=> API Dump: add settings to layer manifest

vkconfig_core/configuration.cpp, vkconfig_core/configuration_manager.cpp, vkconfig_core/json_validator.cpp, vkconfig_core/layer.cpp, vkconfig_core/layer.h, vkconfig_core/layer_manager.cpp, vkconfig_core/layers/layers_schema.json, vkconfig_core/registry.cpp, vkconfig_core/test/test_configuration_built_in.cpp, vkconfig_core/test/test_layer.cpp, vkconfig_core/test/test_layer_built_in.cpp
As a result of SDK layers being optional, built-in configuration using these layers won't load if these layers are missing
=> vkconfig: reduce unit test time and optional SDK layers

vkconfig_core/layer.cpp
vkconfig was crashing when detecting an SDK layer with an unexpected version
=> vkconfig: fix loading of built-in settings

layersvt/VkLayer_api_dump.json.in, vkconfig/widget_setting_filesystem.cpp, vkconfig_core/layers/130/VK_LAYER_LUNARG_api_dump.json, vkconfig_core/layers/135/VK_LAYER_LUNARG_api_dump.json, vkconfig_core/layers/141/VK_LAYER_LUNARG_api_dump.json, vkconfig_core/layers/148/VK_LAYER_LUNARG_api_dump.json, vkconfig_core/layers/154/VK_LAYER_LUNARG_api_dump.json, vkconfig_core/layers/162/VK_LAYER_LUNARG_api_dump.json, vkconfig_core/layers/170/VK_LAYER_LUNARG_api_dump.json, vkconfig_core/layers/latest/VK_LAYER_LUNARG_api_dump.json
An issue was discovered that if a JSON file is too big and open by
the Vulkan Loader, the loader would crash instantly.
This issue is fixed for SDK 1.2.176 but we can rely on the $LOCAL
built-in variable to prevent this issue to appear.
Change-Id: If100aa5c939e110744eb2920f08440cd3300f282
=> vkconfig: Avoid API dump log to go in SDK bin dir #1469

layersvt/api_dump.h, scripts/api_dump_generator.py
The call to vkGetInstanceProcAddr to get vkCreateDevice used NULL for the
VkInstance handle. This is forbidden by the spec but was allowed on
various implementations. This commmit fixes it by keeping track of the
physical device and instance handles.
Fixes #1233 
Change-Id: Ib247c71913f1512f919349523a2058907616ee23
=> apidump: Use VkInstance instead of NULL in GIPA

vkconfig/settings_tree.cpp
Change-Id: If910d2431bd5f0e15bb3baaf15a5caf8f5ef44d7
=> vkconfig: Fix grammar in tooltip for layer order

LICENSE.txt, external/valijson/LICENSE
The root license file says:
```
The majority of files in this project use the Apache 2.0 License.
There are a few exceptions and their license can be found in the source.
Any license deviations from Apache 2.0 are "more permissive" licenses.
```
Just adding this file seems to resolve the issue. 
compat/optional.hpp has the license embedded within the source so I guess it's ok.
=> license: add valijon license

vkconfig/CHANGELOG.md, vkconfig/README.md, vkconfig/configurator.cpp, vkconfig/widget_setting.cpp, vkconfig/widget_setting.h, vkconfig/widget_setting_bool.cpp, vkconfig/widget_setting_enum.cpp, vkconfig/widget_setting_filesystem.cpp, vkconfig/widget_setting_flags.cpp, vkconfig/widget_setting_float.cpp, vkconfig/widget_setting_frames.cpp, vkconfig/widget_setting_int.cpp, vkconfig/widget_setting_list.cpp, vkconfig/widget_setting_list_element.cpp, vkconfig/widget_setting_string.cpp, vkconfig_core/override.cpp, vkconfig_core/setting_meta.cpp, vkconfig_core/setting_meta.h, vkconfig_core/test/VK_LAYER_LUNARG_reference_1_2_0.json, vkconfig_core/test/test_layer.cpp
When the environment variable of a layer setting is set while Vulkan Configurator runs, the setting is highlighted and a tool tip is set to the value to state the setting is overridden.
=> vkconfig: Add interaction with layer env variables

layersvt/VkLayer_device_simulation.json.in, layersvt/device_simulation_examples/sdk_sample_configs/portability_minimum_vulkan_1_0.json, layersvt/device_simulation_examples/sdk_sample_configs/portability_minimum_vulkan_1_1.json, layersvt/device_simulation_examples/sdk_sample_configs/portability_minimum_vulkan_1_2.json, layersvt/device_simulation_examples/sdk_sample_configs/spec_minimum_vulkan_1_0.json, layersvt/device_simulation_examples/sdk_sample_configs/spec_minimum_vulkan_1_1.json, layersvt/device_simulation_examples/sdk_sample_configs/spec_minimum_vulkan_1_2.json
Added the minimum_vulkan_1_2.json devsim config file to the
device_simulation_examples/sdk_sample_configs.
Added the "Vulkan 1.2 minimum requirements" preset to
VkLayer_device_simulation.json.in.
=> vkconfig: Add Vulkan 1.2 minimum preset

layersvt/VkLayer_device_simulation.json.in, vkconfig_core/layers/130/VK_LAYER_LUNARG_device_simulation.json, vkconfig_core/layers/135/VK_LAYER_LUNARG_device_simulation.json, vkconfig_core/layers/141/VK_LAYER_LUNARG_device_simulation.json, vkconfig_core/layers/148/VK_LAYER_LUNARG_device_simulation.json, vkconfig_core/layers/154/VK_LAYER_LUNARG_device_simulation.json, vkconfig_core/layers/162/VK_LAYER_LUNARG_device_simulation.json, vkconfig_core/layers/170/VK_LAYER_LUNARG_device_simulation.json
Add an introduction and a URL in the devsim manifest. 
These are used by Vulkan Configurator for the Vulkan Developers to find the layer documentation.
=> devsim: add url and introduction to the layer manifest

layersvt/VkLayer_api_dump.json.in, vkconfig_core/layers/130/VK_LAYER_LUNARG_api_dump.json, vkconfig_core/layers/135/VK_LAYER_LUNARG_api_dump.json, vkconfig_core/layers/141/VK_LAYER_LUNARG_api_dump.json, vkconfig_core/layers/148/VK_LAYER_LUNARG_api_dump.json, vkconfig_core/layers/154/VK_LAYER_LUNARG_api_dump.json, vkconfig_core/layers/162/VK_LAYER_LUNARG_api_dump.json, vkconfig_core/layers/170/VK_LAYER_LUNARG_api_dump.json
Add an introduction and a URL in the layer manifest.
These are used by Vulkan Configurator for the Vulkan Developers to find the layer documentation.
=> api dump: add url and introduction to the layer manifest

layersvt/screenshot.cpp
The screenshot layer was calling both vkQueueWaitIdle and vkDeviceWaitIdle after performing the swapchain image copy, without performing any synchronization before the swapchain image copy.  This change moves the vkDeviceWaitIdle call before the copy, to wait for any outstanding work that may modify the swapchain image to complete.
Because the copy is performed in the layer's implementation of vkQueuePresentKHR, prior to making the actual vkQueuePresentKHR call, it may be possible to further improve synchronization by stealing the wait semaphores intended for vkQueuePresentKHR to use with the vkQueueSubmit that performs the copy so that the vkDeviceWaitIdle call can be removed.
=> screenshot: adjust synchronization

vkconfig/CHANGELOG.md, vkconfig/settings_validation_areas.cpp, vkconfig/settings_validation_areas.h
Handle this Validation PR: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2808
The feature requires July SDK validation layer version of to see the UI.
=> vkconfig: add validation shader caching UI

layersvt/VkLayer_device_simulation.json.in
macOS doesn't support Vulkan 1.2 so there is no point to expose the 1.2 files on macOS. It's just obfuscation of functional features.
=> devsim: macOS doesn't support Vulkan 1.2

layersvt/device_simulation.cpp
- Preventing to read a devsim file with more data than expected is more restrictive than useful.
- Read every core feature available in the devsim file indendently from the schema
I didn't add all the extensions because I wasn't 100% sure it would affect things but I actually expect it would just work. More refactor would be required so that the "missing extension support" warnings are emitted only when the structures are not found.
=> devsim: first step to be able to read GPUinfo database

vkconfig/CHANGELOG.md, vkconfig/alert.cpp, vkconfig/alert.h, vkconfig/configurator.cpp, vkconfig/dialog_applications.cpp, vkconfig/dialog_layers.cpp, vkconfig/main_gui.cpp, vkconfig/mainwindow.cpp, vkconfig/settings_tree.cpp, vkconfig/vkconfig.pro, vkconfig/vulkan.cpp, vkconfig_core/alert.cpp, vkconfig_core/alert.h, vkconfig_core/layer.cpp, vkconfig_core/test/CMakeLists.txt
No title were displayed on macOS message box causing quite some confusion considering the convention used when using message boxes in Vulkan Configurator.
Also improve message box for failed layer manifest validation against the layer schema.
=> vkconfig: Fix message box with no title displayed on macOS #1547

layersvt/VkLayer_device_simulation.json.in, layersvt/device_simulation.cpp, layersvt/device_simulation.md
Added the ability to modify the following structures with devsim:
VkSurfaceCapabilitiesKHR
VkSurfaceFormatKHR list
VkPresentModeKHR list
Added the following new settings to control surface format and present
mode list modification:
VK_DEVSIM_MODIFY_SURFACE_FORMATS
VK_DEVSIM_MODIFY_PRESENT_MODES
=> devsim: Add surface capabilities modifications

layersvt/device_simulation_examples/sdk_sample_configs/portability_minimum_vulkan_1_0.json, layersvt/device_simulation_examples/sdk_sample_configs/portability_minimum_vulkan_1_1.json, layersvt/device_simulation_examples/sdk_sample_configs/portability_minimum_vulkan_1_2.json
Modified minimum values in the minimum portability subset configs to
more accurately match real Vulkan portability subset devices.
Added portability subset structs to the config files.
Fixes #1538
=> devsim: Update minimum portability subset configs

README.md
Providing information about the status of actively used tools as well as communicate their replacements is essential for ensuring the community is aware of these replacements and knows where to find what. Non suspecting developers might compile VulkanTools expecting to get vktrace and vkreplay binaries while these have been removed and superseded by gfxreconstruct.
=> Information about deprecation, removal and replacement of vktrace

layersvt/device_simulation.cpp
Devsim was replacing not just the device extension list, but also each
individual layer's list of provided extensions.
This PR fixes this issue.
=> devsim: Fix layer extension list replacement

via/via_system_linux.hpp
I ran into some `-Winconsistent-missing-override` warnings when trying to build this on clang 12.0. I think we did something similar for the validation layers a while back.
=> build: Fix missing override warnings

layersvt/device_simulation.cpp
AndroidGetEnv was returning the `c_str` of a staticly allocated
`std::string` as a `const char*`.
This `const char*` gets converted into an `std::string` anyway, so this
commit modifies the AndroidGetEnv function to return a `std::string`.
Fixes #1525
=> devsim: Fix AndroidGetEnv use after free error

layersvt/device_simulation.cpp
Fixes issue where `VkSurfaceCapabilitiesKHR` struct was not filled out
properly.
=> devsim: Fix Surface Capabilities

vkconfig/settings_tree.cpp, vkconfig/settings_tree.h, vkconfig/settings_validation_areas.cpp, vkconfig/vulkan.cpp, vkconfig_core/doc.cpp, vkconfig_core/layer.cpp, vkconfig_core/layer.h, vkconfig_core/layers/130/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layers/135/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layers/141/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layers/148/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layers/154/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layers/162/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layers/170/VK_LAYER_KHRONOS_validation.json, vkconfig_core/test/test_layer.cpp, vkconfig_core/test/test_layer_preset.cpp, vkconfig_core/test/test_parameter.cpp, vkconfig_core/test/test_setting_type_bool.cpp, vkconfig_core/test/test_setting_type_bool_numeric.cpp, vkconfig_core/test/test_setting_type_enum.cpp, vkconfig_core/test/test_setting_type_file_load.cpp, vkconfig_core/test/test_setting_type_file_save.cpp, vkconfig_core/test/test_setting_type_flags.cpp, vkconfig_core/test/test_setting_type_float.cpp, vkconfig_core/test/test_setting_type_folder_save.cpp, vkconfig_core/test/test_setting_type_frames.cpp, vkconfig_core/test/test_setting_type_group.cpp, vkconfig_core/test/test_setting_type_int.cpp, vkconfig_core/test/test_setting_type_list.cpp, vkconfig_core/test/test_setting_type_string.cpp
- Fix regression introduced while implementing validation layer "validate_draw_indirect" setting
- Fix typo
- Add built-in manifest env var for validation layers
- Avoid crash when not Vulkan loader is found
- Validation areas content expands by default
=> vkconfig: SDK 1.2.182 fixes

vkconfig/mainwindow.cpp, vkconfig/mainwindow.h
=> vkconfig: fix crash when renaming a configuration #1551

vkconfig/widget_setting_list.cpp, vkconfig/widget_setting_list.h
Vulkan Configurator was emitting a warning on start up when the layers configuration had a list type of setting
=> vkconfig: Remove Qt Warning on Qt 5.11 and older

vkconfig/mainwindow.cpp, vkconfig_core/date.cpp, vkconfig_core/date.h, vkconfig_core/test/test_date.cpp
Using __DATE__ caused Linux package error due to the reproducible build requirements:
https://www.debian.org/doc/manuals/debmake-doc/ch05.en.html#reproducible
=> vkconfig: fix Linux packages build

vkconfig/CHANGELOG.md, vkconfig_core/doc.cpp, vkconfig_core/layers/148/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layers/154/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layers/162/VK_LAYER_KHRONOS_validation.json, vkconfig_core/layers/170/VK_LAYER_KHRONOS_validation.json, vkconfig_core/override.cpp, vkconfig_core/test/test_layer_built_in.cpp
Standard Preset Before:
```
khronos_validation.debug_action = 
khronos_validation.log_filename = stdout
khronos_validation.report_flags = error,warn,perf
khronos_validation.enable_message_limit = false
khronos_validation.duplicate_message_limit = 1
khronos_validation.message_id_filter = 
khronos_validation.disables = VK_VALIDATION_FEATURE_DISABLE_THREAD_SAFETY_EXT
khronos_validation.enables = 
khronos_validation.printf_to_stdout = true
khronos_validation.printf_verbose = false
khronos_validation.printf_buffer_size = 1024
khronos_validation.gpuav_buffer_oob = true
```
Standard Preset After:
```
khronos_validation.debug_action = 
khronos_validation.report_flags = error,warn,perf
khronos_validation.enable_message_limit = false
khronos_validation.message_id_filter = …
```
=> vkconfig: fix settings output when dependencies is not met

vkconfig/settings_validation_areas.cpp, vkconfig/settings_validation_areas.h
The validation manifest need to expose VALIDATION_CHECK_ENABLE_VENDOR_SPECIFIC_AMD for this UI to appear.
=> vkconfig: add support for AMD best practices

layersvt/device_simulation_examples/sdk_sample_configs/portability_desktop_1_0.json
Fixed `storageImageSampleCounts` value from 9 -> 1
Fixes issue #1594
=> devsim: Fix portability_desktop_1_0.json

vkconfig/README.md
README for vkconfig doesn't specify that qt must be installed. This commit updates to include a message that qt must be installed.
=> README: specify to have qt installed to run vkconfig from tarball

vkconfig/CHANGELOG.md, vkconfig/vulkan.cpp, vkconfig_core/version.cpp
When "break" debug action is selected, the action is triggered by a notification message when active. 
This causes Vulkan Configurator to fail starting when creating a Vulkan Instance because the a notification message is generated.
The Layers configuration no longer apply to Vulkan Configurator to ensure the layers never break the tool that allows us to configure the layers...
=> vkconfig: Discard applied layers configuration to ensure the layers never crash Vulkan Configurator

via/via_system_linux.cpp
vkvia was failing to compile on gcc version 11.2
because of a mismatched-dealloc warning
See issues:
https://github.com/LunarG/VulkanTools/issues/1615
https://vulkan.lunarg.com/issue/view/617b38195df112b7e382a341
=> via: fix compilation on gcc version 11.2

layersvt/api_dump.h
`first_func_call_on_frame` can be false if no interested vulkan api call has been made yet. However, `settings()` would instantiate `dump_settings` if it was a `nullptr`.
=> api_dump: avoid creating ApiDumpSettings at ~ApiDumpInstance()

vkconfig_core/override.cpp, vkconfig_core/test/override_layers_2_2_2_schema_1_2_1.json
Allows using layers from the system path and user defined paths at the same time.
=> vkconfig: always add all layers paths to override_paths

vkconfig_core/path.cpp
Fix for this issue:
https://gitlab.khronos.org/vulkan/Vulkan-SDK-Packaging/-/issues/910
Massage or rearrange if needed, but the case where VULKAN_SDK is defined is not handled correctly on macOS without something like this.
=> Vkconfig fix for VULKAN_SDK set on macOS

vkconfig/dialog_layers.cpp
Change-Id: I2483369df8d8fd222dba1ef37334678c61912b88
=> vkconfig: fix creating a new configuration crash

scripts/api_dump_generator.py
The previous solution relied on `<<` having a lower precedence than `+`.
Except it didn't and clang complains about it. The fix is straightforward,
fix up the codegen inside the template blocks instead of trying to fix it
outside of them.
Fixes #1646
=> apidump: Fixup rasterizationSamples in codegen

via/via_system.cpp
Enable support for the portability enumeration extension and flag bit
when creating instances.
Also cleaned up some of the redundant memsets with more C++ style code.
=> vkvia: Support Portability Enumeration

via/via_system.cpp
Changed message displayed from "Failed to open settings file" to
"File not found". It's not an error, so changed message so it
doesn't sound so alarming.
Addresses https://github.com/LunarG/VulkanTools/issues/981
=> Change message when layer settings file can't be opened

via/via_system.cpp, via/via_system.hpp, via/via_system_windows.cpp, via/via_system_windows.hpp
Only implemented on Windows.
Also removed a couple of unused variables that were causing compiler warnings.
Addresses issue https://github.com/LunarG/VulkanTools/issues/792
Change-Id: I6f04c3dfaa69d6581588ff7025f2e9c848b257ad
=> via: Display html file in browser automatically

via/via_system.cpp
Make text in vkvia console window easier to read:
- Changed vkcube window size from 500x500 to 250x250.
- Windows only: Added a sleep before displaying the vkvia.html
file so that user might see the output for a while before the
browser with the vkvia.html file covers it up. Added a sleep
after displaying the vkvia.html file so the user might be able
to bring the console to the front and see the console output.
This fix addresses https://github.com/LunarG/VulkanTools/issues/829
Change-Id: I396aa61f66e3751cd4915bed838913d0ad7cc2dd
=> via: Display console on Windows until user presses enter

layersvt/screenshot.cpp
Validation error would occur when VK_SCREENSHOT_FORMAT was set
to SINT/UINT. Added code to override the output format for this
case and set it to the same as the swapchain image format.
Also changed wording in several error messages.
Fixes issue https://github.com/LunarG/VulkanTools/issues/1737
=> Address validation errors in screenshot layer.

vkconfig/CHANGELOG.md, vkconfig/settings_tree.cpp, vkconfig/settings_tree.h, vkconfig/widget_setting_bool.cpp, vkconfig/widget_setting_enum.cpp, vkconfig/widget_setting_filesystem.cpp, vkconfig/widget_setting_flags.cpp, vkconfig/widget_setting_float.cpp, vkconfig/widget_setting_frames.cpp, vkconfig/widget_setting_int.cpp, vkconfig/widget_setting_list.cpp, vkconfig/widget_setting_list_element.cpp, vkconfig/widget_setting_string.cpp, vkconfig_core/override.cpp, vkconfig_core/setting.cpp, vkconfig_core/setting.h
This is what the validation layer settings would look like with the refactor of the layer manfest :
=> vkconfig: Make built-in validation layer optional

layersvt/screenshot.cpp
Previously, screenshot was using the mutexes from an accidentally exposed header file provided by the Validation Layers. Since they aren't installing that header, the definitions were missing when building an SDK.
The fix is to replace the use of platform specific mutex wrapper with std::mutex.
=> screenshot: Use std::mutex

layersvt/monitor.cpp
Error building on Ubuntu 20.04.
```
[  1%] Building CXX object layersvt/CMakeFiles/VkLayer_monitor.dir/monitor.cpp.o
/vulkan-sdk/1.3.230.0/source/VulkanTools/layersvt/monitor.cpp: In function 'VkResult vkCreateInstance(const VkInstanceCreateInfo*, const VkAllocationCallbacks*, VkInstance_T**)':
/vulkan-sdk/1.3.230.0/source/VulkanTools/layersvt/monitor.cpp:207:42: error: 'RTLD_NOW' was not declared in this scope
xcb.xcbLib = dlopen("libxcb.so", RTLD_NOW | RTLD_LOCAL);
^~~~~~~~
/vulkan-sdk/1.3.230.0/source/VulkanTools/layersvt/monitor.cpp:207:53: error: 'RTLD_LOCAL' was not declared in this scope
xcb.xcbLib = dlopen("libxcb.so", RTLD_NOW | RTLD_LOCAL);
^~~~~~~~~~
/vulkan-sdk/1.3.230.0/source/VulkanTools/layersvt/monitor.cpp:207:22: error: 'dlopen' was not declared in this scope
xcb.xcbLib = …
```
=> monitor: add include dlfcn.h

scripts/layer_factory_generator.py
CreateEvent and CreateSemaphore are macros defined in some windows header file, and the Validation layers moved this guard in such a way that the layer factory no longer is protected from it. The simplest fix is to manually include vulkan, which will include various windows headers, undefine the offending names, then include the layer_dispatch_table (which contains the macro defined names).
=> layer_factory: Guard against win32 defines

README.md, layersvt/README.md
Docs still mentioned `VK_LAYER_LUNARG_device_simulation` in a couple of places.
=> Removed DevSim references.

update_external_sources.sh, vkconfig_core/setting.h
This seemed to work fine on older Linux distributions (e.g. Ubuntu 16.04),
probably because the header file was implicitly included somewhere;
but it fails on newer distributions (e.g. Ubuntu 22.04).
Always explicitly including <limits> is painless and lets the project
build on all Linux versions.
=> vkconfig: include <limits>

layersvt/api_dump.h
When the indentation gets too high apidump would start reading other memory in the executable, which leads to humorous but highly incorrect output.
=> apidump: Use setfill/setw to prevent indentation overflow

build-android/build_all.sh
The Android build is quite aggressive, attempting to consume all available cores; large builds (particularly the api_dump layer) cause all the processes involved to consume 3+G of memory, causing physical and swap memory to be exhausted, which causes sporadic build failures as the OOM killer kills the compiler processes.
These changes allow the use of an environment variable $VT_BUILD_CORES to limit how many cores are in use; it also prevents the build from using additional parallel jobs if the load average is too high (on one 8-core system, the load average climbed to over 26 before the OOM killer started killing processes).
=> android: limit parallel builds

via/via_system_linux.cpp
Pop-OS also uses Ubuntu packages, this fixes it so Pop-OS also finds the SDK
=> vkvia: Fix not finding Ubuntu package on Ubuntu based distros

CMakeLists.txt
The vulkan validation layers update their CMake min to 3.17.2
Raise min accordingly
=> cmake: Raise minimum to 3.17.2

layersvt/api_dump.h, scripts/api_dump_generator.py
Big refactor to the codebase which cleans up many aspects of the code, to reduce the code generation time and compile time.
Changes include:
* Removing variadic templates, replacing them with explicit storage in the ApiDumpInstance class. There are only two places in the entire API where this is needed, making everything require a variadic template to handle these two cases is a bit much.
* Removing redundant `inline` statements for class member functions
* Removing the return type for many of the api_dump.h functions. Returning the stream operator was used in one place and one place only, and didn't require returning the ostream type to function.
* Factor out the dump_head functions. The actual values printed are easily replaced with a single function that takes the function name & …
=> Refactor api dump

layersvt/monitor.cpp, layersvt/screenshot.cpp, scripts/api_dump_generator.py, scripts/layer_factory_generator.py, vku/vk_layer_settings.cpp, vku/vk_layer_settings.h
This PR fixes API Dump, Monitor, Screenshot, and the vk_layer_settings utility to no longer use the VK_LAYER_EXPORT macro which was defined in vk_layer.h. The macro was recently removed thus all the projects using it must be updated.
In addition to defining the macro locally to each file, this commit removes function exporting for functions which do not need it. For Example, it was being added to each and every function in API Dump when only ~7 functions in the entire Vulkan interface need to be exported. Additionally, it was entirely removed from the vk_layer_settings utility due to the utility being a static library thus having no effect.
Fixes #1793
=> Remove usage of VK_LAYER_EXPORT

layersvt/api_dump.h, scripts/api_dump_generator.py
Originally API dump had no issues with blocking API calls, because it would only take the lock for printing after the function calls returned. But since the change to print the function name before calling down the chain (in case the function crashes) required printing, that meant the lock was taken before calling down the chain. If that function blocks then this stalls EVERY other API call from progressing, which may cause a dead lock.
The solution is to manually specify the functions which may block and have those functions revert to the original behavior (not print before calling down). This prevents deadlocks by not holding the lock during blocking Vulkan function calls.
To do this change and not just copy paste all of the code, the 'dump_function_head' function was added to …
=> apidump: Don't lock for functions that may block

CMakeLists.txt, build-android/android-generate.bat, build-android/android-generate.sh, layersvt/CMakeLists.txt, layersvt/api_dump.h, scripts/api_dump_generator.py, scripts/vt_genvk.py
NOTE: This uses the currently in progress #1771 PR as a base, and therefore is not ready for primetime. Expect a rebase on main when the refactor PR is complete. Until then, this PR contains commits of both
This PR adds support for the video extensions in API Dump. The video extensions were not supported initially because they required definitions for the various external types that were defined in video.xml but because these definitions live in a different xml file, they weren't generated. This PR fixes it by running the generator script over the video.xml files to produce text, html, and json header files that are then used by the existing API Dump code.
=> API Dump support video extensions

layersvt/api_dump.h, scripts/api_dump_generator.py
Move the logic for dertermining if something is a struct or union to be a hardcoded value instead of having to perform a runtime lookup. This is a possibility since whether a type is a struct or union is apart of the Vulkan API.
This fixes an issue introduced in the PR to support the video extensions where there is_struct & is_union functions only included the video API types, not the entire API.
=> apidump: Generate is_struct/is_union logic

layersvt/api_dump.h
The emplace() function will not update the value in the map if it is already present.
This is useful if you are labelling objects which get recycled. For examples, you might label a fence "Frame 1 Complete Fence" and then again "Frame 4 Complete Fence".
=> Make update_object_name_map() update on name re-assignment

CMakeLists.txt, layersvt/CMakeLists.txt, scripts/known_good.json, via/CMakeLists.txt
This will also removing the submodule and the update_external_sources steps...
I might follow this with adding the external libraries into the update_deps/known_good stuff. 
This repository is a huge build system mess \o/
I am a bit concerned with Android build, it's not clear how it works but it doesn't seem to use CMake...
=> cmake: move jsoncpp to knowngood to simply build steps

layersvt/api_dump.h, layersvt/screenshot.cpp
* Implement the AndroidLogcatBuf class that derives from std::streambuf which writes to the Android logcat on a per-line basis.
* Modify ApiDumpSettings to hold an instance of AndroidLogcatBuf, and make the output_stream to use that streambuf instead of the iostream one at initialization.
=> apidump: Use logcat instead of stdout for Android

scripts/api_dump_generator.py
VkAccelerationStructureTypeNV and VkBuildAccelerationStructureFlagsNV are aliased types which are explicitly used by the VK_NV_ray_tracing extension. Because apidump didn't know how to keep track of aliases and then fixup uses of aliased types into the real type, those two types had hand written typedefs. This commit is able to remove the hardcoding as well are removes both redundant code (self.trackedTypes) and dead code (str_VkStructureTypeToEnum).
Fixes #977
=> apidump: Use correct aliased types

layersvt/api_dump.h, scripts/api_dump_generator.py
The VK_EXT_descriptor_buffer extension adds a union with pointer elements. Because API Dumps union logic is naive, it prints the value of every element in the union regardless of whichever the 'active' element is, as it is not always possible to easily get the active element. VkDescriptorDataEXT contains pointers which are dereferenced resulting in a crash. Fixing it is straightforward because the parent structure VkDescriptorGetInfoEXT contains the type to use, so it is just a matter using the PARAMETER_STATE and VALIDITY_CHECKS functionality to set & get the type when printing out the contents of the union.
=> api_dump: Prevent crash in VkDescriptorDataEXT union

CMakeLists.txt, build-android/android-generate.sh
The extension was disabled due to issues with the transition from an NV ext to a KHR ext. This required a fix to the autogeneration, which was previously committed.
=> Enable VK_NV_cooperative_matrix

CMakeLists.txt, build-android/android-generate.sh, scripts/api_dump_generator.py, scripts/common_codegen.py
This extension was disabled due to not working with API dump, to which this commit fixes. The souce of the error was that vulkan safety critical modified vk.xml to change the supported="vulkan" to allow supported="vulkan,vulkansc". ApiDump's generator was only looking for vulkan, causing any extension that worked with both API's to be missed, causing the extension guard to not be added where required.
This commit also adds the SCI platform define to the hardcoded list.
Fixes #1840
=> Enable VK_QNX_external_memory_screen_buffer

CMakeLists.txt, layersvt/CMakeLists.txt
find_package(PythonInterp) is deprecated.
Use find_package(Python3).
Move codegen code to layersvt/CMakeLists.txt where it is actually used.
Create a VULKAN_REGISTRY variable to reduce code duplication.
Remove pointless cmake_minimum_required
=> cmake: Cleanup Python Generation Code

layersvt/CMakeLists.txt
A minor tweak to allow for building with iOS as a target.
Note I left out the case for VK_USE_PLATFORM_MACOS_MVK on purpose as it is deprecated. While there are probably people using this still for macOS, I thought it best not to encourage it moving forward, such as on iOS.
=> Add case for iOS builds with cmake

scripts/api_dump_generator.py
QNX types _screen_context, _screen_window and _screen_buffer are opaque types which must not be dereferenced.
=> Add QNX types.

layersvt/api_dump.h
api_dump.h stores the no-address setting in a variable called show_address. This requires inverting the setting to match what the rest of the api_dump code expects it to mean. This fixes a regression introduced by the transition to using the Layer Settings library from Vulkan-Utility-Libraries.
=> apidump: Fix regression in the NoAddr setting

CMakeLists.txt, layersvt/test/CMakeLists.txt, scripts/known_good.json, via/CMakeLists.txt
Simplifies the CMake code since Vulkan-Loader now exports itself in an easy to consume format. No need to create our own target, just use the provided one.
=> build: Use Vulkan-Loader find_package support

scripts/api_dump_generator.py
vkGetDeviceProcAddr specifies that only function pointers of enabled extensions should be exposed. If an extension is not enabled, vkGetDeviceProcAddr should return NULL. The same goes for vkGetInstanceProcAddr, except that the extension only needs to be available. Some users like winevulkan rely on this behaviour and break when used with the current API dump layer.
Assuming that drivers and other layers act accordingly and return NULL for non-enabled entrypoints, we can mirror this by simply returning NULL when the corresponding dispatch table entry is NULL.
=> apidump: Return NULL in Get*ProcAddr for disabled extensions

layersvt/monitor.cpp, layersvt/screenshot.cpp, layersvt/vk_layer_table.cpp, layersvt/vk_layer_table.h, scripts/known_good.json
The functions and structs in vk_dispatch_table.h have been updated to use a 'vku' prefix instead of 'vul'. Thus, this repo needs to update to it so the next header update goes smoothly.
=> layers: Update to new names in vk_dispatch_table.h

layersvt/api_dump.h, scripts/api_dump_generator.py
The members of VkPipelineRenderingCreateInfo should be ignored (except for viewMask) when either VK_GRAPHICS_PIPELINE_LIBRARY_PRE_RASTERIZATION_SHADERS_BIT_EXT or VK_GRAPHICS_PIPELINE_LIBRARY_FRAGMENT_SHADER_BIT_EXT is set in the flags of VkGraphicsPipelineLibraryCreateInfoEXT.
Doing this requires looking for the VkGraphicsPipelineLibraryCreateInfoEXT struct in the pNext chain of VkGraphicsPipelineCreateInfo.
This commit also cleans up a few things:
* Use enum name instead of value in pNext_trampolines for loader structs
* Eliminate the name & type fields in the PARAMETER_STATE since they were unused.
* Remove whitespace
Fixes #1860
=> apidump: Check for Graphics Pipeline Library properly.

layersvt/api_dump.h, layersvt/screenshot.cpp, scripts/api_dump_generator.py, scripts/known_good.json, vkconfig_core/test/test_override.cpp
Also fix regression in Environment Variable naming: 
The use of the layer settings library changed the established names for
the settings set through environment variables. This commit addresses
this by using the compatibility namespace feature to ensure existing
users aren't affected.
=> Update to latest Vulkan-Utility-Libraries

scripts/known_good.json
The Vulkan-Tools repo is only used for testing, but known_good.json did not specify that.
=> deps: Mark Vulkan-Tools as a test dependency

layersvt/screenshot.cpp
Since queue handles are used to dispatch down the call chain, there is no reason to skip adding them in any case. This occurs if the screenshot setting is empty.
=> screenshot: Always add queues

vkconfig_core/test/test_path.cpp
@christophe-lunarg 
This is a 'possible' fix for this issue:
https://github.com/LunarG/VulkanTools/issues/1897
We need this test corrected so we can get VulkanTools into CI for macOS. I took a look at the test, but I don't know why it's failing only on macOS, other than the relative paths isn't setup correctly. There may be a better way to fix this than my hack, if so, please chime in, as the issue is about a month old now.
=> Unit test on macOS potential fix

CMakeLists.txt
Allows simplifying the rest of the CMake code
=> cmake: Only require the CXX compiler

tests/CMakeLists.txt
Currently these custom targets are always dirty.
It's simpler to just use execute_process and utilize CMake's copy_if_different command during the configuration step.
=> cmake: Fix constant dirty builds

scripts/known_good.json, via/CMakeLists.txt
Currently vkvia will fail to run due to dependency on libjsoncpp.so
Detect and prefer jsoncpp_static when possible.
closes #1933
=> Fix vkvia regression

CMakeLists.txt, layersvt/CMakeLists.txt, via/CMakeLists.txt
Neither vkconfig / vkvia currently need/use xcb, x11, or the wayland libraries.
Move the WSI code to the layersvt directory where it is actually used.
=> cmake: Cleanup WSI code

scripts/known_good.json, via/CMakeLists.txt
The main thing to note is we want to use the STATIC version of jsoncpp
By default pkg-config was pointing to the SHARED version
I explicitly turn this off in the known_good.json now so now the pkg-config path will work for us for the linux tarball.
=> Use pkg-config for jsoncpp if possible

layersvt/screenshot.cpp
The check should have been
```
value != "USE_SWAPCHAIN_COLORSPACE"
```
This is how it was originally written:
```
} else if (strcmp(vk_screenshot_format, "USE_SWAPCHAIN_COLORSPACE") != 0) {
```
I also made colorSpaceFormat an enum class.
closes #1906
=> Fix screenshot error

via/CMakeLists.txt
Currently UNIX platforms like linux/mac default to using package config and don't use CMake config.
This broke our existing SDK process for jsoncpp
=> Fix SDK regression

layersvt/api_dump.h
If the 'file' option is set in the settings file, it will now be used to determine whether to write to a file output or not. Previously it was being ignored entirely, resulting in all output heading to a file.
=> apidump: Fix file setting being ignored

via/via_system_linux.cpp
Fix the SDK detection based on Explicit layer location which was recently updated in the SDK setup scripts.
=> VIA: Fix SDK detection

.github/workflows/ci.yml, layersvt/CMakeLists.txt
Apples App store rules require dynamic libraries be packaged as Frameworks for iOS. This requirement is not applied for macOS, so all iOS libraries should be packaged as Frameworks moving forward to comply with Apples policy. Although this layer in particular is not likely to be shipped in an application bundle, it is being made a Framework as well to be consistent with all the other layers.
=> Build API Dump as a framework for iOS

layersvt/CMakeLists.txt
This adds two version field strings to the iOS Framework Info.plist files. These are needed for App store compatibility.
=> apple: Add version strings to Frameworks

layersvt/screenshot.cpp
This is treated as an error and fails to build
=> screenshot: Fix warning and remove extra begin

vkconfig/CHANGELOG.md, vkconfig/main.cpp, vkconfig3/main.cpp
Note that here I copied my test built executable into my SDK 1.3.280.beta2 directory but this is going to be available in next SDK
=> vkconfig: Add support for command line outputs on Windows when using 'Command Prompt'

vkconfig/CHANGELOG.md, vkconfig/dialog_layers.cpp, vkconfig/mainwindow.cpp, vkconfig/mainwindow.h, vkconfig_core/configuration_manager.cpp, vkconfig_core/environment.h, vkconfig_core/layer.cpp, vkconfig_core/layer.h, vkconfig_core/parameter.cpp
1. All implicit layers must have disable_environment in their manifest
2. If disable_environment is set (to anything) in the environment, the layer will not be enabled
3. If enable_environment is in the layer's manifest, then the layer wont be enabled UNLESS the exact string in enable_environment is set in the environment.
=> vkconfig: Better handle implicit layer

vkconfig/mainwindow.cpp, vkconfig/mainwindow.h, vkconfig/mainwindow.ui
New system tray menu:
Double clicking on the icon will show the main window.
=> vkconfig: Refactor system tray, extended menu

vkconfig/mainwindow.cpp
Make sure `QGuiApplication::setQuitOnLastWindowClosed` is updated with current value of UseSystemTray when closing
=> vkconfig: Treak system tray

vkconfig/mainwindow.cpp, vkconfig/settings_tree.cpp, vkconfig/settings_tree.h
I made and tweak for when the message is displayed based on your feedback in here:
https://gitlab.khronos.org/vulkan/Vulkan-SDK-Packaging/-/issues/1491
Now, the message is displyed only is the user is changing setting while an application is launched. The first time.
=> vkconfig: Only display setting are not change dynamically in context

.github/workflows/ci.yml, BUILD.gn, scripts/gn/DEPS, scripts/gn/generate_vulkantools_layers_json.py, scripts/gn/gn.py, scripts/gn/secondary/build_overrides/build.gni, scripts/gn/secondary/build_overrides/lunarg_vulkantools.gni, scripts/gn/secondary/build_overrides/vulkan_headers.gni, scripts/gn/secondary/build_overrides/vulkan_utility_libraries.gni, scripts/gn/update_deps.sh
Add GN build support for the api dump layer only. 
This is needed by Google for Chromium ANGLE builds so that apidump can be built in-tree and loaded as an ANGLE debugging output option.
Very closely based on the GN build infrastructure found in the VVL repo.
=> Add VulkanTools apidump GN build

vkconfig/CHANGELOG.md, vkconfig/CMakeLists.txt, vkconfig/README.md, vkconfig/main.cpp, vkconfig/mainwindow.cpp
This reverts commit a2cfb54fafbadcf67a7dab7305732c9691d300b1.
Windows 11 doesn't support hiding the console so to get text output, the user has to redirect to a file or use a different console than Command Prompt.
=> Revert "vkconfig: Add 'Command Prompt' support with command line mode"

scripts/gn/generate_vulkantools_layers_json.py
The gn build json file generator script needs to modify the default VulkanTools json filename format to match what ANGLE expects, i.e.:
VkLayer_api_dump.json -> VkLayer_lunarg_api_dump.json
=> Change gn json file generator filename output

layersvt/api_dump_layer.md, layersvt/screenshot_layer.md
Note that `VK_APIDUMP_LOG_FILENAME` is still supported for backward compatibility reason but `VK_API_DUMP_LOG_FILENAME` is the expect name.
Environment variable layer settings names are built this way:
`VK_[VENDOR_][LAYER_NAME_POSTFIX_]SETTING_NAME`
For Android, the name are build similarly:
`debug.vulkan.[VENDOR.][LAYER_NAME_POSTFIX.]setting_name`
The layer settings library will first search the full name :
`debug.vulkan.lunarg.api_dump.setting_name`
And then trim the vendor name:
`debug.vulkan.api_dump.setting_name`
And then trim the layer name:
`debug.vulkan.setting_name`
Enabling using the same setting for multiple layers and also as a trick to be more backward compatible with the previous layer setting system and each layer implementation that were quite inconsistent.
An …
=> layer: Update Android layer settings doc

vkconfig/mainwindow.cpp, vkconfig/mainwindow.h, vkconfig3/mainwindow.cpp, vkconfig3/mainwindow.h
The combo-box for selecting what layers are being controlled is not correctly signaling its corresponding slot. As a result the configurator never gets updated. Checkable actions use the "toggled" signal rather than "triggered". A simple if statement was also added so only the selected action updates the configurator.
#2046
=> VkConfig: Fix tray combo-box signal method

layersvt/test/CMakeLists.txt, layersvt/test/layer_test_helper.cpp, layersvt/test/test_api_dump.cpp
The CMake code mixed up the layer binary directory with the test executable directory, causing tests to look in the layer binary directory by mistake.
=> apidump: Fix tests looking in wrong output folder

layersvt/test/CMakeLists.txt, layersvt/test/test_api_dump.cpp
The tests are failing on windows due to a mismatch in the working directory that the executable is being run and the directory that is assumed to be where Api Dump will output. By querying where the current directory is, the tests can always find the output of Api Dump.
=> Look for api dump test output in current directory

vkconfig_core/configurations/2.2.2/Crash Diagnostic.json
macOS is not supported by the diagnostic layer
=> Update Crash Diagnostic.json

layersvt/api_dump.h, layersvt/generated/api_dump.cpp, scripts/api_dump_generator.py
Replaces the usage of recursive_mutex with the standard mutex. Replaces explicit calls of lock() & unlock() with lock_guard.
=> apidump: Use regular mutex & lock guards

vkconfig_core/type_log.cpp, vkconfig_core/type_log.h, vkconfig_gui/tab_configurations.cpp
Matches the Vulkan-Loader's own log levels.
=> Replace "implem" with "driver" loader log level

.github/workflows/ci.yml
macOS-12 is being removed from github actions.
=> ci: Update to macOS-13 in github actions

vkconfig_core/configuration.cpp, vkconfig_core/configuration.h, vkconfig_core/layer_manager.cpp, vkconfig_core/layer_manager.h, vkconfig_core/test/test_configuration.cpp, vkconfig_gui/main.cpp, vkconfig_gui/settings_tree.cpp, vkconfig_gui/widget_layer_version.cpp, vkconfig_gui/widget_layer_version.h
=> vkconfig3: Support multiple layers of the same api version

vkconfig_cmd/main.cpp, vkconfig_cmd/main_doc.cpp, vkconfig_cmd/main_layers.cpp, vkconfig_cmd/main_reset.cpp, vkconfig_core/configuration_manager.cpp, vkconfig_core/configuration_manager.h, vkconfig_core/configurator.cpp, vkconfig_core/configurator.h, vkconfig_core/configurator_signal.cpp, vkconfig_core/executable_manager.cpp, vkconfig_core/executable_manager.h, vkconfig_core/layer_manager.cpp, vkconfig_core/layer_manager.h, vkconfig_core/path.cpp, vkconfig_core/path.h, vkconfig_core/serialization.h, vkconfig_core/test/test_layer_manager.cpp, vkconfig_gui/main.cpp, vkconfig_gui/mainwindow.cpp, vkconfig_gui/tab_configurations.cpp, vkconfig_gui/tab_diagnostics.cpp
The new approach, delete all the saved files and registry entries and restart vkconfig3 that will setup up itself like on first install.
=> vkconfig3: Redesign reset to default

vkconfig_core/configurations/3.0.0/Portability.json, vkconfig_core/configurator.cpp, vkconfig_core/executable.cpp, vkconfig_core/executable_manager.cpp, vkconfig_core/layer_manager.cpp, vkconfig_core/path.cpp, vkconfig_core/path.h, vkconfig_core/test/test_executable_manager.cpp, vkconfig_core/test/test_path.cpp, vkconfig_gui/CHANGELOG.md, vkconfig_gui/mainwindow.ui, vkconfig_gui/settings_tree.cpp, vkconfig_gui/tab_applications.cpp, vkconfig_gui/tab_configurations.cpp, vkconfig_gui/tab_documentation.cpp, vkconfig_gui/tab_layers.cpp, vkconfig_gui/vkconfig.pro, vkconfig_gui/widget_setting_group.cpp, vkconfig_gui/widget_setting_group.h, vkconfig_gui/widget_tab_configurations_layer.cpp
- Fix `${VULKAN_SDK}` path in logging
- Fix `${VULKAN_SDK}` overriding system path when set
- Add `vulkaninfo` to default executable
- Add `${VULKAN_PROFILES}`
- Fix group settings visibility which depends on enum value
- Clean up layer paths on macOS
- Improve layer control UI combobox on macOS
- Resolve dark theme difficult link to read
=> vkconfig3: beta bugfixing

layersvt/generated/api_dump.cpp, scripts/api_dump_generator.py
Make sure to get the dispatch key before destroying the instance as it
might not be valid anymore after calling `DestroyInstance`.
=> api_dump: Fix destroy instance dispatch table

vkconfig_cmd/main.cpp, vkconfig_core/application_singleton.cpp, vkconfig_core/application_singleton.h, vkconfig_core/layer.cpp, vkconfig_core/layer.h, vkconfig_core/layer_preset.cpp, vkconfig_core/layer_preset.h, vkconfig_core/parameter.cpp, vkconfig_core/parameter.h, vkconfig_core/registry.cpp, vkconfig_core/test/layers/VK_LAYER_LUNARG_test_04.json, vkconfig_core/test/layers/VK_LAYER_LUNARG_test_07.json, vkconfig_core/test/layers/VK_LAYER_LUNARG_test_08.json, vkconfig_core/test/resources.qrc, vkconfig_core/test/test_application_singleton.cpp, vkconfig_core/test/test_configuration.cpp, vkconfig_core/test/test_layer.cpp, vkconfig_core/test/test_layer_manager.cpp, vkconfig_core/test/test_layer_preset.cpp, vkconfig_core/test/test_parameter.cpp, vkconfig_core/test/test_path.cpp, vkconfig_gui/main.cpp
- Add layers env vars load unit tests
- Add single instance unit tests
- Add `Layer::FindPresetIndex` tests
- Add `Layer::GetActualControl` tests
- Add `HasMissingLayer` test
- Add `OrderParameter` test
=> vkconfig3: Add more unit tests

vkconfig_gui/resources.qrc, vkconfig_gui/tab_configurations.cpp
For SDK 1.4.304.1, the loader can't be updated so here is an ugly workaround.
The loader messages only configuration is removed and "Include Vulkan Loader Messages" can only be check if "Include Vulkan Layers" is checked. A tool tip is added to explain the workaround.
=> vkconfig: Workaround loader message bug requiring layers override

vkconfig_gui/mainwindow.ui
The previous URL won't work for people outside LunarG. This URL should point to the latest public spec.
=> vkconfig: update url to point to LunarG's latest public antora spec

vkconfig_core/configurator.cpp, vkconfig_core/configurator.h, vkconfig_core/path.cpp, vkconfig_core/path.h, vkconfig_core/test/test_version.cpp, vkconfig_core/type_platform.cpp, vkconfig_core/type_platform.h, vkconfig_core/util.cpp, vkconfig_core/util.h, vkconfig_core/version.cpp, vkconfig_core/version.h, vkconfig_gui/CHANGELOG.md, vkconfig_gui/mainwindow.cpp, vkconfig_gui/mainwindow.h, vkconfig_gui/mainwindow.ui, vkconfig_gui/tab_preferences.cpp, vkconfig_gui/tab_preferences.h
=> vkconfig: Add Vulkan SDK release detection

.github/workflows/ci.yml
This prevents CI jobs from being duplicated when a PR is made for a branch in the repo.
=> ci: Prevent double runs for branches in repo with PR's

CMakeLists.txt, vkconfig_cmd/CMakeLists.txt, vkconfig_core/CMakeLists.txt, vkconfig_core/test/CMakeLists.txt, vkconfig_gui/CMakeLists.txt
Internally, we build the Vulkan Configurator against a static build of Qt (Qt6 now) that is also built using the static MSVC runtime (this is also used for the installer framework). This allows an executable to run without any additional DLL support.
We have the need to build Vulkan Configurator using our internal Qt6 build, but also to link against the static MSVC runtime, but we don't want the rest of VulkanTools to have this requirement. 
This change allows VulkanTools to pass:
-DUSE_STATIC_CRT_VKFG=ON
CMAKE_PREFIX_PATH can point to a version of Qt that uses the static runtime, and vkConfig only will be built with the static MSVC runtime.
=> Allow for building vkConfig against static versions of Qt

scripts/known_good.json, via/CMakeLists.txt
Compatibility with CMake < 3.5 has been removed from CMake 4.0
jsoncpp before version 1.9.6 will cause an error as a result
Link to release notes:
https://github.com/open-source-parsers/jsoncpp/releases/tag/1.9.6
=> cmake: Update jsoncpp to fix CMake 4.0 error

vkconfig_core/doc.cpp, vkconfig_core/layer.cpp, vkconfig_core/vulkan_util.cpp, vkconfig_core/vulkan_util.h, vkconfig_gui/CHANGELOG.md
- Clarify VK_EXT_layer_settings variable names in generated layer documentation
- Hide `advanced` settings from generated layer documentation, used only by layer developers
- Fix broken generated layer doc links
- When we click on the layer setting label, it jumps to the details layer setting below.
- When we click on `Variables Key`, it opens the general layer settings documentation https://vulkan.lunarg.com/doc/sdk/1.4.309.0/windows/layer_configuration.html
When we click on `Setting Variables`, it opens the general layer settings documentation https://vulkan.lunarg.com/doc/sdk/1.4.309.0/windows/layer_configuration.html
=> vkconfig: Improved generated layer documentation

vkconfig_core/doc.cpp, vkconfig_core/layer.cpp, vkconfig_core/setting.cpp, vkconfig_core/setting.h, vkconfig_gui/CHANGELOG.md
Here is what it looks like:
Also show the layer settings hierarchy:
=> vkconfig: Use table to display detail setting methods doc

scripts/known_good.json
It was a transitive dependency from Vulkan-Tools which, with the specified commit, no longer requires Volk to build.
=> build: Drop Volk dependency

vkconfig_gui/CHANGELOG.md, vkconfig_gui/main.cpp
QT_QPA_PLATFORM can be used to for manually setting the underlying display driver on Linux : wayland, xcb, xwayland. 
The SDK build use static Qt which doesn't containt the Qt plugins causing Qt the crash at inilialization.
=> vkconfig: Fix QT_QPA_PLATFORM crashes

vkconfig_core/configurator.cpp, vkconfig_gui/CHANGELOG.md
Eg:
```
khronos_validation.check_shaders_caching = true
```
=> vkconfig: Add layer setting deps to generated vk_layer_settings.txt

CMakeLists.txt, layersvt/CMakeLists.txt, layersvt/generated/api_dump.cpp, layersvt/generated/api_dump_text.cpp, scripts/api_dump_generator.py
cmake: Find Qt dependencies last & api_dump: Add missing colon in text output
* Fixes a bug where system installed Vulkan-Headers were used instead of
known_good.json due to Qt searching for Vulkan in its own package searching.
cmake: Generate apidump when api_dump_generator.py changes
* Only happens if VT_CODEGEN is on.
api_dump: Add missing colon in text output
* Colon after return type got dropped in commit https://github.com/LunarG/VulkanTools/commit/c20cdda69ac017c95fb7ba31db8498dc88f67d2f.
=> cmake: Find Qt dependencies last and api_dump: Add missing colon in text output

CMakeLists.txt, layersvt/CMakeLists.txt
The file(GLOB) command works differently than I thought, causing the glob to match the WHOLE PROJECT.
Is not a hard fix, but only was found after trying to clean my build and accidentally deleted everything.
=> cmake: Fix bad GLOB for generated files

via/CMakeLists.txt
In vcpkg, there is only one build type installed. JsonCpp::JsonCpp is always available from an installed jsoncpp.
=> vkvia: Maybe link to JsonCpp::JsonCpp

CMakeLists.txt, layersvt/CMakeLists.txt
Creates a new target that is run on-demand with the vt_codegen target. A new target vt_codegen_as_needed creates the necessary file dependencies to allow the build tool to know when to rerun codegen.
This separationg of on-demand and as-needed is so that tools using the codegen can have it run automatically as changes are made while the vt_codegen target can be used to *force* codegen to run in case the file level dependencies aren't accurate.
=> cmake: Run codegen on demand

layersvt/api_dump.h, layersvt/generated/api_dump_dispatch.h, scripts/generators/api_dump_generator.py
for https://github.com/LunarG/VulkanTools/issues/1967 (likely others, so maybe not close it completely)
This was 
1. Something I wanted before
2. A quick test how easy @charles-lunarg refactoring made this change.... it was really easy to add, so good job Charles! :confetti_ball:  
-----
Before
After
=> dump: Use hex for VkDeviceAddress

CMakeLists.txt, vkconfig_core/CMakeLists.txt, vkconfig_core/configurator.cpp, vkconfig_core/configurator.h, vkconfig_gui/CHANGELOG.md, vkconfig_gui/mainwindow.ui, vkconfig_gui/tab_preferences.cpp, vkconfig_gui/tab_preferences.h
Fixed .X SDK release invalid notifications by setting `SDK_VERSION` cmake variable to a SDK version
=> vkconfig: Enabled passing SDK version to vkconfig

CMakeLists.txt
When building using our local version of Qt, we need to ensure we use the static runtime library for vkConfig builds. This was working, but recent changes caused a regression when tests are built. This small change restores using the static runtime when tests are not built as well.
=> Use static RT when static QT

vkconfig_core/layers/layers_schema.json
Removes an illegal trailing comma in the JSON schema, preventing it being loaded by some clients (e.g. LSPs).
=> vkconfig: Fix malformed JSON schema

layersvt/api_dump.h, layersvt/generated/api_dump_video_implementation.h, scripts/generators/api_dump_generator.py
Adding the necessary special cases turned out to be a bit more work than I originally thought. This was because there was a bug in the get_validity_check generator logic, as well as the complex validity requirements that the previously skipped struct members had.
=> Fix skipped std video h265 hrd parameters

scripts/base_generator.py, scripts/vulkan_object.py
basetypes and platform types are no longer used by API Dump, so they can safely be removed from the local copy of vulkan_object.py & base_generator.py.
=> scripts: Remove unused custom changes to vulkan_object.py

layersvt/api_dump.h
Was always printing nullptr instead of the address of the element in the array.
=> api_dump: Fix array elements not printing addresses
